### ISSUE TITLE
Pretre Ombre / Shadow Prist

### ISSUE THREAD

**Issue by Garrpp** [AshamaneProject/AshamaneCore#1017]
Débuger la classe de prêtre ombre 

Forme du Vide 
Ne tiens pas comme elle devrais, il es donc impossible d'utilisé des sors comme "Éclair de vide"

Le talent Misère ne fonctionne pas. 

Le talent de l'arme prodigieuse "Convocation du vide" ne fonctionne pas 

voilà pour le moment les gros soucis de la classe que j'ai repéré

**Comment by cooler-SAI** [comment]
Wrong format
