### ISSUE TITLE
[World] All Transmogrifiers in major cities are bugged out.

### ISSUE THREAD

**Issue by johnsvc** [AshamaneProject/AshamaneCore#1027]
**Description:**

All transmog npcs in major cities are not functional, missing the normal transmog window, instead they are only selling random transmog gears.

http://www.wowhead.com/search?q=transmogrifier

**Current behaviour:**

Transmog npcs are vendors only as right now, missing transmog function.

**Expected behaviour:**

Transmogrifiers should have normal transmog function, or, have a gossip menu for players to choose from whether they want to transmog or buy transmog items the vendors offer.

**Project(s): <-- Mandatory**

 Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

c614b920b004

**Database version**

ADB 7.3.5 with latest commits as 6th May.

**Comment by Sefrenia-Caecias** [comment]
Fixed ;) 

https://github.com/AshamaneProject/AshamaneCore/commit/03c0dcffa415bd2a51ab40bf9ce0e4973bc0dabd
