### ISSUE TITLE
[SQL Patch] Karthax Loot Table

### ISSUE THREAD

**Issue by Questiero** [AshamaneProject/AshamaneCore#1028]
**Description :**
This is my first attempt with SQL, it should add the loot table for the NPC Karthax.

**Usefull Wowhead links :**
http://www.wowhead.com/npc=111731/karthax

**SQL :**
[Karthax_loot_table.txt](https://github.com/AshamaneProject/AshamaneCore/files/1977074/Karthax_loot_table.txt)

**Comment by Traesh** [comment]
Hello, thanks for the help :)

I checked and all the loots seems good, but i'm not sure you did understand the reference_loot_template correctly

https://puu.sh/Ah6yj/431148026a.png

reference_loot_template is usefull to make a "group" of loots, to
- ensure you can only loot one item from that group X times (for example, we can use it for boss loots, to ensure it will only drop 2 good items)
AND/OR
- reference the same loots on multiple mobs if they loot the same items, to avoid duplicated data


You have to "reference" it from the creature_loot_template by adding a line with item = 0 but reference = reference_loot_template.entry

In this case, you do not reference it from the creature_loot_template (so it will never be used), and i don't see any necessity to use reference_loot_template in the first place

**Comment by Questiero** [comment]
Sorry, I heard that the looted gear needed to be in reference_loot_template, here is the version without it !
[Karthax_loot_table_wo_reference.txt](https://github.com/AshamaneProject/AshamaneCore/files/1977596/Karthax_loot_table_wo_reference.txt)

**Comment by Traesh** [comment]
It's true for bosses only :) Thanks for the patch
