### ISSUE TITLE
[BUG] Rogue Spell : Pick Lock

### ISSUE THREAD

**Issue by cooler-SAI** [AshamaneProject/AshamaneCore#1043]
**Description:**

Spell does'nt work correctly, I can't unlock items, Have a message : Your skill not high enought
http://www.wowhead.com/spell=1804/pick-lock

**Current behaviour:**

very bad bug(((

**Expected behaviour:**

You can't unlock items lover than 305 skill

**Project(s): <-- Mandatory**

- [x] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

https://github.com/AshamaneProject/AshamaneCore/commit/e447ccbcf43f0cdebe8166ade0448c1fb243ba78

**Database version**

ADB last

**Operating system:** Win 10

**Comment by HannibalRoG** [comment]
Already here #498
