### ISSUE TITLE
[vs2017]Compiler Error C2678

### ISSUE THREAD

**Issue by hygfrtqwe** [AshamaneProject/AshamaneCore#1045]
unit.cpp 6795 
unit.cpp 7612

 return aurEff->GetCasterGUID() == caster->GetGUID() && (aurEff->GetMiscValue & spellProto->GetSchoolMask());

  return aurEff->GetCasterGUID() == attacker->GetGUID() && (aurEff->GetMiscValue & spellProto->GetSchoolMask());

**Comment by HannibalRoG** [comment]
Missing important and mandatory info, issue not valid.
