### ISSUE TITLE
Felblade

### ISSUE THREAD

**Issue by wwolegion** [AshamaneProject/AshamaneCore#1049]
**Description:**

http://www.wowhead.com/spell=213241/felblade does not work.
Also some spam errors when using it:
`Script: `spell_dh_felblade` Spell: `232893`: function SpellScript::GetHitUnit was called, but function has no effect in current hook!`

**Project(s): <-- Mandatory**

- [ ] Issue found playing in Live Ashamane Private Server.
- [x] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

https://github.com/AshamaneProject/AshamaneCore/commit/94e70b5343af93bceb05c4772d07dcef62eddd9f

**Database version**

ADB 735

**Operating system:** Windows x64

**Comment by HannibalRoG** [comment]
#5
