### ISSUE TITLE
Worgen starts from Northshire

### ISSUE THREAD

**Issue by Szone** [AshamaneProject/AshamaneCore#1052]
**Description:**

Worgen starts from Northshire after last update 

**Current behaviour:**

![image](https://user-images.githubusercontent.com/2180820/39769729-aac1ee40-52f5-11e8-9dfb-9ab1c444bb99.png)

**Project(s): <-- Mandatory**

- [ ] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

TrinityCore rev. 9255db8133bc 2018-05-08 12:16:16 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) 

**Database version**

ADB735

**Operating system:** Ubuntu server 18.04

**Comment by conan513** [comment]
Confirmed but I found this 2-3 weeks before. I thought it’s only on my fork and I broke something.

**Comment by Szone** [comment]
@cooler-SAI issue still persist.

**Comment by Szone** [comment]
@cooler-SAI issue still persist.
