### ISSUE TITLE
Elwynn Forest (Part 2)

### ISSUE THREAD

**Issue by ObsVrae** [AshamaneProject/AshamaneCore#1056]
- In the initial zone of humans, the blackrock spies sometimes do not let you select them. (NPC)(http://www.wowhead.com/npc=49874/blackrock-spy).

- In the initial zone of humans,the northshire peasant do not do the animations they should do. (NPC) (http://www.wowhead.com/npc=11260/northshire-peasant).

- In the initial zone of humans, the blackrock spys spies that are in stealth do not move. (NPC)(http://www.wowhead.com/npc=49874/blackrock-spy).

-  In the initial zone of humans, the guards on the side of Sheriff McBride (http://www.wowhead.com/npc=197/marshal-mcbride) should not carry any flag. These guards have 598 thousand HP instead of 2078 thousand.

-  In the initial zone of humans, when you kill a blackrock worg (http://www.wowhead.com/npc=49871/blackrock-worg), who was attacked by the Stormwind infantry (http://www.wowhead.com/npc=49869/stormwind-infantry), the guard stands still instead of being in combat mood.

**Comment by cooler-SAI** [comment]
cosmetic......not cricical....

**Comment by Sefrenia-Caecias** [comment]
-Repaired Blackrock Spy: removed npcflag 2 erroneous that made it difficult to select for the attack; added random movement.
-Repaired Northshire Peasant: now cut trees and have random movement with logs, but not PathID.
-Repaired Stormwind Royal Guard: eliminated defective aura.
-Without changes, Stormwind Infantry: it has attached a Core script in its template; invokes Blackrock Worg and does not recover life by default, as part of an internal event.

-----------------------------------------------------------------

-Reparados Blackrock Spy: eliminada npcflag 2 errónea que dificultaba su selección para el ataque; añadido movimiento random.
-Reparados Northshire Peasant: ahora talan árboles y poseen moviiento random con troncos, pero no PathID.
-Raparados Stormwind Royal Guard: eliminada aura defectuosa.
-Sin cambios, Stormwind Infantry: posee anexado un script de Core en su template; invoca Blackrock Worg y no recupera vida de manera predeterminada, como parte de un event interno.

**Comment by Sefrenia-Caecias** [comment]
-Stormwind Royal Guard: refrozado `smart_scripts`; added correct aura only to patrols with PathID.
-Blackrock Spy: added entry `pickpocketloot`; special credits to @HannibalRoG.

--------------------------------------

-Stormwind Royal Guard: refrozado `smart_scripts`; agregada aura correcta sólo a patrullas con PathID.
-Blackrock Spy: agregada entrada `pickpocketloot`; créditos especiales a @HannibalRoG.
