### ISSUE TITLE
Northshire (All)

### ISSUE THREAD

**Issue by ObsVrae** [AshamaneProject/AshamaneCore#1059]
- In the initial zone of humans, the northshire guard (NPC) (http://www.wowhead.com/npc=1642/northshire-guard) are at level 90 when they should be at level 115.

- In the initial zone of humans, the Stormwind Royal Guards (NPC) (http://www.wowhead.com/npc=42218/stormwind-royal-guard) are at level 100 when they should be at level 110.

- In the initial zone of humans, Brother Paxton (NPC) (http://www.wowhead.com/npc=951/brother-paxton) should go around while the Stormwind Infantry (NPC) (http://www.wowhead.com/npc=49869/stormwind-infantry) asks for help, he reply and heals them.

- In the initial zone of humans, the Goblin Assassins (NPC) (http://www.wowhead.com/npc=50039/goblin-assassin) do not move.

- In the initial zone of humans, Injured Stormwind Infantry (NPC) (http://www.wowhead.com/npc=50047/injured-stormwind-infantry) do not have the aura of when a dead npc has booty.

- In the initial zone of humans, the quest Extinguishing Hope (QUEST) (http://www.wowhead.com/quest=26391/extinguishing-hope) It does not give you the Fire Extinguisher buff (SPELL) (http://www.wowhead.com/spell=80209/fire-extinguisher), so it does not go away on your back, even if it's in your backpack.

- The Stornwind Guard (NPC)  (http://www.wowhead.com/npc=1423/stormwind-guard) that should be going up  and down the road from Northshire to Goldenshire, is quietest in the middle of the road.

**Comment by Sefrenia-Caecias** [comment]
-Northshire Guard: set level at 115.
-Stormwind Royal Guard: set level at 110.
-Brother Paxton: created 'SmartAI'; will cast on friendly goals Power Word: Fortitude, Renew and Prayer of Healing, when certain requirements are met; added random movement.
-Goblin Assassin: added random movement.
-Injured Stormwind Infantry: no changes (the premise is not understood).
-Fire Extinguisher: no changes.
-Stormwind Guard: no changes (there are 62 of them).

---------------------------------------------------------

-Northshire Guard: establecido nivel en 115.
-Stormwind Royal Guard: establecido nivel en 110.
-Brother Paxton: creado 'SmartAI'; casteará en objetivos amistosos Power Word: Fortitude, Renew y Prayer of Healing, al cumplirse ciertos requisitos; añadido movimiento random.
-Goblin Assassin: añadido movimiento random.
-Injured Stormwind Infantry: sin cambios (no se entiende la premisa).
-Fire Extinguisher: sin cambios.
-Stormwind Guard: sin cambios (hay 62 de ellos).
