### ISSUE TITLE
Bug Void talon 

### ISSUE THREAD

**Issue by Soyis** [AshamaneProject/AshamaneCore#145]
**Description:**
J'ai réussi a trouver le portail pour obtenir les serres du vide de l’étoile noir ( drop 100% une des monture les plus rare de dreanor ) http://www.wowhead.com/item=121815/voidtalon-of-the-dark-star . Mais Quand j'ai cliqué sur le portail mon jeu a crash et le portail a disparue si il est possible de me donner la monture et de régler le bug car c'est extrêmement frustrent 

**Usefull Wowhead links:**

**Comment by Nexon99** [comment]
Bonjour, @Soyis merci d'avoir reporté ce bug. Je peux comprendre que cela soit frustrant pour toi mais nous ne donnons pas d'objet aux joueurs (sans preuves). Il faudra donc attendre un correctif pour pouvoir obtenir la monture.

**Cordialement.**

**Comment by Traesh** [comment]
Le portail n'est pas spawn en jeu, c'est donc un autre portail que vous avez vu, désolé pour vous
