### ISSUE TITLE
Minerai Légion

### ISSUE THREAD

**Issue by PandaChinois** [AshamaneProject/AshamaneCore#149]
- [ ] Ne donne aucun minerai ( aucune table de loot )

**Tellurium**
http://fr.wowhead.com/object=241726/gisement-de-tellurium
http://fr.wowhead.com/object=245324/riche-gisement-de-tellurium
http://fr.wowhead.com/object=253280/veine-de-tellurium

**Gangreschiste**
http://fr.wowhead.com/object=241743/gisement-de-gangreschiste
http://fr.wowhead.com/object=268901/pointe-de-gangreschiste
http://fr.wowhead.com/object=245325/riche-gisement-de-gangreschiste
http://fr.wowhead.com/object=255344/veine-de-gangreschiste

**Comment by PandaChinois** [comment]
Up:

Riche gisement de tellurium / veine de tellurium / gisement de gangreschiste / pointe de gangreschiste / riche gisement de gangreschiste / veine de gangreschiste ne donne toujours rien

**Comment by Neredun** [comment]
They have Entries in Gameobject_loot_template. But for some reason the nodes give you nothing (as far as i could see) at least in the server. Didn't test in local yet
