### ISSUE TITLE
Bug sort DH (DEUX SORT)

### ISSUE THREAD

**Issue by shaoshaoo** [AshamaneProject/AshamaneCore#157]
**Description:**

Les sorts ne sont pas appris automatiquement et reste griser dans les talents d'origine

**Usefull Wowhead links:**

http://fr.wowhead.com/spell=203720/pointes-demoniaques

http://fr.wowhead.com/spell=204021/marque-enflammee

**Comment by Traesh** [comment]
Ces sorts sont censés s'apprendre dans la 2eme zone de départ DH (Le caveau des gardiennes) qui n'est pas encore disponible, je vais les ajouter automatiquement sur les DH
