### ISSUE TITLE
Loot de stuff sur mobs ( zone Légion )

### ISSUE THREAD

**Issue by PandaChinois** [AshamaneProject/AshamaneCore#161]
Les mobs de Légion loot du stuff vert ( ilvl 680 ) le problème est qu'il doivent loot aussi du stuff bleu / violet avec un meilleur ilvl et avec des stats

Problème:
Ne donne pas de pièce de stuff bleu ou violet
Non aucune stat

Exemple:
http://fr.wowhead.com/npc=115666/garde-nid-scrutesang Donne les protèges bras ilvl 680 couleur verte sans stat alors qu'il devrait être 680 couleur verte AVEC stat

**Comment by Nexon99** [comment]
Les loots sont bien présent (rare et épique) mais le taux de chance de drop est proche de 0%. Concernant les stats manquant nous allons regarder ça sous peu.

**Comment by PandaChinois** [comment]
J'ai mal expliquer mais le loot que je vais dire "basique" est par exemple http://fr.wowhead.com/item=121063/protege-bras-en-os-dettin qui peut être obtenue en ilvl 780 ( vert ) 790 ( bleu) etc, plusieurs version de l'item mais avec ilvl différent
