### ISSUE TITLE
Character database is missing structure for table - character_archaeology_history

### ISSUE THREAD

**Issue by ImmortalusDev** [AshamaneProject/AshamaneCore#165]
Master branch

>> Auth database is up-to-date! Containing 1 new and 0 archived updates.
Updating Character database...
>> Applying update "2018_12_02_01_characters_archaeology.sql" 'B4522B1'...
Warning: Using a password on the command line interface can be insecure.

ERROR 1146 (42S02) at line 1: Table 'characters.character_archaeology_history' doesn't exist

**Comment by shamage** [comment]
try implementing this proof:

```sql
CREATE TABLE `character_archaeology_history` (
  `guid` bigint(20) unsigned NOT NULL DEFAULT '0',
  `time` smallint(5) unsigned NOT NULL DEFAULT '0',
  `projectId` int(10) unsigned NOT NULL DEFAULT '0',
  `count` smallint(5) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`,`projectId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
