### ISSUE TITLE
31429 Logging

### ISSUE THREAD

**Issue by Rokmusic45** [AshamaneProject/AshamaneCore#166]
Base ADB_820.00

rev.  ‎August ‎15, ‎2019, ‏‎12:27:54 AM

Config:
`###################################################################################################
# UPDATE SETTINGS
#
#    Updates.EnableDatabases
#        Description: A mask that describes which databases shall be updated.
#
#        Following flags are available
#           DATABASE_LOGIN     = 1, // Auth database
#           DATABASE_CHARACTER = 2, // Character database
#           DATABASE_WORLD     = 4, // World database
#           DATABASE_HOTFIX    = 8, // Hotfixes database
#
#        Default:     15 - (All enabled)
#                     4  - (Enable world only)
#                     0  - (All Disabled)

Updates.EnableDatabases = 15

#
#    Updates.AutoSetup
#        Description: Auto populate empty databases.
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

Updates.AutoSetup   = 1

#
#    Updates.Redundancy
#        Description: Perform data redundancy checks through hashing
#                     to detect changes on sql updates and reapply it.
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

Updates.Redundancy  = 1

#
#    Updates.ArchivedRedundancy
#        Description: Check hashes of archived updates (slows down startup).
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

Updates.ArchivedRedundancy = 0

#
#    Updates.AllowRehash
#        Description: Inserts the current file hash in the database if it is left empty.
#                     Useful if you want to mark a file as applied but you don't know its hash.
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

Updates.AllowRehash = 1

#
#    Updates.CleanDeadRefMaxCount
#        Description: Cleans dead/ orphaned references that occur if an update was removed or renamed and edited in one step.
#                     It only starts the clean up if the count of the missing updates is below or equal the Updates.CleanDeadRefMaxCount value.
#                     This way prevents erasing of the update history due to wrong source directory state (maybe wrong branch or bad revision).
#                     Disable this if you want to know if the database is in a possible "dirty state".
#        Default:     3 - (Enabled)
#                     0 - (Disabled)
#                    -1 - (Enabled - unlimited)

Updates.CleanDeadRefMaxCount = 3

#
###################################################################################################`

client: 8.2.0 31429
7 August.

![logging](https://user-images.githubusercontent.com/48260896/63191967-e0dfac00-c037-11e9-9ac9-1cd8d81f6f4a.jpg)

![logging2](https://user-images.githubusercontent.com/48260896/63191975-e4733300-c037-11e9-8574-8ed04e985038.jpg)

![logging3](https://user-images.githubusercontent.com/48260896/63191984-e76e2380-c037-11e9-972e-cfa2e5757831.jpg)

![logging4](https://user-images.githubusercontent.com/48260896/63191994-eb9a4100-c037-11e9-9a78-7cde3823589b.jpg)

WorldSocket::HandleAuthSession: Authentication failed for account: 1 ('1#1') address: 

**Win 10 X64 1903**

CMake 3.15.2
Boost  - C:\local\boost_1_69_0_b1_rc3
VS 2017

installed HERE SAME 31229. No problem

**Comment by Rokmusic45** [comment]
![realm](https://user-images.githubusercontent.com/48260896/63192483-336d9800-c039-11e9-8511-1391f99a4029.jpg)

**Comment by Rokmusic45** [comment]
`#
#    mmap.enablePathFinding
#        Description: Enable/Disable pathfinding using mmaps - recommended.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

mmap.enablePathFinding = 0

#
#    vmap.enableLOS
#    vmap.enableHeight
#        Description: VMmap support for line of sight and height calculation.
#        Default:     1 - (Enabled, vmap.enableLOS)
#                     1 - (Enabled, vmap.enableHeight)
#                     0 - (Disabled)

vmap.enableLOS    = 0
vmap.enableHeight = 0

#
#    vmap.enableIndoorCheck
#        Description: VMap based indoor check to remove outdoor-only auras (mounts etc.).
#        Default:     1 - (Enabled)
#                     0 - (Disabled, somewhat less CPU usage)

vmap.enableIndoorCheck = 0

#
#    DetectPosCollision
#        Description: Check final move position, summon position, etc for visible collision with
#                     other objects or walls (walls only if vmaps are enabled).
#        Default:     1 - (Enabled)
#                     0 - (Disabled, Less position precision but less CPU usage)

DetectPosCollision = 0
`

**Comment by destiny1500** [comment]
![fail flag](https://user-images.githubusercontent.com/21302048/63384162-9c893e80-c39e-11e9-8f54-e63345df6fe1.PNG)
Hello ,
In the data bass in the table realmlist change flag 2 by 0

this should solve the problem :)

**Comment by ReyDonovan** [comment]
you don’t even see the error, it is corrected with one query to the database in 10 seconds
