### ISSUE TITLE
ashamane.com Domain name expiration

### ISSUE THREAD

**Issue by Geekvcn** [AshamaneProject/AshamaneCore#167]
ashamane.com Domain name expiration
I can't access web page

**Comment by sergeyklay** [comment]
Right now ashamane.com website offers to install trojan

**Comment by benas80** [comment]
Is needed some connection patcher for the client ? 
Client can't connect to server (everytime Disconnected shows).
Fresh files, config from Trinity, 3.3.5 are working 8.2 not.
