### ISSUE TITLE
Quete : au secours de stellagosa 

### ISSUE THREAD

**Issue by Soyis** [AshamaneProject/AshamaneCore#173]
**Description:**
le mob ne loot pas la clé ducoup on peut pas faire la quete

**Usefull Wowhe ad links:**

**Comment by Astrozia** [comment]
moi j'ai loot la clef personnellement

**Comment by PandaChinois** [comment]
Quête http://fr.wowhead.com/quest=37450/au-secours-de-stellagosa

Mobs http://fr.wowhead.com/npc=86535/surveillant-lykill

**Comment by KrystenAsha** [comment]
Bug corrigé. Bon jeu sur Ashamane
