### ISSUE TITLE
Quête "[Les Bienfaits du pèlerin][La saison des fêtes][Le maître des traditions estivales][La directrice d'orphelinat costumée][Collecteurs du printemps][La fête des Brasseurs !]" Sansaint

### ISSUE THREAD

**Issue by Astrozia** [AshamaneProject/AshamaneCore#174]
Les quête de la sansaint sont disponible mais impossible de les rendre car les pnj pour rendre les quêtes ne sont pas la

**Comment by KrystenAsha** [comment]
Les PNJ apparaissent lors d'évènement particulier. Bon jeu sur Ashamane
