### ISSUE TITLE
Bug Quest "Incendicite Ore"

### ISSUE THREAD

**Issue by father0000** [AshamaneProject/AshamaneCore#178]
Ne prend pas l'element pour validé la quête 

**Usefull Wowhead links:**
http://www.wowhead.com/quest=25735/incendicite-ore

**Comment by father0000** [comment]
Pas sur que c'est un BUG  désolé pour le dérangement....je viens de m'apercevoir que je nai pas la pioche pour faire la quête... si je me souviens je l'avais jetée pour faire de la place dans mes sacs.

**Comment by KrystenAsha** [comment]
Pas de bug. Bon jeu sur Ashamane
