### ISSUE TITLE
Database update failed

### ISSUE THREAD

**Issue by sueastward** [AshamaneProject/AshamaneCore#179]
**Description:**

The database names are Ashamane_world and Ashamane_hotfixes when I populate the database.
After the fill is complete, the database cannot be found if the database is updated.
After deleting the database prefix Ashamane_, it can be updated.

**Current behaviour:**

The program exits when it is updated after the database is populated.

**Expected behaviour:**

Normally updated after the database is populated.

**Project(s): <-- Mandatory**

- [ ] Issue found playing in Live Ashamane Private Server.
- [x] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

TrinityCore rev. e84346c8a910  (master branch) (Win64, MinSizeRel, Static) 

**Database version**

ADB

**Operating system:** Win10 Pro

**Comment by benas80** [comment]
I have this problem with database if i start: worldserver.exe 
All files are fresh.

[1146] Table 'world.updates_include' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

And server crash.

**Comment by derkeshtai** [comment]
Download https://github.com/AshamaneProject/AshamaneCore/releases/tag/ADB_820.00

Unzip and edit **ADB_world_820.00.sql**  changing sentences (only 2 sentences, it may be necessary to install a large file editor program like EmEditor):

```
CREATE DATABASE /*!32312 IF NOT EXISTS*/`ashamane_world` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE 'ashamane_world`;
```

for

```
CREATE DATABASE /*!32312 IF NOT EXISTS*/`world` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `world`;
```

only swift "ashamane_world" for "world"

AND edit **ADB_hotfixes_820.00.sql** changing:

```
 CREATE DATABASE /*!32312 IF NOT EXISTS*/`ashamane_hotfixes` /*!40100 DEFAULT CHARACTER SET latin1 */;
 USE `ashamane_hotfixes`;
```

for

```
CREATE DATABASE /*!32312 IF NOT EXISTS*/`hotfixes` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `hotfixes`;
```

Save and put it next to bin worldserver

**Comment by Gosa1979** [comment]
[SQL] Query ADB_world_820.00 start
[ERR] 5 - Out of memory (Needed 3053336 bytes)
[ERR]
when i try to execute the sql
