### ISSUE TITLE
Undead starting zone: no initial quest

### ISSUE THREAD

**Issue by DrThum** [AshamaneProject/AshamaneCore#18]
**Description:**

The first quest is not offered as undead. Also, the buff that makes you lie on the ground (spell ID 73523) is cancellable with a right click (probably not intended).

**Current behaviour:**

The game tutorial tells me to right click the exclamation mark to get my first quest, except there is no exclamation mark in sight. Instead, there's an aggressive spider (NPC id 51107) next to me.

**Expected behaviour:**

There should be a quest giver next to me to allow me to get my first quest.

**Steps to reproduce the problem:**

1. Create an undead character
2. Watch or skip the intro cinematic

**Comment by Nexon99** [comment]
**Bug fixed.** ✔️
