### ISSUE TITLE
No defined handler for opcode [UNKNOWN OPCODE 0x354B (13643)] 

### ISSUE THREAD

**Issue by rwilkin** [AshamaneProject/AshamaneCore#182]
**Description:**

Constantly I am being disconnected from the server within minutes of joining.
The server log says:
`No defined handler for opcode [UNKNOWN OPCODE 0x354B (13643)] sent by [Player: Avalos GUID Full: 0x08000400000000000000000000000005 Type: Player Entry: 0 Low: 5, Account: 5]`

I think it is to do with getting the first quest. Maybe?

**Expected behaviour:**

I think it just shouldn't happen

**Project(s): <-- Mandatory**

- [x] Issue found playing in Live Ashamane Private Server.
- [ ] Issue found in a compiled master repo from Git.

**Operating system:** Windows 10

**Comment by ajrgaming** [comment]
I am getting the same error

No defined handler for opcode [UNKNOWN OPCODE 0x354B (13643)] sent by [Player: Pallyerin GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 3]

**Comment by sueastward** [comment]
I tested it in trinitycore.
Trinitycore will also issue a warning
This message occurs when the task interface with npc is closed.
Repeat the chat with npc and close the interface, it will trigger repeatedly, but will not disconnect.

**Comment by rwilkin** [comment]
> I tested it in trinitycore.
> Trinitycore will also issue a warning
> This message occurs when the task interface with npc is closed.
> Repeat the chat with npc and close the interface, it will trigger repeatedly, but will not disconnect.

It takes a little bit but it does disconnect. Once the error is thrown nothing in the world works properly until you reconnect

**Comment by osleyder85** [comment]
I tried TrinityCore, the same error appears but does not disconnect the client.

So:
No defined handler for opcode [UNKNOWN OPCODE 0x354B (13643)]

It is not the problem that causes the client to disconnect.

**Comment by osleyder85** [comment]
Here is what I have from opcode: 0x354B:

ClientToServer: 13643 (0x354B) Length: 4 ConnIdx: 0 Time: 03/29/2019 14:36:26.830 Number: 9618
|-------------------------------------------------|---------------------------------|
| 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F | 0 1 2 3 4 5 6 7 8 9 A B C D E F |
|-------------------------------------------------|---------------------------------|
| 29 62 00 00                                     | ) b . .                         |
|-------------------------------------------------|---------------------------------|

**Comment by buddyqc69** [comment]
i have the same issue, do you have a fix for this ?

**Comment by MaxtorCoder** [comment]
It is literally a missing opcode. It is harmless lmao.

**Comment by 0x384c0** [comment]
Maybe this information will be useful for anyone.
By randomly changing parameters in world.conf, I figured out, that setting these parameters to 1
```
Quests.IgnoreAutoAccept = 1
Quests.IgnoreAutoComplete = 1
```
solves client disconnection, when task interface with NPC is closed

**Comment by buddyqc69** [comment]
same error do you have fix for this?

**Comment by MaxtorCoder** [comment]
Bruh. I said earlier. It is an opcode sent by the client that is unknown to the server. It's harmless.

**Comment by buddyqc69** [comment]
yeah, but why that disconnect me after complete quest? we have good client..

**Comment by buddyqc69** [comment]
dont play with the gm account and check you mysql server performance, all is good for me
