### ISSUE TITLE
Azerite Power

### ISSUE THREAD

**Issue by MttAI-dev** [AshamaneProject/AshamaneCore#190]
Is there any fixes for azerite power? or any one can tell me how to update 8.0.1 DB in to 8.2? Azerite is realy need in 8.2 and its not working this is realy big problem. on 8.0.1 BFAcoreN was working possible to use that for fix?

**Comment by shamage** [comment]
Some fixes have already been solved and are also being solved at TC - you need to look for it for example here :   [Azerite ](https://github.com/TrinityCore/TrinityCore/blob/b0bf1275ee29858d34cfe951e46e8b4718386a13/src/server/game/Handlers/AzeriteHandler.cpp)

**Comment by ReyDonovan** [comment]
https://github.com/ReyDonovan/AshamaneCoreLegacy

update Ashamane bfa and legion
