### ISSUE TITLE
disconnecting

### ISSUE THREAD

**Issue by drustcore** [AshamaneProject/AshamaneCore#192]
i got instanlty disconnecting and its not crashing server

a streaming error has ocurred wow51900322

**Comment by DJBoxer** [comment]
your error is related to game client not AshamaneCore. 

Do you have full client? Or your client is corrupted.

**Comment by drustcore** [comment]
> your error is related to game client not AshamaneCore.
> 
> Do you have full client? Or your client is corrupted.

no but it can not opcoce?

**Comment by cooler-SAI** [comment]
damn! it's coz AutoAccept Quest! off it in conf for temp fix

**Comment by buddyqc69** [comment]
how to fix the disconnection ?
