### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by arcaniafr** [AshamaneProject/AshamaneCore#195]
Hi, the worldserver crash after connect. 
BDD updated...
core 8.2

**Comment by shamage** [comment]
what is your kernel version ? 

Edit :  Build version  ?

**Comment by arcaniafr** [comment]
Build 32750, the problem is in mail opcode... I've set to unhandled CMSG_QUERY_NEXT_MAIL_TIME, the core not crash before i try open the mail box...

**Comment by ReyDonovan** [comment]
)))))

**Comment by arcaniafr** [comment]
i think, it's in the GM mode

**Comment by ReyDonovan** [comment]
https://github.com/ReyDonovan/AshamaneCoreLegacy

update Ashamane bfa and legion
