### ISSUE TITLE
Download legion = 7.3.5.26972

### ISSUE THREAD

**Issue by V3nomAnc3r** [AshamaneProject/AshamaneCore#196]
Hey guys where i can download wow client 7.3.5.26972

**Comment by buddyqc69** [comment]
Check on another server, download the client and modify

**Comment by V3nomAnc3r** [comment]
i cant find 7.3.5.26972 ...:(

**Comment by buddyqc69** [comment]
Is not a chat here, if you need help talk on discord

**Comment by shamage** [comment]
> Nemôžem nájsť 7.3.5.26972 ... :(


maybe you can find what you're looking for here :  [DOWNLOAD WOW CLIENT](https://wowmortal.com/download.php#)
