### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by darkmoi31** [AshamaneProject/AshamaneCore#197]
**Description:**
how i can install database ? (sql) in order : base, ashamane update ?

i use branch legion

thanks in advance

CHANGEME Description of the problem or issue here. Wowhead link will be appreciated.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/). Do not post entire log here.

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Project(s): <-- Mandatory**

- [ ] Issue found playing in Live Ashamane Private Server.
- [ ] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

CHANGEME Mandatory if Project == compiled master repo from Git, found it in first line of Server.log

**Database version**

CHANGEME What DB do you use, TDB, ADB, other.

**Operating system:** CHANGEME OS

debian 9

**Comment by buddyqc69** [comment]
Check on trinitycore wiki

**Comment by ReyDonovan** [comment]
https://github.com/ReyDonovan/AshamaneCoreLegacy

update Ashamane bfa and legion
