### ISSUE TITLE
Unknown column 'value' in 'field list'

### ISSUE THREAD

**Issue by Hellfurian** [AshamaneProject/AshamaneCore#2]
**Description:**

Crash after loading worldserver. All updates have been applied (even Ashamane updates). 

**Current behaviour:**

Crash
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

**Steps to reproduce the problem:**

1. Initialize worldserver.
2. Check DBErrors & Server
3. ??

**Branch(es):**

Master

**TC rev. hash/commit:** 

TrinityCore rev. 09fdd32f9834 2017-11-03 10:49:04 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** Windows 10 

Server log ends here: 
Loading Quests...
Table `quest_objectives` has objective for quest 30238 but such quest does not exist

DBErrors log ends here:
[1054] Unknown column 'value' in 'field list'
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

**Comment by Traesh** [comment]
Can you provide the 5 last line of DBErrors ?

**Comment by Hellfurian** [comment]
@Traesh

Spell (id: 247936) have SPELL_EFFECT_QUEST_COMPLETE for quest 47956, but quest not have flag QUEST_SPECIAL_FLAGS_EXPLORATION_OR_EVENT. Quest flags must be fixed, quest modified to enable objective.
Spell (id: 248435) have SPELL_EFFECT_QUEST_COMPLETE for quest 48030, but quest not have flag QUEST_SPECIAL_FLAGS_EXPLORATION_OR_EVENT. Quest flags must be fixed, quest modified to enable objective.
Spell (id: 248448) have SPELL_EFFECT_QUEST_COMPLETE for quest 48031, but quest not have flag QUEST_SPECIAL_FLAGS_EXPLORATION_OR_EVENT. Quest flags must be fixed, quest modified to enable objective.
Spell (id: 248449) have SPELL_EFFECT_QUEST_COMPLETE for quest 48032, but quest not have flag QUEST_SPECIAL_FLAGS_EXPLORATION_OR_EVENT. Quest flags must be fixed, quest modified to enable objective.
Spell (id: 248450) have SPELL_EFFECT_QUEST_COMPLETE for quest 48033, but quest not have flag QUEST_SPECIAL_FLAGS_EXPLORATION_OR_EVENT. Quest flags must be fixed, quest modified to enable objective.
[1054] Unknown column 'value' in 'field list'
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

**Comment by Traesh** [comment]
Do you use the ADB ? https://github.com/AshamaneProject/AshamaneCore/releases/tag/ADB725.01

If not, you may have an issue with the world_quest table

Here is this table full table : 
https://puu.sh/yga9p/ba23fd22c8.txt

**Comment by Hellfurian** [comment]
@Traesh

I have used the Ashamane DB :( But maybe I can try again. Should I apply that after or before the rest of the updates?

Currently receiving;

[1146] Table 'world.areatrigger' doesn't exist

So I'm assuming I'm missing a lot here. What you uploaded worked though, for world quests!

**Comment by Hellfurian** [comment]
@Traesh

I figured it out. (: Thank you! I've been at this for a couple days now, I knew it was a really stupid error/issue and I just needed a push in the right direction to get it working correctly. 

Again, thank you. This can be closed now ^_^ *solved*

**Comment by Traesh** [comment]
My pleasure :)

**Comment by Hellfurian** [comment]
@Traesh

Is there a way to contact you somewhere else? I've got questions, didn't want to blow up the Issues section here though.

**Comment by Traesh** [comment]
You can contact me on Discord : Traesh#1375

**Comment by Hellfurian** [comment]
@Traesh

Thank you! (: Whenever you're free.
