### ISSUE TITLE
Player name Unknown

### ISSUE THREAD

**Issue by arcaniafr** [AshamaneProject/AshamaneCore#200]
<img width="451" alt="Capture" src="https://user-images.githubusercontent.com/56791020/78153813-c37f1700-743b-11ea-92f0-d9400e3b5953.PNG">
hi,
I have the legion core 7.3.5 the professions not open and the player name is unknown...

how fix it ?

Thanks

**Comment by Traesh** [comment]
Check that you don't have a character with guid 0 in your database

**Comment by arcaniafr** [comment]
I have 1,2,3 in character db guid.... you are french traesh no?

**Comment by Faq** [comment]
provide .pinfo

**Comment by arcaniafr** [comment]
resolved

**Comment by slash-design** [comment]
how did you fix the problem?
