### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by NiganNi** [AshamaneProject/AshamaneCore#201]
-----------------------------------------------------
![111](https://user-images.githubusercontent.com/61392055/78457695-c6d10780-76b4-11ea-9b01-29f70a740091.jpg)

CMake Warning (dev) at dep/boost/CMakeLists.txt:48 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Boost_ROOT is set to:

    C:\local\boost_1_66_0

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/macros/FindBoost.cmake:251 (cmake_policy):
  Policy "CMP0102" is not known to this version of CMake.
Call Stack (most recent call first):
  dep/boost/CMakeLists.txt:48 (find_package)

-----------------------------------------------------

**Comment by Traesh** [comment]
Try to update your cmake version

**Comment by NiganNi** [comment]
Traesh thanks for the help!
