### ISSUE TITLE
La mort vient de l'oeil (quête zone DK )

### ISSUE THREAD

**Issue by Pouloss** [AshamaneProject/AshamaneCore#203]
Bonjour ,

La quête " La mort vient de l'oeil " est une quête à la zone des DK , qu'on prend après la quête des prisonniers chez le roi liche:
https://www.noelshack.com/2017-50-5-1513351083-wowscrnshot-121517-161523.jpg

Quand on prend l'oeil , on voit aucun sort dans la barre d'action , donc on ne peut pas faire le sort en face des bâtiments:
https://www.noelshack.com/2017-50-5-1513351282-wowscrnshot-121517-161544.jpg

Et quand on s'approche d'un bâtiment sa fait rien j'ai tout de même essayer au cas ou si sa ce valider tout seul. On peut pas faire la quête c'est dommage .

Merci
Cordialement Pouloss

**Comment by Traesh** [comment]
Fixed by c20ad8672ee12464375afb89df27dd7faeaff104
