### ISSUE TITLE
scriptmgr.cpp crash now when starting server

### ISSUE THREAD

**Issue by firelook** [AshamaneProject/AshamaneCore#204]
**Description:**

Script named 'npc_quest_107242' does not have a script name assigned in database.
Script named 'npc_quest_107241' does not have a script name assigned in database.
Script named 'npc_quest_107243' does not have a script name assigned in database.
Script 'merayl_q42159' already assigned with the same script name, so the script can't work.

D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\game\Scripting\ScriptMgr.cpp:956 in SpecializedScriptRegistry<class CreatureScript,1>::AddScript ABORTED.

**Project(s): <-- Mandatory**

- [X ] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

TrinityCore rev. 2bd554e23db6+ 2020-04-06 03:47:51 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

**Database version**

DB : MySQL

**Operating system:** Windows 10

**Comment by dio85** [comment]
zone_azshuna.cpp// new merayl_q42159("merayl_q42159"); this 2x in the zone script. just delete the latest.

**Comment by firelook** [comment]
would you mind to be more explicit please: is it in the db ? which table ?

**Comment by dio85** [comment]
what? if you ask me, in the core. scripts/

**Comment by firelook** [comment]
I take a look but it is above my head, too complicated

**Comment by firelook** [comment]
I have removed     new merayl_q42159("merayl_q42159"); on line 1899 for zone_azshuna.cpp and it worked => seems a small bug
