### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by firelook** [AshamaneProject/AshamaneCore#206]
**Description:**
doesn't compile with version as of Commits on Apr 14, 2020

`
ÉCHEC de la build.

"D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\AshamaneCore.sln" (cible par défaut) (1) ->
"D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\ALL_BUILD.vcxproj.metaproj" (cible par défaut) (2) ->
"D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\game\game.vcxproj.metaproj" (cible par défaut) (42) ->
"D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\game\game.vcxproj" (cible par défaut) (43) ->
(ClCompile cible) -> 
  D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\game\Spells\SpellEffects.cpp(5505,36): error C2065: 'SUMMON_TYPE_UNK17': undeclared identifier [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\game\game.vcxproj]
`

**Project(s): <-- Mandatory**

- [x] Issue found playing in Live Ashamane Private Server.
- [ x] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

CHANGEME Mandatory if Project == compiled master repo from Git, found it in first line of Server.log

**Database version**

mysql

**Operating system:** CHANGEME OS

windows 10

**Comment by ReyDonovan** [comment]
```
        -if (properties->Control != SUMMON_TYPE_UNK17)
        +if (SummonTitle(properties->Control) != SummonTitle::Spirit)
```

**Comment by firelook** [comment]
you are right !
it is working now !!!
thanks a lot

**Comment by firelook** [comment]
solved / integrated in latest commit
