### ISSUE TITLE
New Install - DB errors with worldserver start

### ISSUE THREAD

**Issue by mcsescott** [AshamaneProject/AshamaneCore#211]
**Description:**

New server install - DB errors

**Current behaviour:**

Downloaded latest commit, created new install.  No errors in CMake or VS2019 build.  Several DB errors upon starting worldserver. See attachment from server log.

**Expected behaviour:**
I was hoping it would start clean, but several errors popped up.

**Project:** 
- [x] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 
TrinityCore rev. 7f7c43bc5b3f 2020-04-19 19:36:31 +0200 (master branch) (Win32, RelWithDebInfo, Static) (worldserver-daemon)

**Database version**

Used ADB 820.00

**Operating system:** 
Windows 10

[Server.log](https://github.com/AshamaneProject/AshamaneCore/files/4506990/Server.log)

**Comment by mcsescott** [comment]
Was hopeful the latest commit from @Daniel25 changes would have gotten rid of the errors...  Did I miss a step somewhere?

**Comment by Traesh** [comment]
Daniel25 commit was made to fix the main errors preventing Ashamane from starting, it didn't fix all DB errors which are sadly inevitable when you include a lot of sniffed data in a short amount of time

Fixing all DB errors will probably require multiple commits

**Comment by mcsescott** [comment]
OK, I'll sludge through it.  Thanks for the reply.
