### ISSUE TITLE
DK starting issues

### ISSUE THREAD

**Issue by mcsescott** [AshamaneProject/AshamaneCore#213]
**Description:**

DK starting issues - gear and 2nd quest

**Current behavior:**

When starting a new DK, charcters has no clothes (except a hat). In addition, cannot complete the second quest #12842 because there is no "Runeforging" ability in the spellbook.

**Expected behavior:**

DK should have a beginning set of gear, and be able to complete the second quest.

----------

**Project:**

- [x]  Issue found in a compiled master repo from Git.

**TC rev. hash/commit:**

TrinityCore rev. 7f7c43b 2020-04-19 19:36:31 +0200 (master branch) (Win32, RelWithDebInfo, Static) (worldserver-daemon)

**Database version:** Used ADB 820.00

**Operating system:** Windows 10

**Comment by Traesh** [comment]
Clothes issue fixed with e4029772508a4b6d4546da70f4205670c3539808

**Comment by Traesh** [comment]
The quest 12842 is completable, you don't need the runeforging ability you have to take a sword on the ground and use it

The problem here is a global issue with gameobject not starting sparkling as soon as you take a quest, but you can use them after a disconnect/reconnect. The info was passed to Shauren from TC and he will look into it

**Comment by mcsescott** [comment]
I believe your comment is referring to quest 12619, which *is* able to be completed.  That is the quest that requires you to pick up a sword and use it at the Runeforge.

I will compile today with the latest commit, but the quest in question is 12842, and requires you to use the Runeforging ability in your spellbook.  When looking at the spellbook, there is no Runeforging available.  

I will recompile today and post screenshot if applicable.  Thank you.

**Comment by Traesh** [comment]
12619 is doable too now, thanks to Shauren

**Comment by mcsescott** [comment]
Confirmed both issues are working.  Thank you.
