### ISSUE TITLE
New build - ../characters/2020_04_20_00_characters.sql error

### ISSUE THREAD

**Issue by mcsescott** [AshamaneProject/AshamaneCore#216]
**Description:**

Built fresh, new server with latest commit.  Database error.

**Current behavior:**

When starting worldserver, it builds the database and fails at the following...

2020_04_20_00_characters.sql

Error Code: 1060. Duplicate column name 'auctionHouseId'

I also attached the server log.

**Expected behavior:**

worldserver should run

**Project(s): <-- Mandatory**

- [ ] Issue found playing in Live Ashamane Private Server.
- [x] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

TrinityCore rev. 63eb69a9a04a 2020-04-23 22:04:45 +0200 (master branch) (Win32, RelWithDebInfo, Static)

-- attached server log --

**Database version**

ADB 8.20.00

**Operating system:** 
Windows 10

[Server.log](https://github.com/AshamaneProject/AshamaneCore/files/4526055/Server.log)

**Comment by mcsescott** [comment]
Need to reopen this issue ...  new build/new dbs/new compile... same error.

Server .log attached.

[Server.log](https://github.com/AshamaneProject/AshamaneCore/files/4531890/Server.log)

**Comment by sueastward** [comment]
Interim solution:
1. Delete AshamaneCore \ sql \ ashamane \ characters \ 2020_04_20_00_characters.sql
2. Restart, it should exit after waiting for a while
3. Use heidisql to delete the world and hotfixes, these two db would be empty
modify ashamane_world to world, ashamane_hotfixes to hotfixes
Reference #179
4. Restart

You may encounter this problem https://github.com/AshamaneProject/AshamaneCore/issues/182#issuecomment-541321624

**Comment by mcsescott** [comment]
@sueastward Thank you for that, but I am not going to change the names of my database schemas ... that is why we put the names in worldserver.conf. 

I am currently running TriniryCore and Ashamane on the same machine (not at the same time) and thus two different databases/dB users, etc. 

If these updates reference the default tables (world, hotfixes, auth, characters) then I believe that would be a coding issue or SQL issue, as it should be referencing the dB names defined in worldserver.conf. 

Make sense, or am I totally wrong (which wouldn’t be the first time...). 

Thanks...

**Comment by Traesh** [comment]
My bad @mcsescott, could you try again with last commit ?

**Comment by mcsescott** [comment]
I can confirm this now works with the latest commit.  Thank you!
