### ISSUE TITLE
Quête "[Le paquetage de la compagnie Bravo : le camouflage]" Les carmines

### ISSUE THREAD

**Issue by Astrozia** [AshamaneProject/AshamaneCore#216]
quête faisable mais il n'y a vraiment pas assez de tas de feuilles, il y en a 4 et il en faut 5 donc il faut attendre le respawn
http://fr.wowhead.com/quest=26636/le-paquetage-de-la-compagnie-bravo-le-camouflage

**Comment by KrystenAsha** [comment]
Bug corrigé. Bon jeu sur Ashamane.
