### ISSUE TITLE
Grady Bannson (chat tigré roux )

### ISSUE THREAD

**Issue by Pouloss** [AshamaneProject/AshamaneCore#22]
Bonjour ,

J'ai acheter le "chat tigré roux " , mais le problème c'est que y a rien dans ma liste de mascottes .
Preuve que je les acheter :
https://www.noelshack.com/2017-48-7-1512305926-wowscrnshot-120317-135458.jpg

Preuve qu'il y a rien :
https://www.noelshack.com/2017-48-7-1512306175-wowscrnshot-120317-140101.jpg

Toujours 0 mascottes c'est écrie , et c'est bien grisé l'icone du chat .

Merci
Cordialement Pouloss

**Comment by Traesh** [comment]
Corrigé par 23a66baab181b9b1c15be7fa89e881cc0b793a6f
