### ISSUE TITLE
Multiple errors in server log ... server starts and runs, but errors listed

### ISSUE THREAD

**Issue by mcsescott** [AshamaneProject/AshamaneCore#221]
**Description:**

Built new server with latest commit.  First time server log is attached.  Issues listed below...

**Current behavior:**

Log located here:  [Server starting log.log](https://github.com/AshamaneProject/AshamaneCore/files/4534397/Server.starting.log.log)

1. Line 30 you can see I applied  ADB 820.00, but server says on line 606 I am using ADB 735.00

2. Line 617 - `Missing name Azerite.Knowledge.Level in config file C:/Trinity/RunAsh/worldserver.conf, add "Azerite.Knowledge.Level = 1" to this file`    
--This line is not in TC worldserver.conf.dist either, but it looks like the server is expecting it

3. Lines 653-661 - InstanceSaveManager errors

4. Lines 768 - 960 ... various quest related errors

5. Lines 1269-1706 ... various spell related errors

6. Starting at line 1948, getting VMAP error regarding Kalimdor  (I did use the Ashamane extractors using the latest 33941 client)

**Expected behavior:**

I would hope there would not be many errors.

**Project(s): <-- Mandatory**

- [ ] Issue found playing in Live Ashamane Private Server.
- [x] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

TrinityCore rev. ef978be16603 2020-04-25 17:57:35 +0200 (master branch) (Win32, RelWithDebInfo, Static)

**Database version**

ADB 8.20.00

**Operating system:**
Windows 10

**Comment by Thordekk** [comment]
All servers have db errors, u can make db fixes and then make pull request to contribute
