### ISSUE TITLE
Mobs bugué Strengleronce ceptentorial

### ISSUE THREAD

**Issue by Astrozia** [AshamaneProject/AshamaneCore#227]
il y a des serpent-razzashi a expédition de nésingwary avec une tete de mort a la place de leurs niveau et qui two-shot
http://zupimages.net/viewer.php?id=17/50/4zpy.png
http://fr.wowhead.com/npc=52173/serpent-razzashi

**Comment by Traesh** [comment]
Corrigé au prochain reboot
