### ISSUE TITLE
Orc Starting area - disconnects and mottled boars

### ISSUE THREAD

**Issue by mcsescott** [AshamaneProject/AshamaneCore#232]
**Description:**

Orc starting area is unplayable

1. Mottled Boars are nowhere to be found
2. Constant disconnects from the server

**Current behavior:**

After creating an orc and accepting the first quest, the Mottled Boars (quest #25126) are not available.   In addition, you get constantly disconnected from the server.
https://www.wowhead.com/quest=25126/cutting-teeth

**Expected behavior:**

Boars should be available to complete quest, no disconnects from the server.

----------
**Project(s): <-- Mandatory**
- [ ] Issue found playing in Live Ashamane Private Server.
- [x] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 
AshamaneCore, revision 5467ef4 2020-05-09 09:39:22 -0500 (master branch) (Win32, RelWithDebInfo, Static)

**Database version**
ADB 820.00

**Operating system:**
Windows 10

**Comment by wokaoak** [comment]
hi friend
what's your version of the boost?

**Comment by mcsescott** [comment]
@wokaoak I am currently using 1.66

**Comment by wokaoak** [comment]
think you ，so
the Visual Studio version is 2017 or 2019 ？
and mysql version

**Comment by mcsescott** [comment]
I am also compiling TrinityCore. 

I am using MySQL 5.7 and VS 2019.   I had issues with 64-bit, so am now compiling 32-bit for both TC and Ashamane.

**Comment by Thordekk** [comment]
U need to put in cmake x64 then compile in vs release or debug 64-bit

**Comment by mcsescott** [comment]
Thank you for the suggestion of compiling 64-bit.  Closing this issue and will open new one, so as not to confuse the two...

I compiled in 64 bit and the boars showed up.  Still getting disconnects from the server.  Opened #240 for that issue.
