### ISSUE TITLE
Quête "[Au service de Son Altesse Royale, la princesse Poobah]" Cap de strangleronce

### ISSUE THREAD

**Issue by Astrozia** [AshamaneProject/AshamaneCore#233]
pas de traqueur jaguero 
http://fr.wowhead.com/npc=2522/traqueur-jaguero
http://fr.wowhead.com/quest=26604/au-service-de-son-altesse-royale-la-princesse-poobah

**Comment by KrystenAsha** [comment]
Bug Corrigé. Bon jeu sur Ashamane
