### ISSUE TITLE
PvP and azerite pover cant be set.

### ISSUE THREAD

**Issue by MttAI-dev** [AshamaneProject/AshamaneCore#237]
**Description:**
Cant be saved in game.

**Current behaviour:**

Shen selecting azerite pover or pvp talent it works till relog the game, after relog you need set them again.

**Expected behaviour:**

PvP talents should save when selecting and do not reset after relog.
Azerite Power should save when selecting and do not reset after relog.

**Project(s): <-- Mandatory**

- [+] Issue found playing in Live Ashamane Private Server.
- [+] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

Mandatory if Project == compiled master repo from Git, found it in first line of Server.log

**Database version**
ADB.

**Operating system:** Win 7 OS

**Comment by Thordekk** [comment]
and second talent cant be selected, same issue as trinity core

**Comment by AzgathCore** [comment]
It's the equipment that bugs because if you take another equipment all the azerite features will be set correctly.

**Comment by DuelistRag3** [comment]
@AzgathCore is it just the first you get from the quest?

**Comment by AzgathCore** [comment]
Yes because I've tried a lot of equipment and the azerite strokes work well.

**Comment by AzgathCore** [comment]
Same to activate the war mode outside the capitals, you must close the talent menu before exiting. When I log out and log back in I always have my PVP talents and talents activated. There are some PVP spells that don't work well.

**Comment by MttAI-dev** [comment]
have tested and nop its not working at all
