### ISSUE TITLE
Visual Studio compile error

### ISSUE THREAD

**Issue by mcsescott** [AshamaneProject/AshamaneCore#238]
**Description:**

Error when comping in VS Studio

**Current behavior:**

Error when compiling worldserver

Upgraded to latest CMake, Boost 1_72, 64 bit MySQL ... 

Selected x64 in CMake, VS 2019 selected RelDebwithInfo, 64 bit.
Clean solution was successful.

Only failed on worldserver.  Error attached.

[Compile Error.txt](https://github.com/AshamaneProject/AshamaneCore/files/4619209/Compile.Error.txt)

_Edit ... I can compile TrinityCore successfully with the same settings._

**Expected behavior:**

Be able to compile successfully.

----------
**Project(s): <-- Mandatory**
- [ ] Issue found playing in Live Ashamane Private Server.
- [x] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 
AshamaneCore, revision 5467ef4 

**Database version**
ADB 820.00

**Operating system:**
Windows 10

**Comment by DuelistRag3** [comment]
Try boost 1_66 i always use 66, works fine for me

**Comment by ImmortalusDev** [comment]
You need to use older boost. 1.66 will work, close this.

**Comment by mcsescott** [comment]
Thanks for the suggestion. I switched to boost 1.66 and changed the environment variables, and deleted the CMake cache.  I get CMake errors now ... attached is the output from CMake program, as well as the two other logs.  Much appreciation for the help.

As stated before, I was able to compile 32-bit before, and now that I have switched to 64-bit I get errors.

[CMake Program output.txt](https://github.com/AshamaneProject/AshamaneCore/files/4624288/CMake.Program.output.txt)
[CMakeError.log](https://github.com/AshamaneProject/AshamaneCore/files/4624289/CMakeError.log)
[CMakeOutput.log](https://github.com/AshamaneProject/AshamaneCore/files/4624290/CMakeOutput.log)

**Comment by ImmortalusDev** [comment]
But it's not related to this source code.

**Comment by mcsescott** [comment]
Thank you for the comment, @ImmortalusDev.  I understand it may not be the source code...  Is Ashamane updated for VS2019, or does it still need VS2017?  That could be the issue...  

Again, I was able to compile 32-bit on Boost 1.66, VS2019, but I have now switched to Boost 1.72 and 64-bit MYSQL, so that I can compile a 64-bit server.  I did try Boost 1.66, as shown in the logs above.

I can switch back to 32-bit and try to recompile, but was just trying to solve disconnection problems as stated in issue #232 .

**Comment by mcsescott** [comment]
Thank you for all the comments and suggestions.  I figured out my problem ... when I went back to Boost 1.66, I was still using my 32-bit version.  So, I downloaded Boost 1.66 64-bit, installed, and was able to compile successfully.

Thanks again.
