### ISSUE TITLE
Verdict du templier ( bug sort paladin )

### ISSUE THREAD

**Issue by Pouloss** [AshamaneProject/AshamaneCore#24]
Bonjour ,

Le sort " Verdict du templier " qui est un sort de la classe Paladin fait aucun dégâts , le sort rate toujours sa cible .

https://www.noelshack.com/2017-49-1-1512392792-wowscrnshot-120417-140108.jpg

C'est pas très pratique pour tuer des monstres

Merci
Cordialement Pouloss

**Comment by Traesh** [comment]
Fixed with 34a681c6bc348ed4ee866ef66f4aa89fd2d352aa

**Comment by Pouloss** [comment]
Quand c'est dans " closed " , sa veut dire que se sera résolu au prochain patch de debug je suppose

**Comment by Traesh** [comment]
C'est c'est "closed" c'est que la correction est faites, il faudra juste un reboot du serveur pour l'appliquer :)

**Comment by Pouloss** [comment]
Quand c'est " Vous vous êtes tromper je pense .

D'accord merci pour l'information . J'espère que se sera pour bientôt .
