### ISSUE TITLE
Rapport de bug : Foret d'Elwyn

### ISSUE THREAD

**Issue by Astrozia** [AshamaneProject/AshamaneCore#244]
Quêtes:
- [x] [The Jasperlode Mine] : http://fr.wowhead.com/quest=76/la-mine-veine-de-jaspe (je suis allez dans toute la mine partout et ca ne valide pas la quête)

Mobs:

**Comment by KrystenAsha** [comment]
Bug corrigé. Bon jeu sur Ashamane
