### ISSUE TITLE
issue with updating world 

### ISSUE THREAD

**Issue by Hooaah** [AshamaneProject/AshamaneCore#245]
D:/Ashamane/sql/ashamane/world/2018_11_11_01_world.sql' to database 'ashamane_world' failed!
this the error i get when populating world server

Using ADB_820.00

**Comment by mcsescott** [comment]
@Hooaah   Where is the rest of the issue template?

Is this when starting the server new?  Did you change the value of the max allowed packets?

**Comment by Hooaah** [comment]
yeah new server setup.
AshamaneCore, revision 5467ef4dd91e 2020-05-09 05:10:38 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

               _                                      
     /\       | |                                     
    /  \   ___| |__   __ _ _ __ ___   __ _ _ __   ___ 
   / /\ \ / __| '_ \ / _` | '_ ` _ \ / _` | '_ \ / _ \
  / ____ \\__ \ | | | (_| | | | | | | (_| | | | |  __/
 /_/    \_\___/_| |_|\__,_|_| |_| |_|\__,_|_| |_|\___|

          The Ashamane Project - Ashamane Core
 
 
Based on TrinityCore, with credit to their team and contributions.
http://TrinityCore.org
 
 
Using configuration file D:/BFA/Core/worldserver.conf.
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.66.0
Updating Auth database...
>> Auth database is up-to-date! Containing 7 new and 0 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 24 new and 0 archived updates.
Updating World database...
>> Applying update "2018_11_11_01_world.sql" 'A7C7155'...
mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 1060 (42S21) at line 1: Duplicate column name 'AIAnimKitID'


Applying of file 'D:/Ashamane/sql/ashamane/world/2018_11_11_01_world.sql' to database 'ashamane_world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.

**Comment by Hooaah** [comment]
Also packet set to 1000

**Comment by DuelistRag3** [comment]
what is your wait_timeout value?

**Comment by Hooaah** [comment]
not finding wait_timeout value

**Comment by DuelistRag3** [comment]
which software do you use?

**Comment by Daniel25** [comment]
It isn't a packets issue.
ERROR 1060 (42S21) at line 1: Duplicate column name 'AIAnimKitID'

 This file is the issue 2018_11_11_01_world.sq but your problem is that you aren't using a clear db in the start or it got corrupted.
Drop the world database and allow the worldserver.exe popule it since 0.

**Comment by DuelistRag3** [comment]
@Daniel25 this will help for sure, but i think the problem is also that his wait_timeout value is to low and it will disconect him, so his database will be corrupted again.

**Comment by Daniel25** [comment]
> @Daniel25 this will help for sure, but i think the problem is also that his wait_timeout value is to low and it will disconect him, so his database will be corrupted again.

 This is the update which gives the error,if you still think that its a issue with wait_timeout....ok
https://github.com/AshamaneProject/AshamaneCore/blob/master/sql/ashamane/world/2018_11_11_01_world.sql

**Comment by DuelistRag3** [comment]
Yes, I still think it is, because I don't have this problem

**Comment by mcsescott** [comment]
I agree with @Daniel25 .  If this is a new server, then the world and hotfix DBs should be empty, which possibly could be where the problem lies.  You can see from the log above that the databases are being updated, not created.

So, @Hooaah - drop your world and hotfix databases, and try it again.

In addition, the my.ini file in Windows doesn't have the wait_timeout parameter, but you can edit / change it using this web page as a guide:    https://medium.com/@dilsimchandrasena/changing-mysql-wait-timeout-variable-f16ebed1efce

**Comment by Hooaah** [comment]
I did everything you suggested, but still getting error.
Attempted several times and still no success.
So i deleted all software associated with build.
re-downloaded all software  and source.
Finally success, still not sure of the issue, but server working now.

**Comment by Hooaah** [comment]
Thanks for the help guys

**Comment by DuelistRag3** [comment]
> In addition, the my.ini file in Windows doesn't have the wait_timeout parameter, but you can edit / change it using this web page as a guide: https://medium.com/@dilsimchandrasena/changing-mysql-wait-timeout-variable-f16ebed1efce

you could also just add the wait_timeout value to the my.ini in windows
