### ISSUE TITLE
Applying commits from Trinity

### ISSUE THREAD

**Issue by firelook** [AshamaneProject/AshamaneCore#248]
This will help  us to use the latest client ....  ;)

**Comment by DuelistRag3** [comment]
I only made the changes for the build for now, but i can´t say when trash looks into the reposetory again

**Comment by Dokman** [comment]
@DuelistRag3 in my windows with boost 1.72 it doesn't compile

**Comment by DuelistRag3** [comment]
@Dokman Use boost 1_66 highly recomend it

**Comment by Dokman** [comment]
thanks <3

**Comment by DuelistRag3** [comment]
no proble, your welcome

**Comment by firelook** [comment]
any updates , it will be good ;)

**Comment by DuelistRag3** [comment]
@firelook we have to wait till traesh works again on the core, sadly i don´t know how to contact him

**Comment by Traesh** [comment]
TC and Ashamane are sync now :)
