### ISSUE TITLE
Boss trop puissant

### ISSUE THREAD

**Issue by father0000** [AshamaneProject/AshamaneCore#25]
Tous les boss "marqué entouré de gris comme sur la photo" sont beaucoup trop puissant. Je charge et je meurt a chaque fois... même ceux qui étaient 4 a 5 niveau plus bas.

![2017-12-04_151743](https://user-images.githubusercontent.com/34193536/33557419-7a13b188-d907-11e7-9e41-bf6d92daf7c4.png)

**Comment by Traesh** [comment]
Est-ce que ça pourrait être à cause de la goule juste à coté ? C'est un mob 54 (qui n'a rien à faire là, il était dans l'ancienne version des maleterres)

**Comment by father0000** [comment]
Non le boss ont le voie pas sur la photo il est complétement a gauche .. la goule est venue après  pendant que je faisait le screenshot.

**Comment by Nexon99** [comment]
@father0000 Merci pour le report, il semblerais que ces dégâts soit trop élevé, je vais corriger ça. De plus, ce mob rare n'est-il pas censé être(http://fr.wowhead.com/npc=1850/putridius) dans Scholomance (accès libre) ?
