### ISSUE TITLE
Export Commands

### ISSUE THREAD

**Issue by DuelistRag3** [AshamaneProject/AshamaneCore#252]
**Description:**

Can someone explain me how exactly the export commands work, i´m to stupid to find out myself :D

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/). Do not post entire log here.

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Project(s): <-- Mandatory**

- [ ] Issue found playing in Live Ashamane Private Server.
- [ ] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

CHANGEME Mandatory if Project == compiled master repo from Git, found it in first line of Server.log

**Database version**

CHANGEME What DB do you use, TDB, ADB, other.

**Operating system:** CHANGEME OS

**Comment by mcsescott** [comment]
Which export commands are you referring to?

**Comment by DuelistRag3** [comment]
[This](https://github.com/AshamaneProject/AshamaneCore/blob/5467ef4dd91e01b3fce7218a420f698a4e3d94d3/src/server/scripts/Commands/cs_export.cpp)

**Comment by mcsescott** [comment]
I looked at the code, and it doesn't appear to be in TrinityCore.  Not sure exactly what it does, but many of the comments are in Spanish.

**Comment by DuelistRag3** [comment]
ya i know, i looked into it also, but i don´t quiet unterstand, how to trigger the commands, .export appears to not work, i unterstand what you can do with them and its very usefull, but i can´t trigger them :)

**Comment by DuelistRag3** [comment]
Got it, the export cpp does not getting registered by the command script loader

**Comment by mcsescott** [comment]
Great; glad to see some development.

**Comment by DuelistRag3** [comment]
i will add a pr, that adds it to command script loader soon
