### ISSUE TITLE
Need help with this error

### ISSUE THREAD

**Issue by Hooaah** [AshamaneProject/AshamaneCore#254]
In mysql_stmt_prepare() id: 35, sql: "SELECT ID, RequiredLevel, AzeritePowerID, Type, AutoUnlock FROM azerite_item_milestone_power ORDER BY ID DESC"
Unknown column 'Type' in 'field list'

after rebooting my server, received this message starting world server.

**Comment by MttAI-dev** [comment]
u need update world DB there is missing or added new Colunm abd u need alter it
