### ISSUE TITLE
Mob élite Léthon en 3x ( Hinterlands)

### ISSUE THREAD

**Issue by Pouloss** [AshamaneProject/AshamaneCore#257]
Bonsoir ,

Dans les "Hinterlands" on trouve un mob élite nommer " Léthon " en triple:
https://www.noelshack.com/2017-51-2-1513718937-wowscrnshot-121917-221904.jpg

On voit bien que y a 3 têtes , on trouve Léthon ici:
https://www.noelshack.com/2017-51-2-1513719250-wowscrnshot-121917-221908.jpg

Et moi comme je suis un nain fou , j'ai bien sur essayer de me les faire , mais manque de chance:
https://www.noelshack.com/2017-51-2-1513719395-wowscrnshot-121917-222025.jpg

Je me suis fais oneshot 

Merci
Cordialement Pouloss

**Comment by Traesh** [comment]
C'est corrigé :)

**Comment by Pouloss** [comment]
Ben dis donc , c'est rapide ! j'irais voir ça .. Pour me venger !
