### ISSUE TITLE
Error while importing Database

### ISSUE THREAD

**Issue by AsoraXDev** [AshamaneProject/AshamaneCore#259]
**Description:**
These Errors happens on the first start while importing the SQL Databases for (auth,.... try to fix for myself, checking more)
https://pastebin.com/tUhUef8x

**TC rev. hash/commit:** 
AshamaneCore, revision 45c04a4757c6 2020-08-18 00:04:14 +0200 (master branch) (Win64, RelWithDebInfo, Static)

**Database version**
ADB_820.00 ( ad18bc3)

**Operating system:** 
Windows 10 x64 Version 2004 (Build 19041.329) Lang deDE

**Comment by Hooaah** [comment]
Having the same issue

**Comment by AsoraXDev** [comment]
Fixed it....


Fix 1:
Change Line 2200 in [Path]\AshamaneCore\sql\base\auth_database.sql
```
INSERT INTO `updates` VALUES (`name`, `hash`, `state`, `timestamp`, `speed`)
```
To
```
INSERT INTO `updates` VALUES 
```

Fix 2:
[PATH]\AshamaneCore\sql\ashamane\auth\2019_09_07_01_auth.sql
```ALTER TABLE `account`
  CHANGE COLUMN `sessionkey` `sessionkey` varchar(128) NOT NULL DEFAULT '';```

is obsolete -> Move file to [PATH]\AshamaneCore\sql\old\8.x\auth\19071_2020_06_17 (or delete it => may not recommended)

Fix 3:
in the Database ADB_hotfixes_820.00.sql & ADB_world_820.00.sql

Remove the USE `ashamane_XXXXXX` in BOTH! files (optional) or set the database name in worldserver.conf to ashamane_[database]


@Hooaah Would be nice to know if it's working for you ;)

**Comment by Hooaah** [comment]
Worked great, Thanks!

**Comment by mastermind007** [comment]
The is an extra VALUES in the query.
Should be `INSERT INTO `updates` (`name`, `hash`, `state`, `timestamp`, `speed`) VALUES` and not
`INSERT INTO `updates` VALUES (`name`, `hash`, `state`, `timestamp`, `speed`) VALUES`

**Comment by Hooaah** [comment]
> 
> 
> The is an extra VALUES in the query.
> Should be `INSERT INTO `updates` (`name`, `hash`, `state`, `timestamp`, `speed`) VALUES` and not
> `INSERT INTO `updates` VALUES (`name`, `hash`, `state`, `timestamp`, `speed`) VALUES`

agree, now i have updated mine to 35662 and fixed issues with auth also deleted a unnecessary file. Now it compiles and build with no issues, but cannot upload to Github for everyone else.
