### ISSUE TITLE
Rééquiper le front ( quête chez les nains , forgefer )

### ISSUE THREAD

**Issue by Pouloss** [AshamaneProject/AshamaneCore#26]
Bonjour ,

Je ne peux pas prendre la quête " Rééquiper le front " , car sa me dit " Votre journal des quêtes est plein " alors que j'ai seulement une quête dans mon journal..C'est une quête pour les forgerons et je suis forgerons justement . Alors y a un problème quelque part , et pi même si je l'étais pas , je pense qu'on peut quand même la prendre normalement .

La quête ce trouve ici :
https://www.noelshack.com/2017-49-1-1512398628-wowscrnshot-120417-144433.jpg

Sur ce PNJ :
https://www.noelshack.com/2017-49-1-1512398753-wowscrnshot-120417-144441.jpg

Preuve du message d'erreur que mon journal est plein:
https://www.noelshack.com/2017-49-1-1512398818-wowscrnshot-120417-144503.jpg

Bon pour le nombre de quête que j'ai , on le voit sur le screen ou je montre ma carte .Que j'ai une seule quête.

Merci
Cordialement Pouloss

**Comment by Traesh** [comment]
Fixed by 98259451c40a193c43f039c96584331208092e3a
