### ISSUE TITLE
Tethyr ( mob élite sur l'île de theramore)

### ISSUE THREAD

**Issue by Pouloss** [AshamaneProject/AshamaneCore#260]
Bonjour ,

Cette chose tellement moche nommer " Tethyr ": 
https://www.noelshack.com/2017-51-3-1513781974-wowscrnshot-122017-155649.jpg

Ce trouve ici dans les marécage d'aprefange ( île de theramore):
https://www.noelshack.com/2017-51-3-1513782277-wowscrnshot-122017-155654.jpg

Ce mob oneshot pas , mais il fait très mal, je sais pas si c'est normal. De plus je suis pas sur qu'il soit bien placer , tout le monde va ce faire tuer en passant sur le pont.Mon bouclier divin ma sauver la vie .

Merci
Cordialement Pouloss

**Comment by Traesh** [comment]
Corrigé par 3210837f27df1ce280531a524c06be9ec42b5863

Ce mob est au bon endroit il fait partie d'une quête normalement phasée, je l'ai mis en non-agressif par défaut afin de ne pas bloquer les joueurs bas niveau
