### ISSUE TITLE
compile error with asio

### ISSUE THREAD

**Issue by firelook** [AshamaneProject/AshamaneCore#261]
since few days I have this error on compiling under windows 10

this is where I put the debug
[https://justpaste.it/5w5er](https://justpaste.it/5w5er)

if you want below the same
`D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\asio_compatibility.hpp(57,28): error C2039: 'io_service': is not a member of 'boost::asio' (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
c:\local\boost_1_67_0\boost/asio/impl/write_at.hpp(36): message : see declaration of 'boost::asio' (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\asio_compatibility.hpp(57,38): error C2061: syntax error: identifier 'io_service' (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\asio_compatibility.hpp(58,53): error C2039: 'iterator': is not a member of 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp>' (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\common\Asio\AsioHacksFwd.h(65): message : see declaration of 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp>' (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\asio_compatibility.hpp(58,61): error C2061: syntax error: identifier 'iterator' (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\asio_compatibility.hpp(59,59): error C2039: 'iterator': is not a member of 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp>' (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\common\Asio\AsioHacksFwd.h(65): message : see declaration of 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp>' (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\asio_compatibility.hpp(59,67): error C2061: syntax error: identifier 'iterator' (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\asio_compatibility.hpp(62,20): error C2065: 'io_context': undeclared identifier (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\asio_compatibility.hpp(62,32): error C2065: 'context': undeclared identifier (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\asio_compatibility.hpp(62,56): error C2065: 'handler': undeclared identifier (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\asio_compatibility.hpp(62,3): error C2182: 'post': illegal use of type 'void' (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\asio_compatibility.hpp(62,15): error C7525: inline variables require at least '/std:c++17' (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\asio_compatibility.hpp(62,65): error C2447: '{': missing function header (old-style formal list?) (compiling source file D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp) [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]`

**Comment by Hooaah** [comment]
I used Boost 1.72.0 to resolve my issue.

**Comment by firelook** [comment]
I have the same with  boost 1.75 
https://pastebin.com/Yr457j9R

`D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp
  Main.cpp
  RESTService.cpp
D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\server_http.h(296,1): error C2664: 'boost::asio::basic_waitable_timer<std::chrono::steady_clock,boost::asio::wait_traits<Clock>,boost::asio::any_io_executor>::basic_waitable_timer(const boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context &>,boost::asio::execution::detail::blocking::never_t<0>,boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0>>> &,const std::chrono::time_point<std::chrono::steady_clock,std::chrono::nanoseconds> &)': cannot convert argument 1 from 'boost::asio::executor' to 'const boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context &>,boost::asio::execution::detail::blocking::never_t<0>,boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0>>> &' [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]`


perhaps it is my declaration of boost, do you have a print screen please of your cmake ?

P.S.
it is working fine with Trinity

**Comment by DuelistRag3** [comment]
> I have the same with boost 1.75
> https://pastebin.com/Yr457j9R
> 
> `D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\RESTService.cpp Main.cpp RESTService.cpp D:\users_sys\games\wow\mangos\git\AshamaneCore\src\server\worldserver\TCRest\server_http.h(296,1): error C2664: 'boost::asio::basic_waitable_timer<std::chrono::steady_clock,boost::asio::wait_traits<Clock>,boost::asio::any_io_executor>::basic_waitable_timer(const boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context &>,boost::asio::execution::detail::blocking::never_t<0>,boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0>>> &,const std::chrono::time_point<std::chrono::steady_clock,std::chrono::nanoseconds> &)': cannot convert argument 1 from 'boost::asio::executor' to 'const boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context &>,boost::asio::execution::detail::blocking::never_t<0>,boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0>>> &' [D:\users_sys\games\wow\mangos\git\AshamaneCore\bin\src\server\worldserver\worldserver.vcxproj]`
> 
> perhaps it is my declaration of boost, do you have a print screen please of your cmake ?
> 
> P.S.
> it is working fine with Trinity

do as @Hooaah said, boost 75 will not work with ashamane if 72 also not work try to land somewhere in 60 area, 66 as example, i compile all my projects in 66

**Comment by Hooaah** [comment]
Just recompiled using Mysql 8.0 boost 1.72 and cmake 3.18.5 and getting no errors at all.

**Comment by Hooaah** [comment]
This was with a fresh download of Ashamanecore also.

**Comment by firelook** [comment]
> Just recompiled using Mysql 8.0 boost 1.72 and cmake 3.18.5 and getting no errors at all.

quite strange, the only thing that means is the cmake, can you share it please ?

**Comment by Hooaah** [comment]
For some unseen issue can't print screen right now, but I copied cmake compile file.

# This is the CMakeCache file.
# For build in directory: b:/Build3
# It was generated by CMake: C:/Program Files/CMake/bin/cmake.exe
# You can edit this file to change values found and used by cmake.
# If you do not want to change any of the values, simply exit the editor.
# If you do want to change a value, simply edit, save, and exit the editor.
# The syntax for the file is as follows:
# KEY:TYPE=VALUE
# KEY is the name of a variable in the cache.
# TYPE is a hint to GUIs for the type of VALUE, DO NOT EDIT TYPE!.
# VALUE is the current value for the KEY.

########################
# EXTERNAL cache entries
########################

//Value Computed by CMake
AshamaneCore_BINARY_DIR:STATIC=B:/Build3

//Value Computed by CMake
AshamaneCore_SOURCE_DIR:STATIC=B:/AshamaneCore-master

//Boost atomic library (debug)
Boost_ATOMIC_LIBRARY_DEBUG:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_atomic-vc142-mt-gd-x64-1_72.lib

//Boost atomic library (release)
Boost_ATOMIC_LIBRARY_RELEASE:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_atomic-vc142-mt-x64-1_72.lib

//Boost chrono library (debug)
Boost_CHRONO_LIBRARY_DEBUG:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_chrono-vc142-mt-gd-x64-1_72.lib

//Boost chrono library (release)
Boost_CHRONO_LIBRARY_RELEASE:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_chrono-vc142-mt-x64-1_72.lib

//Boost date_time library (debug)
Boost_DATE_TIME_LIBRARY_DEBUG:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_date_time-vc142-mt-gd-x64-1_72.lib

//Boost date_time library (release)
Boost_DATE_TIME_LIBRARY_RELEASE:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_date_time-vc142-mt-x64-1_72.lib

//The directory containing a CMake configuration file for Boost.
Boost_DIR:PATH=Boost_DIR-NOTFOUND

//Boost filesystem library (debug)
Boost_FILESYSTEM_LIBRARY_DEBUG:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_filesystem-vc142-mt-gd-x64-1_72.lib

//Boost filesystem library (release)
Boost_FILESYSTEM_LIBRARY_RELEASE:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_filesystem-vc142-mt-x64-1_72.lib

//Path to a file.
Boost_INCLUDE_DIR:PATH=C:/local/boost_1_72_0

//Boost iostreams library (debug)
Boost_IOSTREAMS_LIBRARY_DEBUG:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_iostreams-vc142-mt-gd-x64-1_72.lib

//Boost iostreams library (release)
Boost_IOSTREAMS_LIBRARY_RELEASE:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_iostreams-vc142-mt-x64-1_72.lib

//Boost library directory DEBUG
Boost_LIBRARY_DIR_DEBUG:PATH=C:/local/boost_1_72_0/lib64-msvc-14.2

//Boost library directory RELEASE
Boost_LIBRARY_DIR_RELEASE:PATH=C:/local/boost_1_72_0/lib64-msvc-14.2

//Boost program_options library (debug)
Boost_PROGRAM_OPTIONS_LIBRARY_DEBUG:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_program_options-vc142-mt-gd-x64-1_72.lib

//Boost program_options library (release)
Boost_PROGRAM_OPTIONS_LIBRARY_RELEASE:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_program_options-vc142-mt-x64-1_72.lib

//Boost regex library (debug)
Boost_REGEX_LIBRARY_DEBUG:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_regex-vc142-mt-gd-x64-1_72.lib

//Boost regex library (release)
Boost_REGEX_LIBRARY_RELEASE:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_regex-vc142-mt-x64-1_72.lib

//Boost system library (debug)
Boost_SYSTEM_LIBRARY_DEBUG:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_system-vc142-mt-gd-x64-1_72.lib

//Boost system library (release)
Boost_SYSTEM_LIBRARY_RELEASE:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_system-vc142-mt-x64-1_72.lib

//Boost thread library (debug)
Boost_THREAD_LIBRARY_DEBUG:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_thread-vc142-mt-gd-x64-1_72.lib

//Boost thread library (release)
Boost_THREAD_LIBRARY_RELEASE:FILEPATH=C:/local/boost_1_72_0/lib64-msvc-14.2/libboost_thread-vc142-mt-x64-1_72.lib

//Path to a program.
CMAKE_AR:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/lib.exe

//Semicolon separated list of supported configuration types, only
// supports Debug, Release, MinSizeRel, and RelWithDebInfo, anything
// else will be ignored.
CMAKE_CONFIGURATION_TYPES:STRING=Debug;Release;MinSizeRel;RelWithDebInfo

//Flags used by the CXX compiler during all build types.
CMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc

//Flags used by the CXX compiler during DEBUG builds.
CMAKE_CXX_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1

//Flags used by the CXX compiler during MINSIZEREL builds.
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG

//Flags used by the CXX compiler during RELEASE builds.
CMAKE_CXX_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG

//Flags used by the CXX compiler during RELWITHDEBINFO builds.
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG

//Libraries linked by default with all C++ applications.
CMAKE_CXX_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib

//Flags used by the C compiler during all build types.
CMAKE_C_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3

//Flags used by the C compiler during DEBUG builds.
CMAKE_C_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1

//Flags used by the C compiler during MINSIZEREL builds.
CMAKE_C_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG

//Flags used by the C compiler during RELEASE builds.
CMAKE_C_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG

//Flags used by the C compiler during RELWITHDEBINFO builds.
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG

//Libraries linked by default with all C applications.
CMAKE_C_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib

//Flags used by the linker during all build types.
CMAKE_EXE_LINKER_FLAGS:STRING=/machine:x64

//Flags used by the linker during DEBUG builds.
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL

//Flags used by the linker during MINSIZEREL builds.
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO

//Flags used by the linker during RELEASE builds.
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO

//Flags used by the linker during RELWITHDEBINFO builds.
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL

//Install path prefix, prepended onto install directories.
CMAKE_INSTALL_PREFIX:PATH=C:/Program Files (x86)/AshamaneCore

//Path to a program.
CMAKE_LINKER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/link.exe

//Flags used by the linker during the creation of modules during
// all build types.
CMAKE_MODULE_LINKER_FLAGS:STRING=/machine:x64

//Flags used by the linker during the creation of modules during
// DEBUG builds.
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL

//Flags used by the linker during the creation of modules during
// MINSIZEREL builds.
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO

//Flags used by the linker during the creation of modules during
// RELEASE builds.
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO

//Flags used by the linker during the creation of modules during
// RELWITHDEBINFO builds.
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL

//Path to a program.
CMAKE_MT:FILEPATH=CMAKE_MT-NOTFOUND

//Value Computed by CMake
CMAKE_PROJECT_DESCRIPTION:STATIC=

//Value Computed by CMake
CMAKE_PROJECT_HOMEPAGE_URL:STATIC=

//Value Computed by CMake
CMAKE_PROJECT_NAME:STATIC=AshamaneCore

//RC compiler
CMAKE_RC_COMPILER:FILEPATH=rc

//Flags for Windows Resource Compiler during all build types.
CMAKE_RC_FLAGS:STRING=-DWIN32

//Flags for Windows Resource Compiler during DEBUG builds.
CMAKE_RC_FLAGS_DEBUG:STRING=-D_DEBUG

//Flags for Windows Resource Compiler during MINSIZEREL builds.
CMAKE_RC_FLAGS_MINSIZEREL:STRING=

//Flags for Windows Resource Compiler during RELEASE builds.
CMAKE_RC_FLAGS_RELEASE:STRING=

//Flags for Windows Resource Compiler during RELWITHDEBINFO builds.
CMAKE_RC_FLAGS_RELWITHDEBINFO:STRING=

//Flags used by the linker during the creation of shared libraries
// during all build types.
CMAKE_SHARED_LINKER_FLAGS:STRING=/machine:x64

//Flags used by the linker during the creation of shared libraries
// during DEBUG builds.
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL

//Flags used by the linker during the creation of shared libraries
// during MINSIZEREL builds.
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO

//Flags used by the linker during the creation of shared libraries
// during RELEASE builds.
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO

//Flags used by the linker during the creation of shared libraries
// during RELWITHDEBINFO builds.
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL

//If set, runtime paths are not added when installing shared libraries,
// but are added when building.
CMAKE_SKIP_INSTALL_RPATH:BOOL=OFF

//If set, runtime paths are not added when using shared libraries.
CMAKE_SKIP_RPATH:BOOL=OFF

//Flags used by the linker during the creation of static libraries
// during all build types.
CMAKE_STATIC_LINKER_FLAGS:STRING=/machine:x64

//Flags used by the linker during the creation of static libraries
// during DEBUG builds.
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during the creation of static libraries
// during MINSIZEREL builds.
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during the creation of static libraries
// during RELEASE builds.
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during the creation of static libraries
// during RELWITHDEBINFO builds.
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//If this value is on, makefiles will be generated without the
// .SILENT directive, and all commands will be echoed to the console
// during the make.  This is useful for debugging only. With Visual
// Studio IDE projects all commands are done without /nologo.
CMAKE_VERBOSE_MAKEFILE:BOOL=OFF

//Dependencies for the target
Detour_LIB_DEPENDS:STATIC=general;zlib;

//Full path to git commandline client
GIT_EXECUTABLE:FILEPATH=C:/Program Files/Git/cmd/git.exe

//Path to a library.
LIB_EAY_DEBUG:FILEPATH=C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib

//Path to a library.
LIB_EAY_RELEASE:FILEPATH=C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib

//path to your mysql binary.
MYSQL_EXECUTABLE:FILEPATH=C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe

//Specify the directory containing mysql.h.
MYSQL_INCLUDE_DIR:PATH=C:/Program Files/MySQL/MySQL Server 8.0/include

//Specify the location of the mysql library here.
MYSQL_LIBRARY:FILEPATH=C:/Program Files/MySQL/MySQL Server 8.0/lib/libmysql.lib

//Path to a file.
OPENSSL_INCLUDE_DIR:PATH=C:/Program Files/OpenSSL-Win64/include

//Path to a file.
OPENSSL_ROOT_DIR:PATH=C:/Program Files/OpenSSL-Win64

//Dependencies for the target
Recast_LIB_DEPENDS:STATIC=general;zlib;

//Build core with scripts
SCRIPTS:STRING=static

//Build type of the BrokenIsles module.
SCRIPTS_BROKENISLES:STRING=default

//Build type of the Commands module.
SCRIPTS_COMMANDS:STRING=default

//Build type of the Custom module.
SCRIPTS_CUSTOM:STRING=default

//Build type of the DarkmoonIsland module.
SCRIPTS_DARKMOONISLAND:STRING=default

//Build type of the Draenor module.
SCRIPTS_DRAENOR:STRING=default

//Build type of the EasternKingdoms module.
SCRIPTS_EASTERNKINGDOMS:STRING=default

//Build type of the Events module.
SCRIPTS_EVENTS:STRING=default

//Build type of the Kalimdor module.
SCRIPTS_KALIMDOR:STRING=default

//Build type of the KulTiras module.
SCRIPTS_KULTIRAS:STRING=default

//Build type of the Maelstrom module.
SCRIPTS_MAELSTROM:STRING=default

//Build type of the Northrend module.
SCRIPTS_NORTHREND:STRING=default

//Build type of the OutdoorPvP module.
SCRIPTS_OUTDOORPVP:STRING=default

//Build type of the Outland module.
SCRIPTS_OUTLAND:STRING=default

//Build type of the Pandaria module.
SCRIPTS_PANDARIA:STRING=default

//Build type of the Pet module.
SCRIPTS_PET:STRING=default

//Build type of the Scenarios module.
SCRIPTS_SCENARIOS:STRING=default

//Build type of the Spells module.
SCRIPTS_SPELLS:STRING=default

//Build type of the World module.
SCRIPTS_WORLD:STRING=default

//Build type of the Zandalar module.
SCRIPTS_ZANDALAR:STRING=default

//Build worldserver and bnetserver
SERVERS:BOOL=ON

//Path to a library.
SSL_EAY_DEBUG:FILEPATH=C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MDd.lib

//Path to a library.
SSL_EAY_RELEASE:FILEPATH=C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MD.lib

//Build map/vmap/mmap extraction/assembler tools
TOOLS:BOOL=ON

//Use precompiled headers when compiling servers
USE_COREPCH:BOOL=ON

//Use precompiled headers when compiling scripts
USE_SCRIPTPCH:BOOL=ON

//Disable the GIT testing routines
WITHOUT_GIT:BOOL=OFF

//Include additional debug-code in core
WITH_COREDEBUG:BOOL=OFF

//Enable CPR dep (curl wrapper)
WITH_CPR:BOOL=OFF

//Enable dynamic library linking.
WITH_DYNAMIC_LINKING:BOOL=OFF

//Build the source tree for IDE's.
WITH_SOURCE_TREE:STRING=hierarchical

//Show all warnings during compile
WITH_WARNINGS:BOOL=OFF

//Dependencies for the target
casc_LIB_DEPENDS:STATIC=general;zlib;

//Dependencies for the target
common_LIB_DEPENDS:STATIC=general;fmt;general;g3dlib;general;Detour;

//Dependencies for the target
database_LIB_DEPENDS:STATIC=general;mysql;general;common;

//Dependencies for the target
extractor_common_LIB_DEPENDS:STATIC=general;casc;general;common;

//Dependencies for the target
g3dlib_LIB_DEPENDS:STATIC=general;zlib;

//Dependencies for the target
proto_LIB_DEPENDS:STATIC=general;common;general;protobuf;

//Dependencies for the target
shared_LIB_DEPENDS:STATIC=general;database;general;proto;general;zlib;general;gsoap;

**Comment by Hooaah** [comment]
This is my end result of compile.

25>worldserver.vcxproj -> B:\Build3\bin\Release\worldserver.exe
26>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
26>Building Custom Rule B:/AshamaneCore-master/CMakeLists.txt
========== Build: 26 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by firelook** [comment]
1.72 is working fine for boost not 1.75 ;)
thanks to all !!!!

**Comment by Hooaah** [comment]
Your welcome, enjoy !
