### ISSUE TITLE
Error Compiling on linux do to windows dependencies. 

### ISSUE THREAD

**Issue by bluflippy** [AshamaneProject/AshamaneCore#263]
Line 21 of  AshamaneCore/src/server/scripts/Commands/cs_export.cpp  contains  #include <Windows.h>

#include "SpellMgr.h"
#include "DatabaseEnv.h"
#include "RBAC.h"
#include "ScriptMgr.h"
#include "ObjectMgr.h"
#include "MapManager.h"
#include "Chat.h"
#include <stdlib.h>
#include "DB2Stores.h"
#include "PhasingHandler.h"
#include "Creature.h"
#include "World.h"
#include <Windows.h>
class CommadExportHelper

removing this line causing compiling to fail with:

/AshamaneCore/source/src/server/scripts/Commands/cs_export.cpp:5413:22: error: ‘_strtoui64’ was not declared in this scope; did you mean ‘strtof64’?
 5413 |             _Entry = _strtoui64(( char* )aArgs, NULL, 10);

**Comment by DuelistRag3** [comment]
when you try to compile the Source on Linux its essential to kick out the export.cpp for now, i try to find a way to keep it atm
