### ISSUE TITLE
ERROR Build of the "worldserver.vcxproj" 

### ISSUE THREAD

**Issue by 790113822** [AshamaneProject/AshamaneCore#269]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1181	无法打开输入文件“..\scripts\Debug\scripts.lib”	worldserver	G:\Build\src\server\worldserver\LINK	1	

google translation：
Severity Code Description Item File Line Prohibited status
Error LNK1181 Unable to open the input file "..\scripts\Debug\scripts.lib" worldserver G:\Build\src\server\worldserver\LINK 1

**Comment by DuelistRag3** [comment]
we need a little bit more infos then that

**Comment by 790113822** [comment]
> 我們需要更多信息，然後

我目前无法提供更多的信息，因为只有这一个错误。

google translation：
I can't provide more information at the moment because there is only this one error.

**Comment by 790113822** [comment]
已启动生成…
1>------ 已启动生成: 项目: worldserver, 配置: Debug x64 ------
1>Building Custom Rule G:/Trinity/src/server/worldserver/CMakeLists.txt
1>cmake_pch.cxx
1>Main.cpp
1>CliRunnable.cpp
1>RASession.cpp
1>RESTService.cpp
1>TCSoap.cpp
1>WheatyExceptionReport.cpp
1>ServiceWin32.cpp
1>LINK : fatal error LNK1181: 无法打开输入文件“..\scripts\Debug\scripts.lib”
1>已完成生成项目“worldserver.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

google translation：
Generation started...
1>------ Build has been started: Project: worldserver, Configuration: Debug x64 ------
1>Building Custom Rule G:/Trinity/src/server/worldserver/CMakeLists.txt
1>cmake_pch.cxx
1>Main.cpp
1>CliRunnable.cpp
1>RASession.cpp
1>RESTService.cpp
1>TCSoap.cpp
1>WheatyExceptionReport.cpp
1>ServiceWin32.cpp
1>LINK: fatal error LNK1181: Unable to open input file "..\scripts\Debug\scripts.lib"
1>The operation of generating the project "worldserver.vcxproj" has been completed-failed.
========== Generate: 0 succeeded, 1 failed, 0 newest, 0 skipped ==========

> we need a little bit more infos then that

**Comment by rem999** [comment]
У меня тоже самое. Второй год пошёл. Не могут исправить.
I have the same. The second year has gone. Can't fix it.

**Comment by DuelistRag3** [comment]
which boost version you two use and on which rev. you building

**Comment by rem999** [comment]
> which boost version you two use and on which rev. you building

Глупый вопрос. У Trinity/Core работает. У вас не работает.
Stupid question. Trinity / Core works. It doesn't work for you.

**Comment by DuelistRag3** [comment]
absolutly not a dumb question, just answer it ffs, there was more then once the case that trinity worked with the installed boost version and ashamane didn´t and the second question was also not answered, on which rev. you two try to build. I have absolutly no error while building the source

**Comment by Hooaah** [comment]
I use mysql 8.0 and boost 172 have no issues compiling, but when i start to build server this is as far as i can get.

AshamaneCore, revision unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static) (worldserver-daemon)
<Ctrl-C> to stop.

               _                                      
     /\       | |                                     
    /  \   ___| |__   __ _ _ __ ___   __ _ _ __   ___ 
   / /\ \ / __| '_ \ / _` | '_ ` _ \ / _` | '_ \ / _ \
  / ____ \\__ \ | | | (_| | | | | | | (_| | | | |  __/
 /_/    \_\___/_| |_|\__,_|_| |_| |_|\__,_|_| |_|\___|

          The Ashamane Project - Ashamane Core
 
 
Based on TrinityCore, with credit to their team and contributions.
http://TrinityCore.org
 
 
Using configuration file B:/Core/worldserver.conf.
Using SSL version: OpenSSL 1.1.1h  22 Sep 2020 (library: OpenSSL 1.1.1h  22 Sep 2020)
Using Boost version: 1.72.0
Database "ashamane_auth" does not exist, do you want to create it? [yes (default) / no]: 
Creating database "ashamane_auth"...
mysql: [Warning] Using a password on the command line interface can be insecure.


Done.
Database "ashamane_characters" does not exist, do you want to create it? [yes (default) / no]: 
Creating database "ashamane_characters"...
mysql: [Warning] Using a password on the command line interface can be insecure.


Done.
Database "ashamane_world" does not exist, do you want to create it? [yes (default) / no]: 
Creating database "ashamane_world"...
mysql: [Warning] Using a password on the command line interface can be insecure.


Done.
Database "ashamane_hotfixes" does not exist, do you want to create it? [yes (default) / no]: 
Creating database "ashamane_hotfixes"...
mysql: [Warning] Using a password on the command line interface can be insecure.


Done.
Database Auth is empty, auto populating it...
>> Applying 'B:/AshamaneCore-master/sql/base/auth_database.sql'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Done!
Database Character is empty, auto populating it...
>> Applying 'B:/AshamaneCore-master/sql/base/characters_database.sql'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Done!
Database World is empty, auto populating it...
>> Applying 'ADB_world_820.00.sql'...
mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 2006 (HY000) at line 23912: MySQL server has gone away


Applying of file 'ADB_world_820.00.sql' to database 'ashamane_world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not populate the World database, see log for details.

**Comment by DuelistRag3** [comment]
@Hooaah it is another issue then op, but i will answer it anyway, because it is a very common issue, which i see often, pls increase two values in your msql config: "wait_timeout" and "max_allowed_packet_size". If you don't know how to do so, pls Google it, because I'm already in bed 😅 and don't wanna explain right now, after you increased those values, restart your MySQL Server and begin database creation from scratch (delete the databases)

**Comment by Hooaah** [comment]
Sorry my bad, reinstalled server and forgot to change settings.

**Comment by DuelistRag3** [comment]
@Traesh can we state it somewhere, for new people? In my opinion it's a pretty common issue and afaik, it's not in the trinity wiki

**Comment by rem999** [comment]
> absolutly not a dumb question, just answer it ffs, there was more then once the case that trinity worked with the installed boost version and ashamane didn´t and the second question was also not answered, on which rev. you two try to build. I have absolutly no error while building the source

Потренируйтесь. Спросите у Trinity. И только после публикуйте. Единицы могут собрать. Естественно на английском языке.
Practice. Ask Trinity. And only then publish. Units can collect. Naturally in English.

**Comment by 790113822** [comment]
我已经解决了这个问题，谢谢你们的帮助。

I have solved this problem. Thank you for your help.

**Comment by DuelistRag3** [comment]
> 我已经解决了这个问题，谢谢你们的帮助。
> 
> I have solved this problem. Thank you for your help.

Please consider sharing what you did to solve it.

**Comment by 790113822** [comment]
> > 我已经解决了这个问题，谢谢你们的帮助。
> > I have solved this problem. Thank you for your help.
> 
> Please consider sharing what you did to solve it.

我无法提供任何帮助，因为我换了一台电脑进行编译后又不正常了。

I have solved this problem. Thank you for your help.

**Comment by 790113822** [comment]
> > 我已经解决了这个问题，谢谢你们的帮助。
> > I have solved this problem. Thank you for your help.
> 
> Please consider sharing what you did to solve it.

我无法提供任何帮助，因为我换了一台电脑进行编译后又不正常了。

google translation：
I can't provide any help, because I changed a computer to compile and it was abnormal.

**Comment by 790113822** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1181	无法打开输入文件“..\scripts\Debug\scripts.lib”	worldserver	I:\buding2\src\server\worldserver\LINK	1	
错误	C2059	语法错误:“{”	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp	821	
错误	C2334	“{”的前面有意外标记；跳过明显的函数体	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp	821	
错误	C3861	“RemoveEncounterAuras”: 找不到标识符	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp	397	
错误	C3861	“RemoveEncounterAuras”: 找不到标识符	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp	494	
错误	C3861	“RemoveEncounterAuras”: 找不到标识符	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp	539	
错误	C2065	“AREA_2”: 未声明的标识符	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp	297	
错误	C2065	“AREA_4”: 未声明的标识符	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp	305	
错误	C2065	“AREA_5”: 未声明的标识符	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp	309	
错误	C2051	case 表达式不是常量	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp	297	
错误	C2051	case 表达式不是常量	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp	305	
错误	C2051	case 表达式不是常量	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp	309	

google translation：
Severity Code Description Item File Line Prohibited status
Error LNK1181 Cannot open the input file "..\scripts\Debug\scripts.lib" worldserver I:\buding2\src\server\worldserver\LINK 1
Error C2059 Syntax error: "{" scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp 821
Error C2334 Unexpected mark before "{"; skip obvious function body scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp 821
Error C3861 "RemoveEncounterAuras": Could not find identifier scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp 397
Error C3861 "RemoveEncounterAuras": Cannot find identifier scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp 494
Error C3861 "RemoveEncounterAuras": Cannot find identifier scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp 539
Error C2065 "AREA_2": Undeclared identifier scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp 297
Error C2065 "AREA_4": Undeclared identifier scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp 305
Error C2065 "AREA_5": Undeclared identifier scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp 309
Error C2051 case expression is not a constant scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp 297
Error C2051 case expression is not a constant scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp 305
Error C2051 case expression is not a constant scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp 309

**Comment by 790113822** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1181	无法打开输入文件“..\scripts\Debug\scripts.lib”	worldserver	I:\buding2\src\server\worldserver\LINK	1	
错误	C2059	语法错误:“{”	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp	821	
错误	C2334	“{”的前面有意外标记；跳过明显的函数体	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp	821	
错误	C3861	“RemoveEncounterAuras”: 找不到标识符	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp	397	
错误	C3861	“RemoveEncounterAuras”: 找不到标识符	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp	494	
错误	C3861	“RemoveEncounterAuras”: 找不到标识符	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp	539	
错误	C2065	“AREA_2”: 未声明的标识符	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp	297	
错误	C2065	“AREA_4”: 未声明的标识符	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp	305	
错误	C2065	“AREA_5”: 未声明的标识符	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp	309	
错误	C2051	case 表达式不是常量	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp	297	
错误	C2051	case 表达式不是常量	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp	305	
错误	C2051	case 表达式不是常量	scripts	I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp	309	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1181	无法打开输入文件“..\scripts\Debug\scripts.lib”	worldserver	I:\buding2\src\server\worldserver\LINK	1	

google translation：
Severity Code Description Item File Line Prohibited status
Error LNK1181 Cannot open the input file "..\scripts\Debug\scripts.lib" worldserver I:\buding2\src\server\worldserver\LINK 1
Error C2059 Syntax error: "{" scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp 821
Error C2334 Unexpected mark before "{"; skip obvious function body scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp 821
Error C3861 "RemoveEncounterAuras": Could not find identifier scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp 397
Error C3861 "RemoveEncounterAuras": Cannot find identifier scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp 494
Error C3861 "RemoveEncounterAuras": Cannot find identifier scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_alysrazor.cpp 539
Error C2065 "AREA_2": Undeclared identifier scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp 297
Error C2065 "AREA_4": Undeclared identifier scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp 305
Error C2065 "AREA_5": Undeclared identifier scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp 309
Error C2051 case expression is not a constant scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp 297
Error C2051 case expression is not a constant scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp 305
Error C2051 case expression is not a constant scripts I:\AshamaneCore-master\src\server\scripts\Kalimdor\Firelands\boss_shannox.cpp 309
Severity Code Description Item File Line Prohibited status
Error LNK1181 Cannot open the input file "..\scripts\Debug\scripts.lib" worldserver I:\buding2\src\server\worldserver\LINK 1

**Comment by 790113822** [comment]
> which boost version you two use and on which rev. you building
boost_1_72_0-msvc-14.2-64

**Comment by 790113822** [comment]
我将Cmake中的SCRIPTS设置为dynamic。现在我可以建立worldserver.exe了，但是出现了非常多的C3859和C1076错误。

google translation：
I set SCRIPTS in Cmake to dynamic. Now I can create worldserver.exe, but there are a lot of C3859 and C1076 errors.

**Comment by Traesh** [comment]
@DuelistRag3 I need to redo the full world.sql so it don't trigger the max_allowed_packet limit

I'll try to do it soon
