### ISSUE TITLE
GossipMenuItem doesn't working

### ISSUE THREAD

**Issue by src893** [AshamaneProject/AshamaneCore#271]
**Description:**

GossipMenu with codebox is not working since 9.x update.

**Current behaviour:**

1) Download sources 

2) Create a small c++ script for an npc or gameobject and add an gossip item like this :

3) AddGossipItemFor(payer, GOSSIP_ICON_CHAT, "Hello this is a simple test.", GOSSIP_SENDER_MAIN, 0, "Hello this is a popup without codebox", 0, false);
AddGossipItemFor(payer, GOSSIP_ICON_CHAT, "Hello this is a simple test.", GOSSIP_SENDER_MAIN, 0, "Hello this is a popup with codebox", 0, true);

4) Go ingame and test your script. No crash but nothing happen. This kind of gossipItem isn't working.

**TC rev. hash/commit:** 

Latest build

**Database version**

ADB latest version

**Operating system:**

Windows

**Comment by Traesh** [comment]
What GossipHello method are you using ? It may be a simple merge error on my side

**Comment by src893** [comment]
> What GossipHello method are you using ? It may be a simple merge error on my side

OnGossipSelect
OnGossipSelectCode

**Comment by src893** [comment]
> What GossipHello method are you using ? It may be a simple merge error on my side

Did u have test it? On my side nothing is working when I try to create an c++ gossip with mode OnGossipSelect and OnGossipSelectCode hook. OnGossipoHello hook is working as well but nothing else.

**Comment by src893** [comment]
> What GossipHello method are you using ? It may be a simple merge error on my side

Latest update solve partialy the problem. gossip with promotioncode is not handled correctly with OnGossipSelectCode method.
