### ISSUE TITLE
possible to match master = 9.0.2.37474 from Trinity ?

### ISSUE THREAD

**Issue by firelook** [AshamaneProject/AshamaneCore#272]
to be sqare please with the latest version  :
master = 9.0.2.37474

thanks in advance

**Comment by Hooaah** [comment]
you can update it yourself, by updating Auth sql in base folder to newest and adding a auth file from trinity core.

If I had access to update I would do it.

Now I'm working on a source that's made from ashamane with more content and and updated.

Let me know if ya need any more assistance with this.

**Comment by firelook** [comment]
thanks
I though everybody has access to update git repository

**Comment by Hooaah** [comment]
https://github.com/Hooaah/AshamaneCore here is an updated version to 37474 and fixed database 8.0.2
