### ISSUE TITLE
Rapport de bug : Depart des gnomes

### ISSUE THREAD

**Issue by Astrozia** [AshamaneProject/AshamaneCore#278]
Quête:
- [x] [Décontamination] http://fr.wowhead.com/quest=27635/decontamination (les machines "sanitron 5000) ne larche pas)
- [ ] [The Future of Gnomeregan] http://fr.wowhead.com/quest=26203/l-avenir-de-gnomeregan (PNJ pour rendre la quête pas la)
- [ ] [L’avenir de Gnomeregan] http://fr.wowhead.com/quest=26199/l-avenir-de-gnomeregan (PNJ pour rendre la quête pas la)

**Comment by zgn1988** [comment]
fixed Décontamination bbd1109

**Comment by somejoshdude** [comment]
In regards to this issue..
Upon entering the object for Decontamination the World Server will crash.
This is based on a fresh compile/rebuild of DB from most recent commit 01/10/2018
