### ISSUE TITLE
Sort charge du guerrier

### ISSUE THREAD

**Issue by Pouloss** [AshamaneProject/AshamaneCore#28]
Bonjour ,

Je me suis fait un guerrier et j'ai remarquer que le sort " charge " ne fonctionne pas comme il est écrie sur le sort. il est censé "l'enracine " pendant 1 sec , et il enracine rien . il est censé réduire la vitesse de déplacement de 50% pendant 6 secondes et j'ai pas l'impression que le mob avance au ralenti . 

Petit screen de ce qui est dit sur le sort:
https://www.noelshack.com/2017-49-2-1512491559-wowscrnshot-120517-155504.jpg

Merci
cordialement Pouloss

**Comment by HannibalRoG** [comment]
Moved to #499
