### ISSUE TITLE
La fenetre de chat 

### ISSUE THREAD

**Issue by father0000** [AshamaneProject/AshamaneCore#32]
Petit problème mais assez ennuyeux pour ceux qui utilise des addon  comme moi, je n'arrive pas a réduire la fenêtre de chat vers la gauche. 

a++
![2017-12-06_135821](https://user-images.githubusercontent.com/34193536/33663046-af46c042-da8e-11e7-949c-8619a3c8a943.png)

**Comment by Traesh** [comment]
Bonjour,

La fenêtre de chat est normalement gérée du client du jeu, avez-vous essayer de faire clic droit sur "General" et "Déverrouiller" ?

**Comment by father0000** [comment]
Salut
Oui j'ai déverrouiller et je peut la déplacer partout sur mon écran de jeux mais en principe ont peut réduire de droite vers la gauche en pointant le curseur dans la partie inférieur droit  de la fenêtrer. Bon c'est pas si important :-) 
 

    Le jeudi 7 décembre 2017 à 12:58:06 UTC+1, Traesh <notifications@github.com> a écrit :  
 
 
Bonjour,

La fenêtre de chat est normalement gérée du client du jeu, avez-vous essayer de faire clic droit sur "General" et "Déverrouiller" ?

**Comment by Traesh** [comment]
Bizarre, la fenêtre de chat peut bien être réduite chez moi ^^ Même si il y a un minimum de largeur

Peut-être une incompatibilité avec un addon ?

**Comment by father0000** [comment]
C'est peut etre ma résolution ou ma carte graphique.. je vais regarder plus tard. Désolé pour le dérangement.a+
 

    Le jeudi 7 décembre 2017 à 14:03:21 UTC+1, Traesh <notifications@github.com> a écrit :  
 
 
Bizarre, la fenêtre de chat peut bien être réduite chez moi ^^ Même si il y a un minimum de largeur

Peut-être une incompatibilité avec un addon ?

**Comment by father0000** [comment]
Jai trouver dans option fenêtre chat j’ai fait reset et ca marche. :-)
 

    Le jeudi 7 décembre 2017 à 14:03:21 UTC+1, Traesh <notifications@github.com> a écrit :  
 
 
Bizarre, la fenêtre de chat peut bien être réduite chez moi ^^ Même si il y a un minimum de largeur

Peut-être une incompatibilité avec un addon ?

**Comment by Traesh** [comment]
Parfait :)
