### ISSUE TITLE
Mob élite qui oneshot ( Loch Modan)

### ISSUE THREAD

**Issue by Pouloss** [AshamaneProject/AshamaneCore#33]
Bonjour,

Le " Monstre de Modan " , un mob dans la zone " Loch Modan " qui ressemble à rien , ma oneshot , je suis pas sur que ses dégâts sois normal:
https://www.noelshack.com/2017-49-3-1512568382-wowscrnshot-120617-144751.jpg

Y en a plusieurs et on les trouve ici , dans le coin la:
https://www.noelshack.com/2017-49-3-1512568821-wowscrnshot-120617-144645.jpg

Merci
Cordialement Pouloss

**Comment by Nexon99** [comment]
Merci Pouloss, ce mob sera prochainement corrigé.

**_Nexon._**

**Comment by Traesh** [comment]
Corrigé :)
