### ISSUE TITLE
[Database] Installing database

### ISSUE THREAD

**Issue by ThisMushroom** [AshamaneProject/AshamaneCore#340]
Whenever one try to install database stuff following error occure.

```
In mysql_stmt_prepare() id: 14, sql: "SELECT item, maxcount, incrtime, ExtendedCost, OverrideGoldCost, type, BonusListIDs, PlayerConditionID, IgnoreFiltering FROM npc_vendor WHERE entry = ? ORDER BY slot ASC"
Unknown column 'OverrideGoldCost' in 'field list'
```

Several interesting moments.

If you take (Files that are requred to be in server-build folder to initially populate db whenever one firstly launch worldserver)

```
TDB_hotfixes_720.00_2017_04_18
TDB_world_720.00_2017_04_18
```

Originated by the TrinityCore - you get those errors.

If you take Ashamane ADB725.03 files and use them for initial population you get only:

```
Applying update "2017_12_03_02_world_undead_start.sql" 'F931509'...
Applying update "2017_12_04_00_world.sql" 'B741D42'...

ERROR 1060 (42S21) at line 1: Duplicate column name 'ScriptName'

Applying of file 'C:/TrinityAshamane/sql/ashamane/world/2017_12_04_00_world.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.
```

I guess it is somewhere in-between the moment when the patch to switch from default to ashamane sql folder applies.

@Traesh , what is corret way to setup the database?

**Comment by leviathonbeast** [comment]
if you have the latest commit and use ADB725.03 it works fine. 

ERROR 1060 (42S21) at line 1: Duplicate column name 'ScriptName' <<<< Was fixed a while back.
