### ISSUE TITLE
Rapport de bug : Dommaine Chasseur

### ISSUE THREAD

**Issue by Astrozia** [AshamaneProject/AshamaneCore#345]
Quête:
- [x] [Rendezvous with the Courier] http://fr.wowhead.com/quest=41540/un-rendez-vous-avec-le-messager (pnj pour rendre la quête pas là)
- [x] [A Beastly Expedition] http://fr.wowhead.com/quest=41541/une-expedition-brutale (pnj pour rendre la quête pas là)
- [x] [Preparation for the Hunt] http://fr.wowhead.com/quest=41542/preparatifs-pour-la-chasse (pnj pour rendre la quête pas là)
- [ ]

**Comment by Nexon99** [comment]
**Corrigé.**
