### ISSUE TITLE
[ Quête ] Ecouter aux portes des trolls

### ISSUE THREAD

**Issue by Cearon** [AshamaneProject/AshamaneCore#348]
Bonjour,

Normalement nous devrions pouvoir valider l'écoute des PNJ juste en étant devant...  La impossible...  
Rien à faire, impossible de valider l'une des trois écoutes...  

http://fr.wowhead.com/quest=24489/ecouter-aux-portes-des-trolls

**Comment by Traesh** [comment]
Closed by 5b82c4da7cef1a82b4af5fb7f6864f67ce2fdfbd
