### ISSUE TITLE
Teleporter bloodstone ne fonctionne pas

### ISSUE THREAD

**Issue by father0000** [AshamaneProject/AshamaneCore#35]
Dans les terres brulées Kasim Sharim donne des quêtes... en principe il faut prendre le teleporter pour se retrouver dehors et un fois les missions complies il faut reprendre le teleporter pour rejoindre Kasim Sharim. 
Ont peut les faire sans le téléporter mais ca va plus vite avec.
![2017-12-06_172907](https://user-images.githubusercontent.com/34193536/33673359-cc415dce-daac-11e7-9580-95e7e0d1cf2d.png)
![2017-12-06_172934](https://user-images.githubusercontent.com/34193536/33673365-d19d17f4-daac-11e7-9e1a-af14c112a34f.png)
![2017-12-06_173039](https://user-images.githubusercontent.com/34193536/33673372-d4ff2068-daac-11e7-8f54-5675c29a7840.png)
![2017-12-06_170036](https://user-images.githubusercontent.com/34193536/33673401-e79e6d64-daac-11e7-8373-7c7feb2400ee.png)

**Comment by aeroashamane** [comment]
Quête fonctionnel
