### ISSUE TITLE
[Quest] Death comes from on high bugged

### ISSUE THREAD

**Issue by Nupper** [AshamaneProject/AshamaneCore#353]
**Description:**
Clicking the post to activate the eye dose not work.

**Usefull Wowhead links:**
http://www.wowhead.com/quest=12641/death-comes-from-on-high

**Comment by RenegadeLegionWow** [comment]
can confirm, player inhabits the eye but it doesnt taxi on its own anywhere (player can control it, but even still cannot use it to complete the quest)

**Comment by Traesh** [comment]
Temp fix : quest is now auto-complete

**Comment by Neredun** [comment]
This quest now works as intended. Although who @RenegadeLegionWow said, the Eye still doesn't taxi himself but it can be controlled and one can complete the quest without problems.
