### ISSUE TITLE
"In the Blink of an eye" not working

### ISSUE THREAD

**Issue by Reforge-Mark** [AshamaneProject/AshamaneCore#356]
The objective you can't complete is Dalaran's Teleportation Witnessed.
The way to complete it should be to go to dalaran above deadwind pass speak to Khadgar and select "I'm ready ,begin the teleportation of dalaran  to the broken islands " and a cinematic start 
But when you select  it nothing happens.

**Usefull Wowhead links:**
http://www.wowhead.com/quest=44184/in-the-blink-of-an-eye

**Comment by Dreda59** [comment]
Also when porting to the Dalaran above Deadwind Pass you can fall through Dalaran.

**Comment by Traesh** [comment]
Falling through should be fixed with 1dc2d519b1af0035767cdb2d5a5b282efe4db253
