### ISSUE TITLE
Wrong Classhall for Rogue

### ISSUE THREAD

**Issue by darkmord1991** [AshamaneProject/AshamaneCore#358]
**Description:**
Rogues go to warlock classhall
tested with undead rogue

**Usefull Wowhead links:**

**Comment by Traesh** [comment]
What ?

**Comment by darkmord1991** [comment]
When you use the portal to the classhall for a rogue, you come to the classhall of the warlocks, sry i used the wrong word

**Comment by Traesh** [comment]
There is no portal to the rogue classhall, it's a secret passage in some dalaran shops

You probably used the warlock TP, i'll add restrictions so only warlock can use that portal :)
