### ISSUE TITLE
[Spell] Hunter's barrage ability

### ISSUE THREAD

**Issue by Nupper** [AshamaneProject/AshamaneCore#370]
**Description:**
This spell indeed causes a crash of the server. 
Tested
![image](https://user-images.githubusercontent.com/6026902/34755567-b03aa858-f5bc-11e7-94d3-0ca9211b9b9d.png)

**Usefull Wowhead links:**
http://www.wowhead.com/spell=120360/barrage

**Comment by Traesh** [comment]
Could you please provide crashlog ?

**Comment by Traesh** [comment]
Closed by e6ce426c9a1cb4c8653c1a2c7d202bc4db705f7a
