### ISSUE TITLE
Core/Spell Report frost mage spell.

### ISSUE THREAD

**Issue by HannibalRoG** [AshamaneProject/AshamaneCore#383]
**Description:**
List of spell with problem Frost mage. 

- [x] Unstable magic ID 157976 - Complete broken.
- [x] Ice floes ID 108839 - Dont consume the charge, you can use indefinitebly
- [x] Bone Chilling ID 205027 - Chill a target dont activate Bone chilling
- [x] Ray of frost ID 205021 - Dont increase 20% damage when it deals damage
- [x] Mastery:Icicles ID 76613 - Dont create icicles with Frostbolt ID 116
- [x] Blizzard ID 236662 - Dont reduce 0.5s the cooldown of the Frozen Orb
- [x] Brain Freeze ID 231584 - Dont apply Winter´s chill.
- [x] Frozen Org ID 84714 - Dont advance forward, it take ramdomly any direction.
- [x] Cold Snap ID 235219 - Complete broken.
- [x] Ice lance ID 30455 - No tripled damage on frozen target.
- [x] Flurry ID 44614 - Dont apply Winter´s chill.
- [x] Thermal Void ID 155149 - Ice Lances against frozen target dont extend Icy veins for additional 1s

**Usefull Wowhead links:**
To be filled

**Comment by somejoshdude** [comment]
Frost Orb is resolved in most recent release. Can confirm.

**Comment by ThisMushroom** [comment]
Most of them are known.
https://github.com/AshamaneProject/AshamaneCore/pull/376

**Comment by HannibalRoG** [comment]
Can be closed?

**Comment by ThisMushroom** [comment]
@HannibalRoG Guess, it would be correct to close after linked PR would be finished.
