### ISSUE TITLE
Quête du départ impossible en Voleur Humain

### ISSUE THREAD

**Issue by Synoji** [AshamaneProject/AshamaneCore#397]
**Description:**
La quête nommée "The Deepest Cut" demande de s'exercer au sort "Eviscération" sur des mannequins et d'atteindre le niveau trois, étant niveau 7 j'ai tenté de lancer le sort, cependant en cliquant sur la quête on se rend compte qu'il faut non pas "Eviscération", mais "Percée", un sort de la spécialisation Hors la loi du voleur.

**Usefull Wowhead links:**
http://fr.wowhead.com/spell=2098/percee
http://fr.wowhead.com/spell=196819/evisceration
http://www.wowhead.com/quest=26915/the-deepest-cut

**Comment by STARRHELD** [comment]
On the link it says,
"This quest was marked obsolete by Blizzard and cannot be obtained or completed."

**Comment by Synoji** [comment]
Well, my bad xD
I think they should "remove"the quest

**Comment by Nexon99** [comment]
**Thank you, patch applied successfully !**
