### ISSUE TITLE
[BUG] boss de donjon fourrésombrecoeur

### ISSUE THREAD

**Issue by shaoshaoo** [AshamaneProject/AshamaneCore#405]
**Boss 1 :**
- //

**Boss 2 :** http://fr.wowhead.com/npc=103344/chenecoeur
- impossible de le tuer (id : 103344)
- faction amicale

**Boss3 :**
- //

**Boss 4 :**
- //

**Comment by shaoshaoo** [comment]
Les oeufs juste avant le boss Dresaron nous agro continuellement (nous lache pas meme si ils sont mort)

**Comment by shaoshaoo** [comment]
Son attaque Rugissement sismique (ne projette pas une pluie de caillou) et Courant descendant ne nous fait pas reculer dans les œufs ) ne fonctionne pas

http://fr.wowhead.com/npc=99200/dresaron

**Comment by shaoshaoo** [comment]
Cauchemar Eveiller ne Réduit pas au silence.

http://fr.wowhead.com/npc=99192/ombre-de-xavius#drops

**Comment by shaoshaoo** [comment]
Et le Donjon ne loot sur aucun boss

**Comment by Nexon99** [comment]
Merci pour le report ! J'ai mis la présentation à jour, et l'as mettrais à jour prochainement pour ajouter d'autres bugs.

**Comment by shaoshaoo** [comment]
il n'y a plus aucun trash ni boss dans le donjon (n'importe quel mode)

**Comment by shaoshaoo** [comment]
le troisieme boss ne loot pas en hm

**Comment by shaoshaoo** [comment]
Le quatrieme non plus
