### ISSUE TITLE
[BUG] PNJ pour faire les recherches d'arme

### ISSUE THREAD

**Issue by shaoshaoo** [AshamaneProject/AshamaneCore#406]
**Description:**
Impossible de rendre la quete [Hitting the Books] ou même d'apprendre les recherches

**Usefull Wowhead links:**
http://www.wowhead.com/quest=43881/hitting-the-books

**Comment by Nexon99** [comment]
**Cette quête a été marquée obsolète par Blizzard et ne peut être obtenue ou complétée.**
