### ISSUE TITLE
Client/Crash the client run out of memory in especific zone.

### ISSUE THREAD

**Issue by HannibalRoG** [AshamaneProject/AshamaneCore#411]
**Description:**
Go to Orgrimmar, when going out through the main entrance to the Durotar turn right and go to the river, there are elementals in combat, in that place the client crashes 90% of times.

Console show:
AreaTrigger (spellMiscId 7420) not created. Invalid areatrigger miscid (7420)
AreaTrigger (spellMiscId 5250) not created. Invalid areatrigger miscid (5250)
AreaTrigger (spellMiscId 5258) not created. Invalid areatrigger miscid (5258)

Game client stops responding.
No more memory.
Maybe, there are other zones with same problems.

**Usefull Wowhead links:**

**Comment by streetrat** [comment]
check the creatures' emotes, its a stupid bug, but some invalid emote states can make the client crash

**Comment by HannibalRoG** [comment]
Closed via https://github.com/AshamaneProject/AshamaneCore/commit/38a4043e7ea148f147eeb7157e7dacbcb6e9b7fc
