### ISSUE TITLE
spell demo destru bug

### ISSUE THREAD

**Issue by valeriouss** [AshamaneProject/AshamaneCore#418]
Éclats d'âme ne fonctionne pas
Faille dimentionnelle pas script
Grimoire de suprématie ne fonctionne pas
tout les spells des pets ne fonctionne pas
**Usefull Wowhead links:**
http://fr.wowhead.com/soul-shards
http://fr.wowhead.com/spell=196586/faille-dimensionnelle
http://fr.wowhead.com/spell=152107/grimoire-de-suprematie
http://fr.wowhead.com/npc=416/diablotin#abilities
http://fr.wowhead.com/npc=1860/marcheur-du-vide
http://fr.wowhead.com/npc=1863/succube
http://fr.wowhead.com/npc=417/chasseur-corrompu
http://fr.wowhead.com/npc=78217/infernal
http://fr.wowhead.com/spell=18540/invocation-de-garde-funeste

**Comment by Nexon99** [comment]
**Doublon.**
