### ISSUE TITLE
Quest/DB Some factions vendors sell without reputation.

### ISSUE THREAD

**Issue by HannibalRoG** [AshamaneProject/AshamaneCore#423]
**Description:**
Some Quatermaster vendors in capitals sell items without proper reputation.

Some NPCs offer all the daily quests, they should offer only one random each day.

Possible fix. The way I found doing it is hiding the item with a condition if you do not have the necessary reputation.

-- QuarterMaster factions vendors
DELETE FROM `conditions` WHERE `SourceGroup` IN (50323, 50488, 50477, 50309, 50308, 49877, 50305, 50307, 50306, 50483, 50484, 50304);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(23, 50323, 67525, 0, 0, 5, 0, 1133, 64, 0, 0, 0, 0, '', ''),
(23, 50488, 67533, 0, 0, 5, 0, 76, 64, 0, 0, 0, 0, '', ''),
(23, 50477, 67536, 0, 0, 5, 0, 530, 64, 0, 0, 0, 0, '', ''),
(23, 50309, 67528, 0, 0, 5, 0, 47, 64, 0, 0, 0, 0, '', ''),
(23, 50308, 67530, 0, 0, 5, 0, 54, 64, 0, 0, 0, 0, '', ''),
(23, 49877, 67531, 0, 0, 5, 0, 72, 64, 0, 0, 0, 0, '', ''),
(23, 50305, 67526, 0, 0, 5, 0, 69, 64, 0, 0, 0, 0, '', ''),
(23, 50307, 67532, 0, 0, 5, 0, 1134, 64, 0, 0, 0, 0, '', ''),
(23, 50306, 67527, 0, 0, 5, 0, 930, 64, 0, 0, 0, 0, '', ''),
(23, 50483, 67534, 0, 0, 5, 0, 81, 64, 0, 0, 0, 0, '', ''),
(23, 50484, 67525, 0, 0, 5, 0, 1133, 64, 0, 0, 0, 0, '', ''),
(23, 50304, 67529, 0, 0, 5, 0, 68, 64, 0, 0, 0, 0, '', '');

-- Set only one daily quest from some trainers, add some missing pools
UPDATE `pool_template` SET `max_limit`=1, `description`='Catherine Leland - Daily Quests' WHERE `entry`=369;
UPDATE `pool_template` SET `max_limit`=1 WHERE `entry`=368;
DELETE FROM `pool_quest` WHERE `entry` IN (26543, 26556, 26557, 26572, 26588);
INSERT INTO `pool_quest` (`entry`, `pool_entry`, `description`) VALUES 
(26543, 347, 'Clammy Hands'),
(26556, 347, 'No Dumping Allowed'),
(26557, 347, 'A Staggering Effort'),
(26572, 347, 'A Golden Opportunity'),
(26588, 347, 'A Furious Catch');
UPDATE `pool_template` SET `description`='Razgar Daily quests' WHERE `entry`=347;

DELETE FROM `pool_quest` WHERE `entry` IN (29345, 29346, 29348, 29349, 29354);
INSERT INTO `pool_quest` (`entry`, `pool_entry`, `description`) VALUES 
(29345, 346, 'Pond Predators'),
(29346, 346, 'The Rings the Thing'),
(29348, 346, 'The Race to Restock'),
(29349, 346, 'Craving Crayfish'),
(29354, 346, 'Shiny Baubles');
UPDATE `pool_template` SET `description`='Kah Mistrunner Daily quests' WHERE `entry`=346;

**Comment by Nexon99** [comment]
**Thank you for your help, I add it to my patch update (I added your name)**

**Comment by flumby** [comment]
Very nice effort and a good contribution.

**Comment by HannibalRoG** [comment]
This can be closed, fix already commited.
