### ISSUE TITLE
Bug quétes début des humains

### ISSUE THREAD

**Issue by Astrozia** [AshamaneProject/AshamaneCore#43]
bonjour en créant mon personnage (une humaine paladin) j'ai vu que j'avais acces a la quete "paume du tigre" des moines dans la quel il faut s'entrainer a utiliser paume du tigre ors, je suis paladin ^^

ps: vraiment désolé pour les fautes d'hortographes

**Comment by Oldarorn** [comment]
La quête étant obsolète elle sera désactivée. Merci du rapport, il était temps de la fermer :trollface:
