### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by vinin80** [AshamaneProject/AshamaneCore#435]
I have problem with login on server. I get disconnect when i try login. In console i have only this. 

dep/gsoap/stdsoap2.cpp(8876): malloc() = 0x7f2be781d1c0 not freed (memory leak or forgot to call soap_end()?)

Anyone have this problem?

OS: Linux

**Comment by benas80** [comment]
I think we need to check if 'p' is malloc before, if yes 'p' pointer should be free before next malloc.
(i dont have this error, are You trying to connect via SOAP?)

**Comment by vinin80** [comment]
No

**Comment by vinin80** [comment]
/root/Desktop/legion/repo/dep/gsoap/stdsoap2.cpp(8876): malloc() = 0x7fc07a01d1c0 not freed (memory leak or forgot to call soap_end()?)
/root/Desktop/legion/repo/dep/gsoap/stdsoap2.cpp(8876): malloc() = 0x7fc07a07e180 not freed (memory leak or forgot to call soap_end()?)

**Comment by benas80** [comment]
gsoap directories are the same this and trinity, no differents in code.

**Comment by vinin80** [comment]
Anyone can fix this?

**Comment by vinin80** [comment]
WorldSocket::HandleAuthSession: Authentication failed for account: 1 ('1#1') address:

**Comment by Traesh** [comment]
The log (malloc stuff) have to be fixed, but it does not prevent login. You should check your config

**Comment by arkangel2k4** [comment]
Did you find a fix for this? Having the same issue in latest build - after updating to 7.3.5 client - 

core/dep/gsoap/stdsoap2.cpp(8876): malloc() = 0x7f001b01d180 not free d (memory leak or forgot to call soap_end()?)

**Comment by Bodeguero** [comment]
How to fix its error:

WorldSocket::HandleAuthSession: Authentication failed for account: 1 ('1#1') address: 127.0.0.1
