### ISSUE TITLE
DB/GY Add graveyard for Suramar

### ISSUE THREAD

**Issue by HannibalRoG** [AshamaneProject/AshamaneCore#449]
**Description:**
Add graveyard zone for Suramar map

**Usefull Wowhead links:**
[Graveyard_zone_Suramar.zip](https://github.com/AshamaneProject/AshamaneCore/files/1691012/Graveyard_zone_Suramar.zip)

**Comment by Nexon99** [comment]
**Soon add in update patch 0.3 👍**
