### ISSUE TITLE
[ZONE] Turtle isles use 100% processor

### ISSUE THREAD

**Issue by remamakiller** [AshamaneProject/AshamaneCore#450]
Good day people:
I found, that when I enter the server and I want to start doing quest, the panda, the pc, where I have the server, starts working, 100% hard drive, it is locked and must be restarted, so that it works again
It is not because of the pc, because with the other characters, that does not happen, it is only when I enter with the panda. on turtle island.
On other maps, you can play quietly, without anything happening
But do not think about the error
From already thank you very much

**Comment by d3athbl0w** [comment]
I Can confirm this.

**Comment by HannibalRoG** [comment]
Probably the same of #421

**Comment by Traesh** [comment]
Closed by efd214a3909a8a4df24753ee8f5ebbfe76e7c6a9
