### ISSUE TITLE
Garrison teleport

### ISSUE THREAD

**Issue by darkmord1991** [AshamaneProject/AshamaneCore#463]
**Description:**
When you port to garrison, you change the phase, so you cant see npcs outside anymore.
You have to port somewhere to get it back working

**Usefull Wowhead links:**

**Comment by Nexon99** [comment]
**We are aware of this problem. A fix is ​​coming.**

**Comment by Traesh** [comment]
Closed by cca531b2a8403aa0f62c443dc13e4da44e019f7c
