### ISSUE TITLE
Spells/Priest bugs founds

### ISSUE THREAD

**Issue by d3athbl0w** [AshamaneProject/AshamaneCore#465]
1) When entering the angel's form, it is impossible to heal
http://www.wowhead.com/spell=20711/spirit-of-redemption

https://cdn.discordapp.com/attachments/404409448229109770/405495475995934720/unknown.png

2) http://www.wowhead.com/spell=47540 -----  you hurt yourself when you use it on an enemy
3) http://www.wowhead.com/spell=205369 ------- No stun
4) http://www.wowhead.com/spell=123254 ----- it is always active
5) http://www.wowhead.com/spell=88625 ----- No stun
6) http://www.wowhead.com/spell=63733 ---- Does not reduce the cooldown
7) http://www.wowhead.com/spell=33076 --- No can buff
8) http://www.wowhead.com/spell=234702 ---- no make area damage
9) http://www.wowhead.com/spell=62618 ----- No reduce the damage
10) http://www.wowhead.com/spell=152118 --- does not absorb the damage
11) Sometimes in shadow You can not throw spells.

**Comment by remamakiller** [comment]
I can confirm this

**Comment by Kerplunk777** [comment]
I can confirm this

**Comment by Devilfloh** [comment]
I'm working on it

**Comment by HannibalRoG** [comment]
Moved to #673
