### ISSUE TITLE
Error when applying database last update

### ISSUE THREAD

**Issue by GrapsZ** [AshamaneProject/AshamaneCore#482]
**Description:**
ERROR 1054 (42S22) at line 13863: Unknown column 'OptionID' in 'where clause'

Applying of file 'C:/Sources/sql/ashamane/world/2018_02_10_01_world_argus.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.

It's not possible to launch the server whith this error.

**Usefull Wowhead links:**

**Comment by Jinnaii** [comment]
OptionID needs to be changed to OptionIndex like here : 

[3a91e44](https://github.com/Jinnaii/AshamaneSenJin/commit/3a91e448c948411d42e479fc91693abf91d76d6f)

**Comment by RenegadeLegionWow** [comment]
^^ this is correct, i thought perhaps ashamane caught on to that during the latest merge to trinity, I hadn't checked because i already made this change to the Dark-iCE repo

**Comment by RenegadeLegionWow** [comment]
DELETE FROM `gossip_menu_option` WHERE (`MenuId`=83 AND `OptionID`=0) OR (`MenuId`=21509 AND `OptionID`=0) OR (`MenuId`=9821 AND `OptionID`=2) OR (`MenuId`=9821 AND `OptionID`=1) OR (`MenuId`=21462 AND `OptionID`=2) OR (`MenuId`=21462 AND `OptionID`=0);
INSERT INTO `gossip_menu_option` (`MenuId`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextId`) VALUES
(83, 0, 4, 'Return me to life.', 2547),
(21509, 0, 1, 'I want to browse your goods.', 3370),
(9821, 2, 0, 'I''d like to heal and revive my battle pets.', 64115),
(9821, 1, 1, 'I''m looking for a lost companion.', 56613),
(21462, 2, 1, 'Let me browse your goods.', 0), -- OptionBroadcastTextID: 2823 - 7509 - 8097
(21462, 0, 5, 'Make this inn your home.', 2822);

needs to be changed to : 

DELETE FROM `gossip_menu_option` WHERE (`MenuId`=83 AND `OptionIndex`=0) OR (`MenuId`=21509 AND `OptionIndex`=0) OR (`MenuId`=9821 AND `OptionIndex`=2) OR (`MenuId`=9821 AND `OptionIndex`=1) OR (`MenuId`=21462 AND `OptionIndex`=2) OR (`MenuId`=21462 AND `OptionIndex`=0);
INSERT INTO `gossip_menu_option` (`MenuId`, `OptionIndex`, `OptionIcon`, `OptionText`, `OptionBroadcastTextId`) VALUES
(83, 0, 4, 'Return me to life.', 2547),
(21509, 0, 1, 'I want to browse your goods.', 3370),
(9821, 2, 0, 'I''d like to heal and revive my battle pets.', 64115),
(9821, 1, 1, 'I''m looking for a lost companion.', 56613),
(21462, 2, 1, 'Let me browse your goods.', 0), -- OptionBroadcastTextID: 2823 - 7509 - 8097
(21462, 0, 5, 'Make this inn your home.', 2822);

**Comment by RenegadeLegionWow** [comment]
fixed version below
[2018_02_10_01_world_argus.zip](https://github.com/AshamaneProject/AshamaneCore/files/1722084/2018_02_10_01_world_argus.zip)
