### ISSUE TITLE
Some crashlogs

### ISSUE THREAD

**Issue by darkmord1991** [AshamaneProject/AshamaneCore#485]
**Description:**
I used it with darkice source, because of the custom scripts
Maybe I can help you with that.
Core was compiled with release with debug info
[9c235112affa_worldserver.exe_[13-2_21-7-6].zip](https://github.com/AshamaneProject/AshamaneCore/files/1723531/9c235112affa_worldserver.exe_.13-2_21-7-6.zip)

**Usefull Wowhead links:**

**Comment by RenegadeLegionWow** [comment]
its not our custom scripts

**Comment by Traesh** [comment]
Too late @RenegadeLegionWow, already fixed :p

But he didn't say it was your custom script fault, just that he used darkice because of them

**Comment by darkmord1991** [comment]
Thanks, it was just an information from my side :P so that you dont have to wonder
