### ISSUE TITLE
New build 7.3.5

### ISSUE THREAD

**Issue by LuigiElleBalotta** [AshamaneProject/AshamaneCore#486]
**Description:**
Are you going to update the core to the latest build ( 7.3.5 25996 ) ?

**Usefull Wowhead links:**

**Comment by RenegadeLegionWow** [comment]
its not available for core yet, trinitycore doesnt support it yet.
@Traesh you should just close this one, its not an issue its a question

**Comment by Traesh** [comment]
I'm waiting for TC to do it, they will do it so there is no reason for me to loose time on that ATM
