### ISSUE TITLE
Quête "elegant rune" Vallée des frigères

### ISSUE THREAD

**Issue by Astrozia** [AshamaneProject/AshamaneCore#49]
"elegant rune" quête donné par Jona Troupefer à courbenclume pas faisable
ID: 31150

**Comment by Cearon** [comment]
Bonjour, je complète le sujet : 

Je suis nain chasseur et le PNJ me propose la quête...   Pas normal...   La quête est en anglais au passage...  Je vous donne le lien Fr de WowHead : http://fr.wowhead.com/quest=31150/rune-elegante

**Comment by Oldarorn** [comment]
Le PNJ manquant a été ajouté, bientôt en jeu merci du rapport :)
