### ISSUE TITLE
Conteneur Argus

### ISSUE THREAD

**Issue by PandaChinois** [AshamaneProject/AshamaneCore#497]
[conteneur Argus.zip](https://github.com/AshamaneProject/AshamaneCore/files/1733977/conteneur.Argus.zip)

**Comment by Nexon99** [comment]
**Pour proposer des patchs correctif => https://github.com/AshamaneProject/AshamaneCore/pulls 

Merci !**

**Comment by Traesh** [comment]
@Nexon99 Le SQL peut effectivement être proposé en issue et non en PR

**Comment by PandaChinois** [comment]
Et bah je vous laisses choisir ou je doit les mettre la prochaine fois ^^
