### ISSUE TITLE
Talent/Spell for Shaman not working

### ISSUE THREAD

**Issue by HannibalRoG** [AshamaneProject/AshamaneCore#501]
- [x] Hot Hand ID:201900 - Infinite times until time runs out can be used, When it should finish when you throw next Lava Lash
- [x] Gust of Wind ID:192036 - Jumping toward in front no toward back
- [x] Wind Rush Totem ID:192077 - Complete broken
- [x] Rainfall ID:215864 - Complete broken
- [x] Totem Mastery - All broken
- [x] Earthen Rage ID:170374 - Complete broken
- [x] Undulation ID:200071 - Complete broken
- [x] Elemental Blast ID:117014 - He makes damage but no increase critical rate, haste or mastery
- [x] Earthquake, ID: 61882 not working at all
- [x] Chain Lightning, ID: 188443 not generate maelstorm
- [x] Elemental Focus, ID: 16164 it activate without crit
- [x] Tidal wave id 51564 not working properly
- [x] Visual bug with totems, only one cube appears without texture
- [x] Earth Shock ID: 8042 no visual effect, spell is not causing nature damage based on maelstrom spent.
- [x] Lava Surge ID: 77756 dont activate
- [x] Earth Elemental ID: 198103 not working
- [x] Fire Elemental ID: 198067 not working
- [x] Healing rain ID: 73920 Not work and no visual effect.
- [x] Healing Surge [spellID:188070] spell is not becoming instantly when 20 maelstrom or more is available.

**Comment by Ulduar** [comment]
Received not handled opcode [CMSG_UPDATE_SPELL_VISUAL 0x328F (xxxxx)] from [Player: Void GUID Full: 0x0800040000000000000000000000002B Type: Player Entry: 0 Low: 43, Account: x]
Sorry, but maybe this reason for this issue?

**Comment by HannibalRoG** [comment]
@Ulduar for what issue exactly.

**Comment by Ulduar** [comment]
@HannibalRoG 
Sorry, for visual display spell's.

```SQL
Healing rain ID: 73920 Not work and no visual effect.
```
no visual effect. For this case.

**Comment by Ulduar** [comment]
http://www.wowhead.com/spell=212461
http://www.wowhead.com/spell=212563
Not display visual effect. Also, i don't know why.

**Comment by Traesh** [comment]
Sniffs

**Comment by Ulduar** [comment]
``` SQL
AreaTrigger (spellMiscId 8812) not created. Invalid areatrigger miscid (8812) - spell id 227789 
AreaTrigger (spellMiscId 10024) not created. Invalid areatrigger miscid (10024) - spell id 239256
AreaTrigger (spellMiscId 10033) not created. Invalid areatrigger miscid (10033) - spell id 239267
```
Thanks @Traesh for explanation. Tell me please about 8812, 100024 and 10033

**Comment by Traesh** [comment]
@Ulduar I assume those are all from Return to Karazhan, you should sniff the instance if you want the areatriggers data.

Also please create another issue to discuss this topic as this one is specifically about Shaman spells

**Comment by Ulduar** [comment]
``` CPP
I assume those are all from Return to Karazhan, you should sniff the instance if you want the areatriggers data.
```
227789 - Sacred Ground - Maiden of Virtue.
239256 and 239267 - Kil'jaeden heroic and mythic.
Unfortunately, I have not played on the official server for a long time, so there is no way to get data

``` SQL
Also please create another issue to discuss this topic as this one is specifically about Shaman spells
```
Yes, sorry.

**Comment by Ulduar** [comment]
@Traesh 
``` CPP
I assume those are all from Return to Karazhan, you should sniff the instance if you want the areatriggers data.
```
227789 - Sacred Ground - Maiden of Virtue.
239256 and 239267 - Kil'jaeden heroic and mythic.
Unfortunately, I have not played on the official server for a long time, so there is no way to get data

``` SQL
Also please create another issue to discuss this topic as this one is specifically about Shaman spells
```
Yes, sorry.

**Comment by HannibalRoG** [comment]
More here #688 in french

**Comment by cooler-SAI** [comment]
good job ^_^
