### ISSUE TITLE
Talent/Spell for Druid not working

### ISSUE THREAD

**Issue by HannibalRoG** [AshamaneProject/AshamaneCore#508]
- [x] Talent Blessing of the Ancients ID 202360 Not working at all.
- [x] Ysera´s Gift [spellID: 145108] in Restoration Affinity [spellID: 197492] talent heal you but not heal party memeber when your live is full.
- [x] Starlord talent [spellID: 202345] not working at all.

**Comment by einekuhmachtmuh** [comment]
There's a new BUG
<ul class="contains-task-list">
<li class="task-list-item"><input checked="" class="task-list-item-checkbox" disabled="" id="" type="checkbox">new-moon ID 202767(a artifact spell)it should empowers New Moon to become Half Moon(ID 202768) then empowers  itself to full-moon( ID 202771)</li>
 </ul>
