### ISSUE TITLE
Missing Modelids in Creature_template

### ISSUE THREAD

**Issue by Neredun** [AshamaneProject/AshamaneCore#509]
**Description:**
They are 7052 in the table who don't have any modelid1-4, so the worldserver don't load them.

Afortunately i was able to put the correct models into them.

[Creature Template Missing Modelids Fixed.zip](https://github.com/AshamaneProject/AshamaneCore/files/1738608/Creature.Template.Missing.Modelids.Fixed.zip)

**Comment by HannibalRoG** [comment]
There is a lot of model data in your sql that not exist in db2.

**Comment by Neredun** [comment]
Well, most of the models are picked from TC database, only the last 218 Rows which are displayids from Wowhead

**Comment by Neredun** [comment]
i don't know if it's the error that you were referring, but i found "No model data exist for..." errors in DBlogs after a while. I did a fast cheking in TC and that model have data in Creature_model_info (at least for displayid, not for bounding radius or combatreach), so i just inserted it and i didn't recive a error of Non-existing model (at least for creature_model_info and for the ones i put) i think that could be the problem. Also i found creatures with wrong displayids (and that models were applied in model_info, were they gave errors about non-existing model) so i added that other fix here (i don't know if i should but i though they were related)
[Model Info.zip](https://github.com/AshamaneProject/AshamaneCore/files/1739525/Model.Info.zip)
