### ISSUE TITLE
Cant log in to account

### ISSUE THREAD

**Issue by Orangs** [AshamaneProject/AshamaneCore#512]
I have updated core,database to lastest version. Client is updated to 7.3.5 (25996)
When i trying to log in to my account on my server, i have been disconected when client trying to display character list and world server give me this issue.

Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BB (14011)] from [Player: Account: 26]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36BA (14010)] from [Player: Account: 26]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F4 (14068)] from [Player: Account: 26]
Segmentation fault

And after this, worldserver dropped. Any ideas how to fix this issue?

**Comment by RenegadeLegionWow** [comment]
is this *nix or windows? i ask because i am not having that issue under windows.. maybe pull a new revision?

**Comment by ProtektorDD** [comment]
We are using linux and we still didnt fix the problem..

These things happen randomly when we creating character or when we are joining server or when we joined to server and start doing anything

[WorldserverCrash.txt](https://github.com/AshamaneProject/AshamaneCore/files/1743417/WorldserverCrash.txt)
![crash](https://user-images.githubusercontent.com/36415831/36471841-329930fe-16f0-11e8-93c0-09771056652b.JPG)

**Comment by ProtektorDD** [comment]
You can close this issue cuz we solved that problem by fixing ram memory which caused this problem on our side...
