### ISSUE TITLE
Crashlog 

### ISSUE THREAD

**Issue by Thordekk** [AshamaneProject/AshamaneCore#515]
Can´t start server
[Server.log](https://github.com/AshamaneProject/AshamaneCore/files/1741694/Server.log)

**Usefull Wowhead links:**

**Comment by darkmord1991** [comment]
>> The file '2017_08_23_00_hotfixes.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_07_04_00_hotfixes.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_06_14_00_hotfixes.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_04_19_01_hotfixes.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_05_14_00_hotfixes.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_05_07_00_hotfixes.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_08_24_00_hotfixes.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_06_04_00_hotfixes.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_07_02_00_hotfixes.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_07_27_00_hotfixes.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_09_15_00_hotfixes.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_11_05_00_hotfixes.sql' was applied to the database, but is missing in your update directory now!
