### ISSUE TITLE
Warrior arm 'spell Victory rush'

### ISSUE THREAD

**Issue by father0000** [AshamaneProject/AshamaneCore#518]
**Description:**
Victory rush is not activating after killing boss

**Usefull Wowhead links:**

http://www.wowhead.com/spell=34428/victory-rush

**Comment by argumumble** [comment]
What boss did you kill? And at what level?

**Comment by father0000** [comment]
Victory rush  doesn't work with any boss

**Comment by LeRutY** [comment]
You can close it yourself.

**Comment by Traesh** [comment]
Easiest issue ever
