### ISSUE TITLE
Monture raciale, race alliés

### ISSUE THREAD

**Issue by PandaChinois** [AshamaneProject/AshamaneCore#522]
Elfe du vide: http://fr.wowhead.com/item=156486/trotteur-du-vide-astral
Sacrenuit: http://fr.wowhead.com/item=156487/sabre-de-mana-sacrenuit
Tauren haut-Roc: http://fr.wowhead.com/item=155662/sabot-tonnerre-de-haut-roc
Draenei sancteforge: http://fr.wowhead.com/item=155656/gangrebroyeur-sancteforge

**Comment by Traesh** [comment]
Comment les obtient-on ? Elles sont fournies avec le personnage ?

**Comment by Nexon99** [comment]
**Les montures s'obtiennent après avoir fait la suite de quête (scénario) de chaque race alliées.**

=> http://fr.wowhead.com/achievement=12244/races-alliees-sacrenuit

**Comment by Traesh** [comment]
Closed by 7b8e142a220d96a6595d071c013796ffff3c587d
