### ISSUE TITLE
Warlock Unstable affliction spell

### ISSUE THREAD

**Issue by Vertex2187** [AshamaneProject/AshamaneCore#523]
After being cast (casttimer is working) the enemy does not recieve the DOT

http://www.wowhead.com/spell=30108/unstable-affliction

**Comment by darkmord1991** [comment]
https://github.com/AshamaneProject/AshamaneCore/commit/58a6d9361b69b9e9deea8532ed4b3a7fffc7ebb6

**Comment by aeroashamane** [comment]
Ce problème a était régler . 

Traesh - Aujourd'hui à 00:47
Dev report : 

Warlock
- Fix of Agony
- Fix of Phantomatic Singularity
- Fix Unstable Affliction
