### ISSUE TITLE
aire de krasus

### ISSUE THREAD

**Issue by Astrozia** [AshamaneProject/AshamaneCore#525]
monstre invisible, insiblable qui fait tres mal surla plateforme proche de kadgar

**Comment by Nexon99** [comment]
Bug connu, je n’arrive pas obtenir son id pour la supprimer, mais je ne désespère pas. :p

**Comment by Astrozia** [comment]
ok np ^^

**Comment by aeroashamane** [comment]
Ce problème a était régler depuis quelque temps.
