### ISSUE TITLE
Battlepay store

### ISSUE THREAD

**Issue by qyh214** [AshamaneProject/AshamaneCore#529]
**Description:**
Maybe it's not planned or very low, but it's really looking forward to it.

**Usefull links:**
https://github.com/TrinityCore/TrinityCore/pull/15631/

**Comment by Nexon99** [comment]
Our project was not primarily created to meet your expectations regarding the creation of a Legion server. If the shop were to be functional later, it would not be public release. 

Thanks, have a good day.

**Comment by Livux** [comment]
Would love to see that!
