### ISSUE TITLE
Khadgar's version of Shattrath Unupdated

### ISSUE THREAD

**Issue by Neredun** [AshamaneProject/AshamaneCore#531]
**Description:**
The Khadgar NPC in Shattrath still have his old model and weapon. This should fix that

```
UPDATE creature_template SET modelid1 = 56765 WHERE entry = 18166;

UPDATE creature_equip_template SET ItemID1 = 28067 WHERE CreatureID = 18166;
```

**Usefull Wowhead links:**
http://www.wowhead.com/npc=18166

**Comment by aeroashamane** [comment]
Hello, no need to change his(her,its) weapon at present thus I close the ticket and we shall once open him(it) the most urgent makes

**Comment by Neredun** [comment]
I already gave the fix, so the work is already done. This is just visual, so it will never be urgent, to be honest, but it's nice to have it.

**Comment by Traesh** [comment]
Don't know why @aeroashamane closed this, will talk with him.

Still, this issue can stay closed as Khadgar was updated with all outland resniff (6e1e88c9f94960e0652d7c40e56f880f979f677e)
