### ISSUE TITLE
Téléportation Dalaran ( LEvel 100 )

### ISSUE THREAD

**Issue by GrapsZ** [AshamaneProject/AshamaneCore#533]
**Description:**
Bonjour,
Tout d'abord merci pour votre taf les gars. Vous faites un travail remarquable. J'ai pu cependant constater qu'il est impossible de spawn à Dalaran, via le portail de hurlevent lorsque l'on est level 100 et que Kadgar nous donne la quête.
On se téléporte bien dans dalaran au dessus de Karazhan, mais l'on passe " sous map ". 

Avec un coup de fly on peut se mettre au bon endroit, sinon c'est une sorte de boucle. On tombe, on remonte, on retombe, etc...

Je ne sais pas si ça vous a déjà été rapporté.

**Usefull Wowhead links:**

**Comment by Dreda59** [comment]
This was fixed a couple of days ago

**Comment by aeroashamane** [comment]
Ce problème a était régler depuis quelque temps.
