### ISSUE TITLE
Crash worldserver after compile

### ISSUE THREAD

**Issue by Thordekk** [AshamaneProject/AshamaneCore#535]
**Description:**
Crash worldserver after compile please help.
Could not prepare statements of the World database, see log for details.
[Server.log](https://github.com/AshamaneProject/AshamaneCore/files/1750256/Server.log)
[DBErrors.log](https://github.com/AshamaneProject/AshamaneCore/files/1750257/DBErrors.log)

**Usefull Wowhead links:**

**Comment by Traesh** [comment]
Which database did you use ?

**Comment by Thordekk** [comment]
sorry wrong database
