### ISSUE TITLE
Nomi Dalaran Légion

### ISSUE THREAD

**Issue by PandaChinois** [AshamaneProject/AshamaneCore#542]
PNJ non présent
[Nomi.txt](https://github.com/AshamaneProject/AshamaneCore/files/1754606/Nomi.txt)

**Comment by Traesh** [comment]
Les loots de ces deux PNJs sont déjà présents dans la DB

Le wowheadparser ne peut que récupérer des infos sur wowhead, il ne génère pas le SQL requis pour les spawn en jeu ^^
