### ISSUE TITLE
All DK and most of Warlock pets are bugged

### ISSUE THREAD

**Issue by Ahrimansiah** [AshamaneProject/AshamaneCore#545]
**Description:**
All DK and most of Warlock pets are bugged and only do 1-4 damage,

**Usefull Wowhead links:**
Ghoul from raise dead
http://www.wowhead.com/spell=46584/raise-dead
Summoned gargoyle
http://www.wowhead.com/spell=49206/summon-gargoyle
Altered ghoul from transformation
http://www.wowhead.com/spell=63560/dark-transformation
Ghouls from army of dead
http://www.wowhead.com/spell=42650/army-of-the-dead
Zombies from reanimation
http://www.wowhead.com/spell=210128/reanimation
http://www.wowhead.com/spell=207349/dark-arbiter
http://www.wowhead.com/spell=207313/sludge-belcher

Same goes for all warlock pets except Void walker, all the rest are bugged

**Comment by cooler-SAI** [comment]
fixed
