### ISSUE TITLE
Shaman/Totems - model is missing

### ISSUE THREAD

**Issue by bySenom** [AshamaneProject/AshamaneCore#549]
**Description:**
I do not know if someone has already said it but the totems are not displayed correctly / model is missing sry for my bad english :P

**Usefull Wowhead links:**
- [x] http://de.wowhead.com/spell=15786/totem-der-erdbindung : model is missing
- [x]  http://de.wowhead.com/spell=98008/totem-der-geistverbindung : model is missing
- [x] http://de.wowhead.com/spell=5394/totem-des-heilenden-flusses : model is missing
- [x]  http://de.wowhead.com/spell=192058/totem-der-blitzwoge : model is missing
- [x] http://de.wowhead.com/spell=157153/totem-des-wolkenbruchs : (Talent) - model is missing
- [x] http://de.wowhead.com/spell=198838/totem-des-irdenen-schilds : (Talent) - model is missing
- [x] http://de.wowhead.com/spell=207399/totem-des-schutzes-der-ahnen : (Talent) - model is missing
- [x] http://de.wowhead.com/spell=51485/totem-des-erdgriffs : (Talent) - model is missing
- [x] http://de.wowhead.com/spell=196932/voodoototem : (Talent) - model is missing
- [x] http://de.wowhead.com/spell=192077/totem-des-windsturms : (Talent) - model is missing

**Comment by leviathonbeast** [comment]
this will be fixed soon. its a PR on Trinity.

**Comment by HannibalRoG** [comment]
Already reported here #501 and fix it.
