### ISSUE TITLE
Guild vault add items - opcode missing

### ISSUE THREAD

**Issue by darkmord1991** [AshamaneProject/AshamaneCore#552]
**Description:**
No defined handler for opcode [UNKNOWN OPCODE 0x34BB (13499)] sent by [Player: Lightmord GUID Full: 0x08000C000000000000000000000004B8 Type: Player Entry: 0 Low: 1208, Account: 11244504]

So you can not add items to the guild vault
**Usefull Wowhead links:**

**Comment by Szone** [comment]
Confirm.

**Comment by Traesh** [comment]
Fixed by ff0b4027007a60b0784902e60709c72d2101084f
