### ISSUE TITLE
Warlock Class hall doesn't work (Urgent)

### ISSUE THREAD

**Issue by alejous629** [AshamaneProject/AshamaneCore#570]
**Description:**
When you use the portal to the Warlock class hall it teleports you to a zone in stormheim in the air so you fall to your dead

**Usefull Wowhead links:**
http://www.wowhead.com/dreadscar-rift (class hall)
http://wow.zamimg.com/uploads/screenshots/normal/561718.jpg (photo of the portal)

**Comment by HannibalRoG** [comment]
Closed in https://github.com/AshamaneProject/AshamaneCore/commit/8ad34e2e94783f09b6b5a63ee6adfa5e4746cd12
