### ISSUE TITLE
Dk can't continue chainquest

### ISSUE THREAD

**Issue by alejous629** [AshamaneProject/AshamaneCore#588]
**Description:**
The quest Death comes from on high can't be complete because you can't analyze the buildings, this makes that a dk player can't do any other quest after this meaning you are stuck in this zone

**Usefull Wowhead links:**
http://www.wowhead.com/quest=12641/death-comes-from-on-high

**Comment by Traesh** [comment]
Fixed by c20ad8672ee12464375afb89df27dd7faeaff104
