### ISSUE TITLE
Chest from Emissary world quest

### ISSUE THREAD

**Issue by alejous629** [AshamaneProject/AshamaneCore#589]
**Description:**
Once you do 4 world quest of any faction you are able to do a quest that rewards you with a chest and artifact power, when you try to open the chest, the quest does nothing.

**Usefull Wowhead links:**
http://www.wowhead.com/item=137561
http://www.wowhead.com/item=137563
http://www.wowhead.com/item=137560
http://www.wowhead.com/item=137565
http://www.wowhead.com/item=137564
http://www.wowhead.com/item=137562
http://www.wowhead.com/item=152652
http://www.wowhead.com/item=152650
http://www.wowhead.com/item=152649

**Comment by Traesh** [comment]
Closed by c14d4b5ed31af62f4fc6a657122c7f98169dc209
