### ISSUE TITLE
[Draenor] Alliance Garrison Quest-Chain

### ISSUE THREAD

**Issue by Neredun** [AshamaneProject/AshamaneCore#592]
**Description:**
After take the quest three NPCs of Velen, Yrel and Maraad move normally but they don't mount, don't talk and they "fly" (they only walk and get the z-coords too high) and after reaching to the place you don't recive any killcredit. And without this quest you can't continue and make your garrison (for Alliance only. Horde can get his garrison with his quests)

**Usefull Wowhead links:**
Quest: http://www.wowhead.com/quest=34582
Killcredit: http://www.wowhead.com/npc=79697

**Comment by Neredun** [comment]
I decided to continue the questchain in retail, and i found that you can't complete the next quest "For the Alliance!" Doing click in the banner gives you the killcredit, but Khadgar never open the portal to Stormwind (which npcs like the questender should appear from them. Still they are already here) and you don't recive the second Killcredit.

Quest: http://www.wowhead.com/quest=34583
Missing Killcredit: http://www.wowhead.com/npc=79433

The rest can be completated with no problem. (Still, the Lumbers in Looking for Lumbre never appear after you mark a tree, but the quest can be done with no problem.)

**Comment by Traesh** [comment]
"Finding a Foothold" closed by a9df5f1a45e00ffdb5debdb71c54d17f0b8e26ae

**Comment by Neredun** [comment]
Does this mean that "For the Alliance!" (the next quest that follows Finding a Foothold) is fixed too?
