### ISSUE TITLE
[SQL Patch] Acherus: The Ebon Hold Fixes

### ISSUE THREAD

**Issue by Neredun** [AshamaneProject/AshamaneCore#619]
**Description:**
This Patch includes:
- Two Phase group creations for the NPCs who are in more than one Phasing (i added myself the Rate Selector to Phase group 696 which includes all the phases)
- Fix the Phase IDs for all the creatures in the zone. (which should fix the bug on Death Comes From High, tested in local)
- Fix the Phase IDs for some Gameobjects in the zone.
- Fixes Queststarter and Ender for two quests .
- Fixes Olrun the Battlecaller Modelid listened in Creature and Creature_template. (since the update of the Val'kyr model her model were updated and the old modelid doesn't work anymore)

[Ebon Hold Phasing.zip](https://github.com/AshamaneProject/AshamaneCore/files/1778983/Ebon.Hold.Phasing.zip)

**Comment by Neredun** [comment]
Greetings. I updated some things and added new phases to some gameobject that i missed. Also we managed to test with user ShadowStep and i can confirm that Death Comes From High is fixed with this.
Also i managed to repair the Spirit Healers who also had wrong modelid.

[Ebon Hold Phasing Updated.zip](https://github.com/AshamaneProject/AshamaneCore/files/1783149/Ebon.Hold.Phasing.Updated.zip)

**Comment by Traesh** [comment]
Thanks you very much for this patch

**Comment by Neredun** [comment]
Hi, it's Neredun Again!

I completed more things from this Zone:
-Fixed Acherus Teleporters, now you should be able to use it in all phases
-Fixed Runeforges, now you should be able to use it in all phases.
-Fixed some missing Phases for Gameobjects and some NPCs.
-Fixed some missing creatures in the "Epilogue" Chapter (Normal World) due to bad modelid, also fixed the Acherus teleporters during this phase, they should work now both during the Epilogue Chapter And the post-quests.

With this, finally all should be in order, and they should not present any problem during his application (tested it a few times to be sure)

[More Ebon Hold Phasing.zip](https://github.com/AshamaneProject/AshamaneCore/files/1809050/More.Ebon.Hold.Phasing.zip)
