### ISSUE TITLE
Artifact 3th relic slot

### ISSUE THREAD

**Issue by Danuliz** [AshamaneProject/AshamaneCore#629]
**Description:**
In 7.3.x came artifact 3th slot update + chances to get relic slot even more easyer to get by lvlup 110 and its open. Please update this.  "To make things easier, there is no quest/attunement process for the third relic in Patch 7.3. You simply get it at 110." 

**Usefull Wowhead links:**

http://www.wowhead.com/news=268045/netherlight-crucible-and-relic-customization-in-patch-7-3

**Comment by jcmillions** [comment]
Yes, but to get the 3rd artifact slot you need the bonus ID for it. We'd need to have someone find out each bonus id for each artifact since they're all different and there are 36 artifacts (37 if you include the fishing artifact).

**Comment by Danuliz** [comment]
Is there any id found so far or at least some example of relic id? I can try find and make list if i only know where to look at. Wowhead is not helping and i try it also look into artifact.db2 but there is no luck. ItemBonus.db2 has lots of ids but it takes ages to test every id on the list..

**Comment by jcmillions** [comment]
The only way I found out my Ashbringer bonus ID was by paying for wowhead premium and viewing my character. I believe it was 737

**Comment by Danuliz** [comment]
@jcmillions Don't you worry i'm now in the case! I will report full list of those ids now soon to you when i have done it. :)

**Comment by Danuliz** [comment]
@jcmillions Alright now i have all 36 artifact 3th slots ids and here they are:

Warrior
----------------
Arms = 750

Fury = 751

Protection = 752
---------------
Paladin

Holy = 735

Protection = 736

Retribition = 737
---------------
Death Knight

Blood = 716

Frost = 717

Unholy = 718

---------------
Hunter

Beast Mastery = 726

Marksmanship = 727

Survival = 728
---------------
Shaman

Elemental = 744

Enhancement = 745

Restoration = 746
---------------
Rogue

Assasination = 741

Outlaw = 742

Subtlety = 743
---------------
Demon Hunter

Havoc = 719

Vengeance = 721
---------------
Druid

Balance = 722

Feral = 723

Guardian = 724

Restoration = 725
---------------
Monk

Bremaster = 732

Mistweaver = 733

Windwalker = 734
---------------
Mage

Arcane = 729

Fire = 730

Frost = 731

---------------
Priest

Discipline = 738

Holy = 739

Shadow = 740
---------------
Warlock

Affliction = 747

Demonology = 748

Destruction = 749
----------------

**Comment by Danuliz** [comment]
@jcmillions Now i hope in near updates comes all artifact has 3th relic slot open. :)

**Comment by Traesh** [comment]
Closed by 7ab19c32144c0a331b9fab42cf6a44fa77bb6e8f
