### ISSUE TITLE
Problem with the GM Security Level

### ISSUE THREAD

**Issue by Mistixc** [AshamaneProject/AshamaneCore#630]
**Description:**
I have a problem with the Gm Level Security that I can only put GM level 3 level where I could modify it so I can put it to the Commands at the Gm level that I want this is important and even another question where I can Deactivate so that all Player on my Server come out as GM

**Usefull Wowhead links:**

**Comment by HannibalRoG** [comment]
This is not a [forum](http://forum.ashamane.com/), this is an issue tracker.
