### ISSUE TITLE
DB/SAI: A lot scripts in Database!

### ISSUE THREAD

**Issue by cooler-SAI** [AshamaneProject/AshamaneCore#636]
**Description:**
hey! you'r DB missing a lot of scripts. Have Only around 5500 SAI. with this scripts you will have around 13000 SAI!

https://github.com/MoPSource/MopCore547/tree/master/sql/SmartAI/patch

enjoy....

**Usefull Wowhead links:**
www.wowhead.com

P>S> don't forget use this for Dungeons and Raids:
```sql
UPDATE `smart_scripts` SET `event_flags`='0' WHERE `event_flags`IN (2,6);
UPDATE `smart_scripts` SET `event_flags`='1' WHERE `event_flags`IN (3,7);
```

**Comment by HannibalRoG** [comment]
@cooler-SAI Thanks i already update some from your repo and give you the credits, thanks a lot.
Did you have any for WoD Legion expansion creatures?

**Comment by cooler-SAI** [comment]
@HannibalRoG , nope,really.Only Mop SAI.....

**Comment by HannibalRoG** [comment]
Merged
