### ISSUE TITLE
ubuntu 16.04 compiling

### ISSUE THREAD

**Issue by daxgo** [AshamaneProject/AshamaneCore#641]
hello, friends, i have this error when try to configure 

-- Detected 64-bit platform
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- cotire 1.7.10 loaded.
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found MySQL executable: /usr/bin/mysql
-- Found git binary : /usr/bin/git
-- 
    Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
    Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"

* TrinityCore revision   : unknown 1970-01-01 00:00:00 +0000 (Archived branch)
* TrinityCore buildtype  : RelWithDebInfo

* Install core to        : /usr/local
* Install libraries to   : /usr/local/lib
* Install configs to     : /usr/local/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   program_options
--   iostreams
--   regex
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.8")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindZLIB.cmake:124 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  dep/zlib/CMakeLists.txt:13 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/dayron/Escritorio/AshamaneCore-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/dayron/Escritorio/AshamaneCore-master/build/CMakeFiles/CMakeError.log".

this is not my first time compiling a source of trinity, but is the firs time, that the have this error, HAVING THE LIBRARY installed, i have zlib installed alrready, why this error ???

**Comment by mayorCuba** [comment]
remove the tools Option ,

**Comment by HannibalRoG** [comment]
Ubuntu 16.04 ist supported anymore, you need to use at least 17.10.
