### ISSUE TITLE
World wont startup

### ISSUE THREAD

**Issue by madmax765** [AshamaneProject/AshamaneCore#642]
**Description:**
Well with updates from Commits on Mar 11, 2018 World will not start up, only info i can give is in the log

Using configuration file D:/SingleCore_Legion/spp-legion/Settings/world.conf.
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May 2017)
Using Boost version: 1.65.1
Updating Auth database...
>> Auth database is up-to-date! Containing 20 new and 0 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 15 new and 0 archived updates.
Updating World database...
>> World database is up-to-date! Containing 304 new and 0 archived updates.
Updating Hotfixes database...
>> Hotfixes database is up-to-date! Containing 20 new and 0 archived updates.
Could not prepare statements of the Character database, see log for details.
**Usefull Wowhead links:**

Seems to be something missing in the charater DB

**Comment by leviathonbeast** [comment]
this is not Ashamane you are using SPP. ask there.

**Comment by madmax765** [comment]
Thank you :D
