### ISSUE TITLE
Black Temple : The Illidari Council Crash server

### ISSUE THREAD

**Issue by Kaptain0** [AshamaneProject/AshamaneCore#650]
Description: 
the following bosses of The Illidari Council crash server.
It is possible that it is one of the following bosses, however as they attack all at the same time. 
I can not be sure which is the correct one.

1. Gathios the Shatterer
2. High Nethermancer Zerevor
3. Lady Malande
4. Veras Darkshadow

Usefull Wowhead links: 
http://www.wowhead.com/npc=22949/gathios-the-shatterer
http://www.wowhead.com/npc=22950/high-nethermancer-zerevor
http://www.wowhead.com/npc=22951/lady-malande
http://www.wowhead.com/npc=22952/veras-darkshadow

**Comment by HannibalRoG** [comment]
Why did you close this? solved? @Kaptain0

**Comment by Kaptain0** [comment]
@HannibalRoG nope
