### ISSUE TITLE
Hunter Marksmanship Bugs

### ISSUE THREAD

**Issue by Khell88** [AshamaneProject/AshamaneCore#651]
**Description:**
I´ve been testing the MM Hunter and I´ve notice that the Lock and Load talent is bugged. It applies the effect but when you use Aimed Shot twice the buff remains applied until the time expires.

Steps to reprodice error¨:
1-Create MM Hunter.
2-Select Lock and Load talent.
3-Fire to a practice dummy or a creature with high hp

**Usefull Wowhead links:**

http://www.wowhead.com/spell=194595/lock-and-load

**Comment by HannibalRoG** [comment]
I already added to #502
This can be closed.
