### ISSUE TITLE
Crash log Important

### ISSUE THREAD

**Issue by Mistixc** [AshamaneProject/AshamaneCore#655]
**Description:**
This happens when I raise the Core that begin to Legguerase the User

**Usefull Wowhead links:**

[unknown_worldserver.exe_[14-3_0-7-35].txt](https://github.com/AshamaneProject/AshamaneCore/files/1809700/unknown_worldserver.exe_.14-3_0-7-35.txt)

**Comment by HannibalRoG** [comment]
Do not expect support without a proper hash

**Comment by satanic51** [comment]
esto se va a poner interesante

**Comment by Mistixc** [comment]
Look Hanibal I do not ask you if the crach or you can not close that is not your problem thank you for giving your presence but I do not need you do not have to give your opinion if it is closed or I think the Guil is not called Hanibal
