### ISSUE TITLE
[QUEST] The Arts of a Warrior

### ISSUE THREAD

**Issue by madmax765** [AshamaneProject/AshamaneCore#657]
**Description:**
You charged at the tiki target and you charge.. but noting happens on quest

**Usefull Wowhead links:**
http://www.wowhead.com/quest=24640/the-arts-of-a-warrior
and same for the quest Charge. 
Can not find it on wow head. but its the one that starts in Vailey of Trials by npc Frang

**Comment by HannibalRoG** [comment]
Deprecated quest, sun it will be removed fron DB.

**Comment by Blizzmaster** [comment]
there must be at least 8 level 3´s class quests for each race

**Comment by HannibalRoG** [comment]
Already fix it in valley of trials.
