### ISSUE TITLE
[NPC] voljin

### ISSUE THREAD

**Issue by madmax765** [AshamaneProject/AshamaneCore#658]
**Description:**
NPC Missing voljin

**Usefull Wowhead links:**
http://www.wowhead.com/npc=38966/voljin

**Comment by Neredun** [comment]
I see him both in live and local. Are you sure that's the missing NPC id?

**Comment by Ysil69** [comment]
I van confirm he's missing from the troll starting area. NOT the end quest for the starting area, but when you proceed in from your trainer. 

Although that end quest where Vol'jinn fights zar'jira is definitely bugged too.

**Comment by Neredun** [comment]
This is weird. Cause i checked again and he actually IS in the starting area.

Both on live
![wowscrnshot_041118_122933](https://user-images.githubusercontent.com/21986277/38641844-8b1db7f6-3dae-11e8-947a-0a3caddf407e.jpg)

And on local
![wowscrnshot_041118_173321](https://user-images.githubusercontent.com/21986277/38641868-9d020882-3dae-11e8-8d28-13a92e99963d.jpg)

The modelid problem is something i can confirm

**Comment by Ysil69** [comment]
Hmm weird. Could it possibly be the repack I'm using?

**Comment by Neredun** [comment]
Can you check if you have a spawn of him in your repack?

**Comment by Ysil69** [comment]
How would I go about doing that? Pretty new to this
________________________________

**Comment by Neredun** [comment]
@Ysil69 Use Navicat or SQLyog and do a SELECT *FROM creature WHERE id = 38966

**Comment by Ysil69** [comment]
So he comes up. It his spawnmask is 1 which I'm assuming is enabled. His coordinates are -1318.66 -5604.19 23.7201 orientation 0.811154 Map 1 Area id 0. 

Would that be from my custom adding him though with .npc add?

**Comment by Ysil69** [comment]
Definitely was from custom adding him. Conan did a new repack with the new ashamanecore files. I did a Select from on that one and he's not in there.

**Comment by madmax765** [comment]
using SingleCore_Legion repack

**Comment by cooler-SAI** [comment]
No repack support!!
