### ISSUE TITLE
[QUEST] Fizzled

### ISSUE THREAD

**Issue by madmax765** [AshamaneProject/AshamaneCore#660]
**Description:**

when I go to izzle Darkclaw, rick click on him, a menu pops up says Attempt to remove the orb. but nothing happens.. won't give me the orb
**Usefull Wowhead links:**

http://www.wowhead.com/quest=25260/fizzled#comments

**Comment by Blizzmaster** [comment]
I realize that the creature's SAI had a wrong gossip in the query.
FIX: 
-- Fizzle Darkclaw SAI
SET @ENTRY := 3203;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,62,0,100,512,11240,0,0,0,56,52580,1,0,0,0,0,7,0,0,0,0,0,0,0,"On Gossip Select 11240 Add Item 52580");
