### ISSUE TITLE
[NPC] Drowned Thunder Lizard

### ISSUE THREAD

**Issue by madmax765** [AshamaneProject/AshamaneCore#661]
**Description:**
the npc drownned-thunder-lizards are missing for the quest Thunder Down Under
I added one to test and it's working toward the quest.. just need to add them :)

**Usefull Wowhead links:**
http://www.wowhead.com/npc=39464/drowned-thunder-lizard

http://www.wowhead.com/quest=25236/thunder-down-under

**Comment by aeroashamane** [comment]
Quest ok
