### ISSUE TITLE
[SQL Patch] Fixing Ruins of Ahn'quiraj SpawnMask

### ISSUE THREAD

**Issue by Neredun** [AshamaneProject/AshamaneCore#666]
**Description:**
This should fix the spawnmask on Gameobjects and NPCs for the Ruins of Ahn'quiraj Raid. The Raid is empty when you enter, but this should fix that. I tested it my local.

[Ahnquiraj.zip](https://github.com/AshamaneProject/AshamaneCore/files/1813849/Ahnquiraj.zip)

**Comment by HannibalRoG** [comment]
It work fine for me. What DB do you use?

**Comment by Neredun** [comment]
The raid before this changed? Didn't find the bug on local. A friend (Alejous629) found it in Ashamane Server. I went there and indeed you don't see anyone no matter which difficult you choose. (The thing that i tested on local was the fix.)

**Comment by HannibalRoG** [comment]
Try without the fix in your local and tell me the results. Wihtout that fix work fine for me.

**Comment by Neredun** [comment]
You were right, it works fine in local without this (tested it with .gm on and off to be sure). But still, the bug still happens in the Ashamane server.

In The Server nothing appears (i have no ID):
![wowscrnshot_031518_214644](https://user-images.githubusercontent.com/21986277/37498582-dc2d8c50-289d-11e8-94cc-a1ec82d36c8c.jpg)

But in local it does:
![wowscrnshot_031518_221013](https://user-images.githubusercontent.com/21986277/37498600-feb38ad6-289d-11e8-9538-0afbd5f38abc.jpg)

**Comment by HannibalRoG** [comment]
I think this can be closed, in master this problem does not exist, possibly it is a lost update in the Ashamane server.
You can create a new ticket if necessary.
