### ISSUE TITLE
 [SQL Patch] Acherus: The Ebon Hold More Fixes

### ISSUE THREAD

**Issue by Neredun** [AshamaneProject/AshamaneCore#681]
**Description:**
I completed more things from this Zone:
-Fixed some missing Phases for Gameobjects and some NPCs. (This Also should fix a problem with the quest "Bloody Breakout" and the Vargoth Remains)
-Fixed some missing creatures in the "Epilogue" Chapter (Normal World) due to bad modelid.

-- New (18/03/18) --
-Fixed Scarlet Cannons, now they will can't be moved from his place.
-Added Some missing phaseId for Creatures and Gameobject
-Deleted Scarlet Ghost Spawns, they should only be spawned by the Quest Item of the Quest "The Gift That Keeps On Giving"
-Make the Dummy NPCs invisible (some of the didn't have the flags extra 128, so they were visible but unclickable)
-Deleted some duplicated objects who could lag the game (low FPS)
-Fix Death State for two NPCs (28892,54386) from the phase 171 and dismount one NPC who is dead (28898)
-Fix Some NPCs for the Battle for the Light's Hope event (Light of Dawn Quest) Your enemies shall be clickable and attackable now.
-Fixing Rare movements of the Knights of the Ebon Blade (NPC 29202, normal world) and added phasing to the Portals to the Capital Cities.
-- New (21/03/18) --
-Corrected the Modelid from the NPCs who have the incorrect modelid placed in creature table.

Something of interest: The Acherus teleporters (NPCs 29580 and 29581) on Scarlet Enclave don't seem to work when you're on phases (171,175,176...). The Same thing happens with the bunnies who act as runeforges (NPCs 28481 and 28483)

[Ebon Hold Misc Fixing.zip](https://github.com/AshamaneProject/AshamaneCore/files/1838473/Ebon.Hold.Misc.Fixing.zip)

**Comment by pedroevil51** [comment]
Nice man, good work

**Comment by HannibalRoG** [comment]
It seems that there is an error when downloading git files, I will try tomorrow, otherwise, I will contact you so that you can send them to me by mail.
