### ISSUE TITLE
Missing sql updates after Trinity merge

### ISSUE THREAD

**Issue by silviu2008** [AshamaneProject/AshamaneCore#684]
Missing updates in ashmane/auth and ashamane/world after merge f2adc5b04fc8bf55f892256655aa6bccc5c41039 (https://github.com/AshamaneProject/AshamaneCore/commit/f2adc5b04fc8bf55f892256655aa6bccc5c41039)

**Comment by HannibalRoG** [comment]
Closed by https://github.com/AshamaneProject/AshamaneCore/commit/30501b99675a6b21b7cefb03321ba8289e29e421
