### ISSUE TITLE
[SQL mini-Patch] Remove Deprecated Flying Skills from Trainers

### ISSUE THREAD

**Issue by Neredun** [AshamaneProject/AshamaneCore#689]
**Description:**
This should remove the Skills Flight Master's License, Cold Weather Flying and Wisdom of the Four Winds which aren't needed anymore, and were removed from trainers since 7.3.5.

[Riding.zip](https://github.com/AshamaneProject/AshamaneCore/files/1822601/Riding.zip)

**Comment by HannibalRoG** [comment]
It seems that there is an error when downloading git files, I will try tomorrow, otherwise, I will contact you so that you can send them to me by mail.
