### ISSUE TITLE
Win. compile failed 

### ISSUE THREAD

**Issue by Igorinus** [AshamaneProject/AshamaneCore#690]
errors when compile

**Comment by Traesh** [comment]
Is your OpenSSL up to date ?

**Comment by Igorinus** [comment]
i have this Win32 OpenSSL v1.0.2n 20MB Installer, do i need higher version ?

**Comment by Thordekk** [comment]
same error i don´t know how to resolve

**Comment by Igorinus** [comment]
i have all the openssl up to day for 32 and 64 i dont make any recently updates or changes  into computer i just realise the compile suddenly dont work any more

**Comment by Igorinus** [comment]
so now what will happen ? i mean we still have the errors  some of us, any suggestions  ?

**Comment by HannibalRoG** [comment]
@igorinus I do not know what you are doing wrong but right now master does not have any problem to compile in windows.

**Comment by Igorinus** [comment]
i didn't do anything wrong and  how i say i don't  made any changes  or windows updates it is just happens to not work any more suddenly so any suggestions please ?

**Comment by Igorinus** [comment]
how ever fixed and posted solution here https://github.com/AshamaneProject/AshamaneCore/issues/724
