### ISSUE TITLE
Quest "Shu, the Spirit of Water"

### ISSUE THREAD

**Issue by LuXia123** [AshamaneProject/AshamaneCore#697]
This quest is bugged in two ways: First the little "portals" on the stones do not work, I have found a way around it. However, once I get into the pool of reflection, I can't use the Sun Pearl to coax Shu out and it reads "Pool of reflection required" as the error message.

Here's the wowhead link to the quest: http://www.wowhead.com/quest=29678/shu-the-spirit-of-water

Thanks for your help.

**Comment by LuXia123** [comment]
It seems like the issue stems from a location error. Even though I am on the poo of reflection, the map shows the quest area to be the other pond but even when in the circle I cannot accomplish the action. 

![pool](https://user-images.githubusercontent.com/37591272/37718732-b5c52d5e-2d23-11e8-99ec-63a1aeca9810.PNG)

**Comment by HannibalRoG** [comment]
Fixed in latest conmmits
