### ISSUE TITLE
worldserver crash after update

### ISSUE THREAD

**Issue by Thordekk** [AshamaneProject/AshamaneCore#699]
**Description:**
The world server crash after the sql updates

**Usefull Wowhead links:**
[DBErrors.log](https://github.com/AshamaneProject/AshamaneCore/files/1831681/DBErrors.log)
[Server.log](https://github.com/AshamaneProject/AshamaneCore/files/1831682/Server.log)

**Comment by HannibalRoG** [comment]
Update your Core and DB, there is no error now.
