### ISSUE TITLE
DB/Spawns: Wrong default locale.

### ISSUE THREAD

**Issue by Eredar** [AshamaneProject/AshamaneCore#7]
**Description:**
Many if not all creatures in Legion Dalaran/Azsuna/others have wrong locale with enUS client. (Spanish?)

**Current behaviour:**
Wrong locales for enUS client.

**Expected behaviour:**
Proper locale selection/default one.

**Steps to reproduce the problem:**
1. Download enUS locale pack.
2. Log in and go to Legion Dalaran.

**Branch(es):**
master

**TC rev. hash/commit:** 
TrinityCore rev. b1a76c79cbda 2017-11-16 11:04:58 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  ADB_725.02

**Operating system:** Win 10 x64

**Comment by Traesh** [comment]
Fixed with ADB725.03
