### ISSUE TITLE
Worldserver Crash while running the worldserver for the first time

### ISSUE THREAD

**Issue by sujoy84** [AshamaneProject/AshamaneCore#700]
**Description:**
worldserver.exe crashed while running the server for the first time after compiling. Showing this error:
"Could not prepare statements of the World database"

**Usefull Wowhead links:**
[DBErrors.log](https://github.com/AshamaneProject/AshamaneCore/files/1832222/DBErrors.log)
[Server.log](https://github.com/AshamaneProject/AshamaneCore/files/1832223/Server.log)

**Comment by cyilcode** [comment]
I don't if its the same but i have had a similar problem. If you have followed the documentation that was given in the README.md, that is actually for `TrinityCore` project. 

My problem was the DB itself. The docs were saying that i should be downloading `TDB 7.3.5` db and migrate that however that never worked for me. What has worked for me was downloading the latest DB release of [this project](https://github.com/AshamaneProject/AshamaneCore/releases), rename the files to the names from `TDB` project and run the worldserver.

**Comment by HannibalRoG** [comment]
To use AshamaneCore you need [ADB](https://github.com/AshamaneProject/AshamaneCore/releases/tag/ADB725.03), in the latest updates there are no problems of that type.
