### ISSUE TITLE
[Artifact Weapons] Items who give Artifact Power

### ISSUE THREAD

**Issue by Neredun** [AshamaneProject/AshamaneCore#701]
**Description:**
For some reason, the items who give artifact power like Brief History of the Ages (http://www.wowhead.com/item=138782) or History of the Ages (http://www.wowhead.com/item=141856) Are giving A LOT of Artifact Power.

Here i'm showing that i looted Brief History of Ages:
![wowscrnshot_031718_063518](https://user-images.githubusercontent.com/21986277/37700283-a6e45c24-2cc9-11e8-9597-c9654e32bc2d.jpg)

A Combat log of the spell of the item after using it:
![wowscrnshot_031718_063526](https://user-images.githubusercontent.com/21986277/37700284-a70924c8-2cc9-11e8-8091-7ededaebcb7b.jpg)

In the chat you can see 630,000,000,100 and i can confirm that this is NOT visual:
![wowscrnshot_031718_063529](https://user-images.githubusercontent.com/21986277/37700285-a729ad74-2cc9-11e8-9cf9-4ed72163c439.jpg)

Also tried to see if was an Artifact problem but no, also happen with Fangs of Ashamane:
![wowscrnshot_031718_054112](https://user-images.githubusercontent.com/21986277/37700362-f98f3a84-2cc9-11e8-8023-93e1e2a26d44.jpg)

![wowscrnshot_031718_054140](https://user-images.githubusercontent.com/21986277/37700424-33d03e28-2cca-11e8-852d-2d65c247ca4b.jpg)

**Comment by Deisydemant** [comment]
it's normal, we have 55 Artifact Research Notes so you have a lot power in the beginning  but later u will see it's nothing =)

**Comment by Traesh** [comment]
Yup, not a bug, from 7.3.x you start with 55 artifact research

**Comment by Neredun** [comment]
i had no idea of that. Thanks for the clarification!
