### ISSUE TITLE
Lots of DB and Server errors on my self compiled server

### ISSUE THREAD

**Issue by sujoy84** [AshamaneProject/AshamaneCore#703]
**Description:**
I am getting lots of DB and Server errors when I run the worldserver.exe file. I am pretty new to this WoW Repack thing. Please help me.

**Usefull Wowhead links:**

[DBErrors.log](https://github.com/AshamaneProject/AshamaneCore/files/1834423/DBErrors.log)
[Server.log](https://github.com/AshamaneProject/AshamaneCore/files/1834427/Server.log)

**Comment by Livux** [comment]
I guess that's normal.

**Comment by pedroevil51** [comment]
it's normal , numerous things haven't been conf yet, just do it your self or help the devs too

**Comment by martin26** [comment]
Turn of logging in the conf file for db errors, the server will start way faster.

**Comment by HannibalRoG** [comment]
Update to latest, they have been reduced a lot.
