### ISSUE TITLE
Second quest of Tirisfal (Undead)

### ISSUE THREAD

**Issue by Livux** [AshamaneProject/AshamaneCore#704]
**Description:**
Second quest, when the NPC appears, that goes with you (Darnell or sth) he says "Greetings $n" and not the name of the player

**Usefull Wowhead links:**
CreatureID: 49141
Broadcast Text ID (for example): 49305
Text: Greetings, $n.

**Comment by HannibalRoG** [comment]
Idk why this happen, another text have same structure and work fine show the correct player name.

**Comment by Livux** [comment]
Probably script-based? Where are the quests scripted?

**Comment by HannibalRoG** [comment]
https://github.com/AshamaneProject/AshamaneCore/blob/master/sql/ashamane/world/2018_03_13_00_world_undead_zone.sql

**Comment by Livux** [comment]
Thx. Is that the fix? Can you commit that to the master?

**Comment by HannibalRoG** [comment]
That is already in master.

**Comment by Igorinus** [comment]
guys about undeads i have made  in my 4.3.4 rate of 99% good here is  things that could help https://pastebin.com/KiaG5TL2

**Comment by HannibalRoG** [comment]
Gays, except by the $n in creature text all zone work like ofi, please try it first.

**Comment by Igorinus** [comment]
no offense but (gays) its mean somethings bad i think you wanna say guys

**Comment by Livux** [comment]
Being gay isn't something bad. ;p

But: Maybe $n is wrong and it should be replaced with $N ?

**Comment by HannibalRoG** [comment]
I am sorry for that "guys"
Maybe there is something wrong with creature_text called by SAIs.

**Comment by LKArthas** [comment]
there's nothing wrong with the creature text, it's just wrong SAI made, for the $n $r $g and all other kind of variables you should use target_type 7 if it's invoker or on the specific case of that quest you should use target_type 23 Owner ;)
(@ENTRY,0,5,0,40,0,100,0,13,0,0,0,1,10,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Waypoint 13 Reached - Say Line 10"),
(@ENTRY,0,6,0,40,0,100,512,17,0,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Waypoint 17 Reached - Despawn Instant"),
(@ENTRY,0,7,0,54,0,100,512,0,0,0,0,8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Just Summoned - Set Reactstate Passive"),
(@ENTRY*100+00,9,0,0,0,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Say Line 0"),
(@ENTRY*100+00,9,1,0,0,0,100,0,4000,4000,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Say Line 1"),
(@ENTRY*100+00,9,2,0,0,0,100,0,0,0,0,0,53,1,49141,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Start Waypoint"),
(@ENTRY*100+01,9,0,0,0,0,100,0,0,0,0,0,1,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Say Line 2"),
(@ENTRY*100+02,9,0,0,0,0,100,0,0,0,0,0,54,4000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Pause Waypoint"),
(@ENTRY*100+02,9,1,0,0,0,100,0,0,0,0,0,1,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Say Line 3"),
(@ENTRY*100+03,9,0,0,0,0,100,0,0,0,0,0,54,6000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Pause Waypoint"),
(@ENTRY*100+03,9,1,0,0,0,100,0,0,0,0,0,1,4,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Say Line 4"),
(@ENTRY*100+03,9,2,0,0,0,100,0,0,0,0,0,1,5,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Say Line 5"),
(@ENTRY*100+03,9,3,0,0,0,100,0,3000,3000,0,0,1,6,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Say Line 6"),
(@ENTRY*100+03,9,4,0,0,0,100,0,4000,4000,0,0,1,7,0,0,0,0,0,7,0,0,0,0,0,0,0,"Darnell - On Script - Say Line 7"),
(@ENTRY*100+04,9,0,0,0,0,100,0,0,0,0,0,54,10000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Pause Waypoint"),
(@ENTRY*100+04,9,1,0,0,0,100,0,0,0,0,0,1,8,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Say Line 8"),
(@ENTRY*100+04,9,2,0,0,0,100,0,4000,4000,0,0,1,9,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Script - Say Line 9");
With this lines OFC the creature wont say the name of the owner, just change the target_type to 23 and will work :P

**Comment by Livux** [comment]
Genius!

**Comment by Sonyc1987** [comment]
LoL that's basic stuff. ;)

**Comment by HannibalRoG** [comment]
Ok, that already fixit here https://github.com/AshamaneProject/AshamaneCore/commit/ba535e2ff58ff6f5068792c88d5c916995889ff8

Now, since a time when Darnell is invoked, on both occasions (two different quests), until you enter combat he does not run the script, he just keeps following you.
When you enter combat is that he begins to follow the script.
Any ideas?

**Comment by LKArthas** [comment]
oks, Lesson 2.0 ;)
(@ENTRY,0,0,0,54,0,100,512,0,0,0,0,80,@ENTRY*100+00,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Just Summoned - Run Script"),
(@ENTRY,0,1,0,40,0,100,512,4,0,0,0,80,@ENTRY*100+01,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Waypoint 4 Reached - Run Script"),
(@ENTRY,0,2,0,40,0,100,512,8,0,0,0,80,@ENTRY*100+02,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Waypoint 8 Reached - Run Script"),
(@ENTRY,0,3,0,40,0,100,512,9,0,0,0,80,@ENTRY*100+03,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Waypoint 9 Reached - Run Script"),
(@ENTRY,0,4,0,40,0,100,512,10,0,0,0,80,@ENTRY*100+04,0,0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Waypoint 10 Reached - Run Script"),
with this script you made OFC only runs if the creature it's OOC you need to set action_param2 to 2
like this 
(@ENTRY,0,4,0,40,0,100,512,10,0,0,0,80,@ENTRY*100+04,----->    2,    <------- 0,0,0,0,1,0,0,0,0,0,0,0,"Darnell - On Waypoint 10 Reached - Run Script"),
0-- Only runs OOC
1 -- Runs IC
2 -- Runs in Both Ocations
:)

**Comment by HannibalRoG** [comment]
@LKArthas with 0-- Only runs OOC it should work, because, you are not in combat. That behavior that I describe happens with OOC
Now i changed it to 2-- Runs always, and it keeps the same behavior, you need to enter in combat for script runs.
Another idea?

**Comment by LKArthas** [comment]
to wich script do you refer, ID?

**Comment by HannibalRoG** [comment]
49141
