### ISSUE TITLE
Profession Enchanting: Enchanted Vellum Error

### ISSUE THREAD

**Issue by Mistixc** [AshamaneProject/AshamaneCore#705]
**Description:**
If you're going to enchant with the Enchanted Vellum, it doesn't create a respective scroll instead the Enchanted Vellum is self enchanted.
![37264230-9dcbb680-2582-11e8-9fa0-c94d027f83c5](https://user-images.githubusercontent.com/35430178/37728608-c11613c8-2d08-11e8-80b8-686361a63367.png)

**Usefull Wowhead links:**

**Comment by HannibalRoG** [comment]
Duplicated #640
