### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Thordekk** [AshamaneProject/AshamaneCore#707]
**Description:**

errors at start worldserver
>> Hotfixes database is up-to-date! Containing 21 new and 0 archived updates.
Could not prepare statements of the Hotfix database, see log for details.
That´s error:
[DBErrors.log](https://github.com/AshamaneProject/AshamaneCore/files/1835500/DBErrors.log)
 Please help

**Comment by HannibalRoG** [comment]
you need to give more information about what DB and what Core you are using, otherwise it is impossible to help.
Anyway, you should keep in mind that the master project only works with the correct [DB](https://github.com/AshamaneProject/AshamaneCore/releases/tag/ADB725.03).
