### ISSUE TITLE
No allied race creation menu

### ISSUE THREAD

**Issue by sujoy84** [AshamaneProject/AshamaneCore#710]
**Description:**
I don't have the menu to create allied races. Am I missing something? It's a freshly compiled server with all the latest updates.

**Usefull Wowhead links:**

![wowscrnshot_032218_222613](https://user-images.githubusercontent.com/12880541/37785527-6796e75a-2e20-11e8-9710-0659b195cdce.jpg)

**Comment by Livux** [comment]
Just change your account expansion ID to 7
