### ISSUE TITLE
Bug DH

### ISSUE THREAD

**Issue by JustYukki** [AshamaneProject/AshamaneCore#713]
Bug sur les spells du DH : 
Bug sur la " Ruée Fulgurante " qui peut te faire fly ( cancel le fly avec le " Retraite vengeresse " ) .
Bug sur l'arme prodigieuse DH " Lames jumelles du trompeur " , le sort dans les talents  : " Fureur des illidari " n'inflige aucun dommage de zone , mais inflige le ralentissement prévu .
Bug de talent sur l'arme prodigieuse , le démon sur la compétence passive " Démons intérieur " ne s'abat pas sur la cible et n'inflige pas de dommage .
Bug talent  " Rage des illidari " qui ne prock pas les dommages supplémentaires . 
Bug talent " angoisse du trompeur " qui n'inflige pas de dégâts supplémentaires .

**Comment by HannibalRoG** [comment]
#5
