### ISSUE TITLE
Error compiler

### ISSUE THREAD

**Issue by Thordekk** [AshamaneProject/AshamaneCore#724]
**Description:**

26>Main.obj : error LNK2019: símbolo externo SSLeay_version sin resolver al que se hace referencia en la función "public: void __cdecl <lambda_a25fa23e6b043532f702be5539cb18e5>::operator()(void)const " (??R<lambda_a25fa23e6b043532f702be5539cb18e5>@@QEBAXXZ)
26>scripts.lib(cs_server.obj) : error LNK2001: símbolo externo SSLeay_version sin resolver
26>common.lib(OpenSSLCrypto.obj) : error LNK2019: símbolo externo CRYPTO_num_locks sin resolver al que se hace referencia en la función "void __cdecl OpenSSLCrypto::threadsCleanup(void)" (?threadsCleanup@OpenSSLCrypto@@YAXXZ)
26>common.lib(OpenSSLCrypto.obj) : error LNK2019: símbolo externo CRYPTO_set_locking_callback sin resolver al que se hace referencia en la función "void __cdecl OpenSSLCrypto::threadsCleanup(void)" (?threadsCleanup@OpenSSLCrypto@@YAXXZ)
26>common.lib(OpenSSLCrypto.obj) : error LNK2019: símbolo externo CRYPTO_THREADID_set_numeric sin resolver al que se hace referencia en la función "void __cdecl threadIdCallback(struct crypto_threadid_st *)" (?threadIdCallback@@YAXPEAUcrypto_threadid_st@@@Z)
26>common.lib(OpenSSLCrypto.obj) : error LNK2019: símbolo externo CRYPTO_THREADID_set_callback sin resolver al que se hace referencia en la función "void __cdecl OpenSSLCrypto::threadsCleanup(void)" (?threadsCleanup@OpenSSLCrypto@@YAXXZ)
26>common.lib(HmacHash.obj) : error LNK2019: símbolo externo HMAC_CTX_init sin resolver al que se hace referencia en la función "public: __cdecl HmacHash<&struct env_md_st const * __cdecl EVP_sha1(void),20>::HmacHash<&struct env_md_st const * __cdecl EVP_sha1(void),20>(unsigned int,unsigned char const *)" (??0?$HmacHash@$1?EVP_sha1@@YAPEBUenv_md_st@@XZ$0BE@@@QEAA@IPEBE@Z)
26>common.lib(HmacHash.obj) : error LNK2019: símbolo externo HMAC_CTX_cleanup sin resolver al que se hace referencia en la función "public: __cdecl HmacHash<&struct env_md_st const * __cdecl EVP_sha1(void),20>::~HmacHash<&struct env_md_st const * __cdecl EVP_sha1(void),20>(void)" (??1?$HmacHash@$1?EVP_sha1@@YAPEBUenv_md_st@@XZ$0BE@@@QEAA@XZ)
26>common.lib(ARC4.obj) : error LNK2019: símbolo externo EVP_CIPHER_CTX_init sin resolver al que se hace referencia en la función "public: __cdecl ARC4::ARC4(unsigned int)" (??0ARC4@@QEAA@I@Z)
26>gsoap.lib(stdsoap2.obj) : error LNK2019: símbolo externo sk_num sin resolver al que se hace referencia en la función tcp_connect
26>gsoap.lib(stdsoap2.obj) : error LNK2019: símbolo externo sk_value sin resolver al que se hace referencia en la función tcp_connect
26>gsoap.lib(stdsoap2.obj) : error LNK2019: símbolo externo sk_pop_free sin resolver al que se hace referencia en la función tcp_connect
26>gsoap.lib(stdsoap2.obj) : error LNK2019: símbolo externo OPENSSL_add_all_algorithms_noconf sin resolver al que se hace referencia en la función soap_ssl_init
26>gsoap.lib(stdsoap2.obj) : error LNK2019: símbolo externo SSL_load_error_strings sin resolver al que se hace referencia en la función soap_ssl_init
26>gsoap.lib(stdsoap2.obj) : error LNK2019: símbolo externo SSLv23_method sin resolver al que se hace referencia en la función ssl_auth_init
26>gsoap.lib(stdsoap2.obj) : error LNK2019: símbolo externo SSL_library_init sin resolver al que se hace referencia en la función soap_ssl_init
26>gsoap.lib(stdsoap2.obj) : error LNK2019: símbolo externo SSL_state sin resolver al que se hace referencia en la función tcp_connect
26>C:\Legion Core\bin\Release\worldserver.exe : fatal error LNK1120: 16 externos sin resolver
26>Compilación del proyecto "worldserver.vcxproj" terminada -- ERROR.
27>------ Operación Compilar iniciada: proyecto: ALL_BUILD, configuración: Release x64 ------
27>Building Custom Rule C:/Legion source/CMakeLists.txt
27>CMake does not need to re-run because C:/Legion Core/CMakeFiles/generate.stamp is up-to-date.
28>------ Operación Compilar omitida: proyecto: INSTALL, configuración: Release x64 ------
28>Proyecto no seleccionado para compilarse para esta configuración de solución 
========== Compilar: 24 correctos, 2 incorrectos, 0 actualizados, 2 omitidos ==========

**Usefull Wowhead links:**

**Comment by Igorinus** [comment]
i have the same error but  lisen go to your  openssl folders uninstall the  openssl 32  and 64 if you have both then restart then reinstall 1.0.2 versions direct url https://slproweb.com/download/Win32OpenSSL-1_0_2n.exe and https://slproweb.com/download/Win64OpenSSL-1_0_2n.exe then will work

**Comment by Thordekk** [comment]
Thanks bro im going to make that

**Comment by Thordekk** [comment]
links broken

**Comment by Igorinus** [comment]
ok np here it is https://slproweb.com/products/Win32OpenSSL.html scroll down and find  file Win32 OpenSSL v1.0.2o Type  20MB Installer   and the second one find file Win64 OpenSSL v1.0.2o Type 23MB Installer and  install them restart pc and  it should work after

**Comment by Thordekk** [comment]
ty works
