### ISSUE TITLE
Can't learn skill from hunter trainer.

### ISSUE THREAD

**Issue by cowcoa** [AshamaneProject/AshamaneCore#728]
**Description:**

Can't learn Steady Shoot skill from the first hunter trainer after reach level 3.

**Comment by LeRutY** [comment]
Those quests are outdated.

**Comment by cowcoa** [comment]
But I still can see the exclamatory mark and accept the quest, it's confused.

**Comment by cowcoa** [comment]
Dwarf, Dwarf Hunter

**Comment by cowcoa** [comment]
The npc's name is "Thorgas Grimson", and the quest name is "Oh, A Hunter's Life For Me.". In the dialog with that npc, I can't click "I seek training in the ways of the Hunter" to learning skill. But the quest direct me to "Practice Steady Shot" 5 times.

**Comment by cowcoa** [comment]
By the way, with the same npc's dialog, "How do I learn Dual Specialization?" can't be clicked also.

**Comment by Oldarorn** [comment]
Thank you for your report, the quest you tried to achieve is considered as obsolete by Blizzard and will be no longer available :) and I read about the "How do I learn Dual Specialization" and after some test it appears to be working, everything will be done in a few updates, have a nice day !
