### ISSUE TITLE
Unkown crash after a while of playing with friends

### ISSUE THREAD

**Issue by pedroevil51** [AshamaneProject/AshamaneCore#729]
**Description:**
The server crashes , and i can't find anything on the logs ;s
Here's the Crash Log 
http://www.mediafire.com/file/840ryxcg5npy68g/Crashes.rar
I'm using windows 10
8 GB Ram 
A i3 3250 
And a gtx 680 
Some times the server goes up to 5 gb of ram 
then crashes

**Comment by HannibalRoG** [comment]
Probably the same of #421

**Comment by Traesh** [comment]
Closed by efd214a3909a8a4df24753ee8f5ebbfe76e7c6a9

**Comment by pedroevil51** [comment]
Still got that memory leak tho, sometimes @Traesh

**Comment by pedroevil51** [comment]
sometimes the server stays 24/7 and never crashes, then a memory leak comes and crashes @Traesh
