### ISSUE TITLE
PvP Talent Server Crashes

### ISSUE THREAD

**Issue by MrToshi** [AshamaneProject/AshamaneCore#730]
If I want to award PVP talent, the server crashes.

SpellMgr.h:680 in SpellMgr::AssertSpellInfo ASSERTION FAILED:
  spellId < GetSpellInfoStoreSize()

**Comment by HannibalRoG** [comment]
Fix it https://github.com/AshamaneProject/AshamaneCore/commit/f74212c8b8d3d31b4f254538da2f586395ff18a8
