### ISSUE TITLE
Vmaps are broken on latest commit

### ISSUE THREAD

**Issue by pedroevil51** [AshamaneProject/AshamaneCore#736]
**Description:**
Latest commit has vmaps not working
Error on startup

**Usefull Wowhead links:**

**Comment by Traesh** [comment]
Vmaps version have been updated in latests commits, you have to re-extract the vmaps

**Comment by Traesh** [comment]
@pedroevil51 FYI i just uploaded the new vmaps on http://dl.ashamane.com/7.3.5/

**Comment by pedroevil51** [comment]
@Traesh thx, but i extracted myself and it worked.
btw nice upload timing for 2 GB 👍 on my internet would have taken years
