### ISSUE TITLE
Imposible de rejoindre le domaine de classe guerrier

### ISSUE THREAD

**Issue by Bokumetsu** [AshamaneProject/AshamaneCore#737]
**Description:**
Je n'arrive pas a aller au domaine de classe de guerrier on m'a dit qu'il etais prrés de l'aire de Krassus a Dalaran prés d'une valkyrie mais elle est introuvable.

**Usefull Wowhead links:**

**Comment by Traesh** [comment]
Bonjour, pour l'instant en attendant la valkyrie à l'aire de krasus vous devriez avoir le spell directement dans votre grimoire en arrivant niveau 100 :)

**Comment by Bokumetsu** [comment]
Ok merci
