### ISSUE TITLE
problème avec une arme prodigieuse 

### ISSUE THREAD

**Issue by Gadorah** [AshamaneProject/AshamaneCore#744]
**Description:**
coucou j'ai un soucis, impossible d'ajouter des lv sur mon arme prodigieuse (Griffe Serre), alors que sur mes deux autres armes ça fonctionne très bien ^^. Je précise que la lance que j'ai reçue viens par courrier au nom de Blizzard à cause d'un bug qui l'avait effacé de mon inventaire. 

hello I have a problem, impossible to add lv on my artifact weapon (Claw things), while on my other two weapons it works very well ^^. I specify that the spear I received comes by mail on behalf of Blizzard because of a bug that had erased it from my inventory.

**Usefull Wowhead links:**

**Comment by Traesh** [comment]
Vu en jeu de mémoire :) Sinon me contacter sur Discord
