### ISSUE TITLE
Guerrier Arme Talent " Attaque circulaire "

### ISSUE THREAD

**Issue by Linksa** [AshamaneProject/AshamaneCore#748]
**Description:**
Le talent niveau 15 du guerrier spé arme ne fonctionne pas comme il devrait. En effet, suivant ça description, " Frappe mortelle et Exécution touchent 2 cibles supplémentaires proches " Frappe mortelle et Exécution devraient touché donc 3 cible en tous, et si cela est vrai pour la Frappe mortelle, l'Exécution ne s'applique pas, ce qui est un problème pour le dps aoe avec ce talent la qui est important. 

**Usefull Wowhead links:**
http://fr.wowhead.com/spell=202161/attaques-circulaires

**Comment by HannibalRoG** [comment]
Already in list #499, thanks.
