### ISSUE TITLE
Guerrier Arme Talent " Trauma "

### ISSUE THREAD

**Issue by Linksa** [AshamaneProject/AshamaneCore#749]
**Description:**
Le talent niveau 45 du guerrier Arme ne fonctionne pas comme il devrait, en effet, suivant la description de sont talent : " Heurtoir, Tourbillon et Exécution font saigner la cible, ce qui lui inflige 20% de dégâts supplémentaires en 6 sec. Les utilisations répétées cumulent les augmentations de dégâts.
".
Heurtoir applique bien le saignement indiqué, mais pas Tourbillon et Exécution. 
Je suis moins sûr sur ce coup la, mais je pense que la cumulation aussi ne ce fait pas correctement.

**Usefull Wowhead links:**

http://fr.wowhead.com/spell=215538/trauma

**Comment by HannibalRoG** [comment]
Already in list #499
