### ISSUE TITLE
[Guild Bank] bug

### ISSUE THREAD

**Issue by Szone** [AshamaneProject/AshamaneCore#755]
**Description:**
I can`t add items in guild bank.

**Usefull Wowhead links:**
-

**Comment by Oldarorn** [comment]
What kind of items are you trying to add ? I've just tried and it was working with some consumable items

**Comment by Traesh** [comment]
Please note what item you are trying to add and how (right click, drag & drop, etc)

**Comment by madmax765** [comment]
I have sort of the same trouble. I can add items to guild bank if it's in my first bag.But if I try to add them from my other bags it won't, But if I move the item from lest say bag 3 to my main bad. then it will go in the guild bank. Hope this info helps.

**Comment by Szone** [comment]
I checked again and @madmax765's description fits best. Thank you!

**Comment by Szone** [comment]
Solved!
