### ISSUE TITLE
[SQL] sql/ashamane/world/2018_03_30_03_world_misc.sql

### ISSUE THREAD

**Issue by johnsvc** [AshamaneProject/AshamaneCore#756]
**Description:**
Error importing at line 16
Tools attempted: Mysqlworkbench  ;  Dbeaver; SQLYog. Might due to the fact that I'm using Mysql 5.7, or just a plain typo in the sql script.

Cheers

update: Seems to have problem importing with most lines in the script.

**Comment by pedroevil51** [comment]
yeah, some of the sql scripts are wrong, with an * on them
