### ISSUE TITLE
[QUEST] Seeing Where Your Loyalties Lie

### ISSUE THREAD

**Issue by madmax765** [AshamaneProject/AshamaneCore#775]
**Description:**
I go to Fleet Master Seahorn, To get the head.I try talking to him, he dose nothing

**Usefull Wowhead links:**

http://www.wowhead.com/quest=26629/seeing-where-your-loyalties-lie

**Comment by cooler-SAI** [comment]
fixed in my fix pack, close please

**Comment by HannibalRoG** [comment]
Close #775
