### ISSUE TITLE
[Quest/Zone] The Dark Portal (Crashes Server)

### ISSUE THREAD

**Issue by DivineOwner777** [AshamaneProject/AshamaneCore#777]
When you accept the quest *The Dark Portal* in the Blasted Lands and then talk to Khadgar and select the  *For Azeroth!* button, You load into Tanaan Jungle, but you fall through the floor and then the Server crashes(As seen in this video) - https://youtu.be/nDIlqmUKS2Y

Draenor itself seems to load fine without crashes as seen in this screenshot. (I made a fresh horde character and used the .tele frostwall (I saved a TELE before the new update.)
Screenshot: https://imgur.com/a/7JD5D

Crash File: https://pastebin.com/F6pBabFq
Quest: http://www.wowhead.com/quest=34398/the-dark-portal
Npc: http://www.wowhead.com/npc=78558/archmage-khadgar

**Comment by Traesh** [comment]
Is your core compiled in debug mode ? I can't see method names in the crashlog

**Comment by DivineOwner777** [comment]
I'm having issues compiling the core in debug mode for some reason, If I can fix the compiling issue ill upload a new log.

**Comment by DivineOwner777** [comment]
The quest/zone is now working, here is a screenshot of my new character who was able to complete the quest/zone in correctly. :)

https://imgur.com/a/4K75z
