### ISSUE TITLE
WOW64.exe error

### ISSUE THREAD

**Issue by Pretirkal** [AshamaneProject/AshamaneCore#778]
**Description:**
Perso Elmavi =) Pandarie =) BUG

**Usefull Wowhead links:**
![capture](https://user-images.githubusercontent.com/28947875/38298692-5d07d588-37f8-11e8-8bc5-02fca6ada13e.PNG)

**Comment by cooler-SAI** [comment]
close, too old core support bug report,all good for me now

**Comment by HannibalRoG** [comment]
Close #778
