### ISSUE TITLE
[Quest] Protecting Our Rear

### ISSUE THREAD

**Issue by ShokzDev** [AshamaneProject/AshamaneCore#781]
**Description:**
- Gomegaz does not appear in the marked place to kill him and complete a mission objective

**Usefull Wowhead links:**
http://www.wowhead.com/quest=26173/protecting-our-rear
http://www.wowhead.com/npc=41166/gomegaz

**Comment by Neredun** [comment]
Gomegaz has the deprecated modelid. So the fix is easy:

```
UPDATE creature_template SET modelid1 = 73332 WHERE entry = 41166;
UPDATE creature SET modelid = 73332 WHERE id = 41166;
```

**Comment by HannibalRoG** [comment]
Closed https://github.com/AshamaneProject/AshamaneCore/commit/c4cccc5e6a298c3ce0d68d0c520ea5b328f23f1a
