### ISSUE TITLE
.lookup command causes client crash

### ISSUE THREAD

**Issue by LKArthas** [AshamaneProject/AshamaneCore#783]
**Description:**
When you use a .lookup command causes client crash like .lookup quest or .lookup creature, WoW Client Crashes Inmediatly
Rev. 7f38623f4dd2

**Usefull Wowhead links:**
![wow crash](https://user-images.githubusercontent.com/1549829/38377632-61973ae0-38c9-11e8-9cd3-787f98da1f5f.png)

**Comment by martin26** [comment]
.lookup creature does not crash the client.

**Comment by LKArthas** [comment]
but lookup quest it does

**Comment by martin26** [comment]
Yes the quest one does, it is already posted.

**Comment by HannibalRoG** [comment]
Duplicated #706
