### ISSUE TITLE
Error importing 2018_04_05_01_world_at_circular.sql

### ISSUE THREAD

**Issue by Szone** [AshamaneProject/AshamaneCore#786]
**Description:**

[detached from 24854.auth]
root@legion:~/server7# ./worldserver
TrinityCore rev. 5a55671b9567 2018-04-05 15:41:45 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file /root/server7/etc/worldserver.conf.
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.62.0
Updating Auth database...
>> Auth database is up-to-date! Containing 6 new and 0 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 16 new and 0 archived updates.
Updating World database...
>> Applying update "2018_04_05_01_world_at_circular.sql" '7612F0E'...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1136 (21S01) at line 17: Column count doesn't match value count at row 1

Applying of file '/root/AshamaneCore/sql/ashamane/world/2018_04_05_01_world_at_circular.sql' to database 'legionw' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.
root@legion:~/server7#

**Comment by Thordekk** [comment]
me too

**Comment by Dreda59** [comment]
Edit this line +INSERT INTO `spell_areatrigger_circular` VALUES (5016, 12.27271, 12.27271, 2.286397, 0, 0, 1)
to +INSERT INTO `spell_areatrigger_circular` VALUES (5016, 12.27271, 12.27271, 2.286397, 0, 0, 1, 26124)

**Comment by Szone** [comment]
Thank you #Dreda59.
