### ISSUE TITLE
Druid guardian bug (Restoration Affinity)

### ISSUE THREAD

**Issue by ssDaniss2** [AshamaneProject/AshamaneCore#789]
**Description:**
I have this talent from lvl 45 (restoration affinity), but it doesn't work, i dont have "Rejuvenation", "Healing Touch" or "Swiftmend" and "Ysera's Gift" don't work too.

**Usefull Wowhead links:**
http://www.wowhead.com/spell=197492/restoration-affinity

**Comment by Traesh** [comment]
Fixed
