### ISSUE TITLE
Domaine de classe des démonistes [Urgent]

### ISSUE THREAD

**Issue by benji59100** [AshamaneProject/AshamaneCore#796]
**Description:**
Lorsque je clique sur le portail pour accéder au domaines de classe des démonites, celui ci me téléporte dans un endroit dans le ciel , je tombe et je meurt.

Je ne peux donc pas évoluer mon arme prodigieuse , à corriger d'urgence svp ! Merci 

**Usefull Wowhead links:**

**Comment by Neredun** [comment]
This should be fixed after the application of https://github.com/AshamaneProject/AshamaneCore/commit/c4cccc5e6a298c3ce0d68d0c520ea5b328f23f1a
