### ISSUE TITLE
Profession: Fishing

### ISSUE THREAD

**Issue by vtamayoaja** [AshamaneProject/AshamaneCore#8]
Is not working…

When you learn the profession the spell Fishing boot, it is not added … after you disconnect, when you connect again the profession disappears from the spell book.

Madmax735 says:  I learn fishing ok, but the bobber does not go up or down, so I never know when I catch a fish or not

**Comment by shamage** [comment]
@vtamayoaja  : you are not writing a version of the kernel that you are not able to
