### ISSUE TITLE
[SQL-Patch] Human Fix early quest #26391 Extinguishing hope 

### ISSUE THREAD

**Issue by lorac2k14** [AshamaneProject/AshamaneCore#800]
**Description:**
Molly is issuing Extinguishing hope before The rear is clear
*Suggested fix*
`UPDATE `quest_template_addon` SET `PrevQuestID`='28817' WHERE (`ID`='26391');`

**Usefull Wowhead links:**
[Extinguishing Hope](http://www.wowhead.com/quest=26391/extinguishing-hope)
[Northshire Quests](http://www.wowhead.com/northshire-quests)

**Comment by Oldarorn** [comment]
Tested and added, thank you :) !
