### ISSUE TITLE
SQL-Patch Alliance Hunter creation spell bar correction

### ISSUE THREAD

**Issue by lorac2k14** [AshamaneProject/AshamaneCore#801]
**Description:**
With the change of spells on hunters at birth the first spell is not present
and is corrected by removing the spell that blizzard removed from game and replacing with proper spell.
However i can not test the fix for worgens as server crashes on creation.
*Suggested fix*
-- Human
`DELETE FROM `playercreateinfo_action` WHERE (`race`='1') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('1', '3', '0', '193455');`
-- Dwarf
`DELETE FROM `playercreateinfo_action` WHERE (`race`='3') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('3', '3', '0', '193455');`
-- Night Elves
`DELETE FROM `playercreateinfo_action` WHERE (`race`='4') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('4', '3', '0', '193455');`
-- Gnomes
`DELETE FROM `playercreateinfo_action` WHERE (`race`='7') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('7', '3', '0', '193455');`
-- Draenei
`DELETE FROM `playercreateinfo_action` WHERE (`race`='11') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('11', '3', '0', '193455');`

Not tested 
-- Worgens
`DELETE FROM `playercreateinfo_action` WHERE (`race`='22') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('22', '3', '0', '193455');`

**What does this do?**
This puts cobra shot in slot one  of action bar

**Comment by Oldarorn** [comment]
Tested and added, thank you :) !
