### ISSUE TITLE
[SQL-Patch] Horde Hunter Creation Spellbar Correction

### ISSUE THREAD

**Issue by lorac2k14** [AshamaneProject/AshamaneCore#803]
**Description:**
With the change of spells on hunters at birth the first spell is not present
and is corrected by removing the spell that blizzard removed from game and replacing with proper spell.

**Suggested Fix**

-- Table playercreateinfo_action

**-- Blood Elves**
`DELETE FROM `playercreateinfo_action` WHERE (`race`='10') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('10', '3', '0', '193455');`

**-- Goblins**

`DELETE FROM `playercreateinfo_action` WHERE (`race`='9') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('9', '3', '0', '193455');`

**-- Orcs**

`DELETE FROM `playercreateinfo_action` WHERE (`race`='2') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('2', '3', '0', '193455');`

**-- Tauren**

`DELETE FROM `playercreateinfo_action` WHERE (`race`='6') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('6', '3', '0', '193455');`

**-- Troll**

`DELETE FROM `playercreateinfo_action` WHERE (`race`='8') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('8', '3', '0', '193455');`

**-- Undead**

`DELETE FROM `playercreateinfo_action` WHERE (`race`='5') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('5', '3', '0', '193455');`

**-- Panda Neutral**

`DELETE FROM `playercreateinfo_action` WHERE (`race`='24') AND (`class`='3') AND (`button`='0');
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`) VALUES ('24', '3', '0', '193455');`

**Comment by HannibalRoG** [comment]
@lorac2k14 Why did you separate pandas in three different class, neutral, horde and alliance? all pandas class are neutral at creation.

**Comment by lorac2k14** [comment]
Um i had a brain fart, good catch @HannibalRoG I guess I wanted to work harder lol. 
Yes all pandas are 24 at creation. Im going to edit this fix lol so there is less work.

**Comment by HannibalRoG** [comment]
Merged
