### ISSUE TITLE
[Demon Hunter Spell] FellHunter 

### ISSUE THREAD

**Issue by Tk77185** [AshamaneProject/AshamaneCore#804]
FellHunter doesn't work when summoning 

http://www.wowhead.com/spell=691/summon-felhunter

**Comment by Neredun** [comment]
It seems the Felhunter model doesn't have data on creature_model_info, fix is simple in that case.

```
DELETE FROM `creature_model_info` WHERE `DisplayID` = 77398;
INSERT INTO `creature_model_info` VALUES (77398,0,0,0,26124); 
```

**Comment by Tk77185** [comment]
Yes ! it's works thank YOU !!!!!!

**Comment by martin26** [comment]
Could you commit and close? Thanks.
