### ISSUE TITLE
Dépecage

### ISSUE THREAD

**Issue by Rayxard** [AshamaneProject/AshamaneCore#824]
**Description:** J'informe le staff d'Ashamane que le métier travailleur du cuir bug. En effet, avec le couteau de dépeçage ou non, je ne peux même pas dépecer le moindre mob (même ceux d'Elwynn).

**Usefull Wowhead links:**

**Comment by Traesh** [comment]
➤ Oldarorn commented:

Heu attends, y'a un truc qui vient de me frapper. Le dépecage c'est un métier différent de celui du travail du cuir en fait

**Comment by Oldarorn** [comment]
Du coup, je ferme, en fait ça n'a jamais été un bug de pas pouvoir dépecer avec le TDC, c'est ainsi depuis Vanilla :D
