### ISSUE TITLE
Quêtes "[L'appel de Tanaris][L'appel du héros : Tanaris !] Tanaris

### ISSUE THREAD

**Issue by Astrozia** [AshamaneProject/AshamaneCore#83]
Le pnj Kelsey Etinçacier n'est pas la 
[L'appel de Tanaris] ID: 27446
[L'appel du héros : Tanaris !] ID: 28507

**Comment by Azina** [comment]
A vérifier au prochain reboot

**Comment by Astrozia** [comment]
Merci

**Comment by Oldarorn** [comment]
On oublie pas de fermer les tickets :D
