### ISSUE TITLE
Vengeful Retreat and Blade Dance

### ISSUE THREAD

**Issue by Xulthaar** [AshamaneProject/AshamaneCore#841]
**Description:** 

The spell of Demon Hunter "Vengeful Retreat" and "Blade Dance" are not working, the Demon Hunter don't have them on their grimory.

**Usefull Wowhead links:**

http://www.wowhead.com/spell=198793/vengeful-retreat

http://www.wowhead.com/spell=188499/blade-dance

**Comment by HannibalRoG** [comment]
#5
