### ISSUE TITLE
Update 2018_04_09_01_world_localesESes.sql Error

### ISSUE THREAD

**Issue by Szone** [AshamaneProject/AshamaneCore#844]
**Description:**
TrinityCore rev. 1659d367bdd4 2018-04-12 16:17:00 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file /root/server7/etc/worldserver.conf.
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.62.0
Updating Auth database...
>> Auth database is up-to-date! Containing 7 new and 0 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 16 new and 0 archived updates.
Updating World database...
>> Applying update "2018_04_09_01_world_localesESes.sql" '74C316A'...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1146 (42S02) at line 4: Table 'legionw.quest_template_Locale' doesn't exist

**Usefull Wowhead links:**

**Comment by Neredun** [comment]
That error happens cause you don't have the quest_template_locale table.

**Comment by Szone** [comment]
![image](https://user-images.githubusercontent.com/2180820/38694115-77e49cde-3e91-11e8-88af-7feaf455eab0.png)
 
I have that table.

**Comment by Traesh** [comment]
Uppercase L in 'Locale'

**Comment by Neredun** [comment]
Thanks for the info, Traesh. Going to fix it right now

**Comment by Szone** [comment]
Same problem on :

>> Applying update "2018_04_09_02_world_locales_esMX.sql" 'B735D0E'...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1146 (42S02) at line 4: Table 'legionw.quest_template_Locale' doesn't exist
