### ISSUE TITLE
Error auto-update hotfixes in clean instalation

### ISSUE THREAD

**Issue by darvinrivera** [AshamaneProject/AshamaneCore#847]
**Description:**
Error auto-update hotfixes in clean instalation:
OS: Debian 9 64bits:

Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May 2017)
Using Boost version: 1.62.0
Updating Auth database...
Auth database is up-to-date! Containing 7 new and 0 archived updates.
Updating Character database...
Character database is up-to-date! Containing 16 new and 0 archived updates.
Updating World database...
World database is up-to-date! Containing 462 new and 0 archived updates.
Updating Hotfixes database...
> Hotfixes database is up-to-date! Containing 22 new and 0 archived updates.
In mysql_stmt_prepare() id: 0, sql: "SELECT Title, Description, Reward, Flags, MapID, Supercedes, Category, UIOrder, SharesCriteria, Faction, Points, MinimumCriteria, ID, IconFileDataID, CriteriaTree FROM achievement ORDER BY ID DESC"
Unknown column 'MapID' in 'field list'
In mysql_stmt_prepare() id: 6, sql: "SELECT ID, ZoneName, AreaName, Flags1, Flags2, AmbientMultiplier, MapID, ParentAreaID, AreaBit, AmbienceID, ZoneMusic, IntroSound, LiquidTypeID1, LiquidTypeID2, LiquidTypeID3, LiquidTypeID4, UWZoneMusic, UWAmbience, PvPCombatWorldStateID, SoundProviderPref, SoundProviderPrefUnderwater, ExplorationLevel, FactionGroupMask, MountFlags, WildBattlePetLevelMin, WildBattlePetLevelMax, WindSettingsID, UWIntroSound FROM area_table ORDER BY ID DESC"

**Comment by HannibalRoG** [comment]
Update you DB or use ADB from Ashamane proyect.
