### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by Devyl** [AshamaneProject/AshamaneCore#857]
**Description:**
Hello,
I keep on geteting: "Could not prepare statements of the World database, see log for details."
When i go into DBErrors, there is:
"In mysql_stmt_prepare() id: 63, sql: "INSERT INTO gameobject (guid, id, map, spawnMask, PhaseId, PhaseGroup, position_x, position_y, position_z, orientation, rotation0, rotation1, rotation2, rotation3, spawntimesecs, animprogress, state, isActive) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
Unknown column 'isActive' in 'field list'"

I already posted on trinity forums but they say it's custom core, so they won't help.
I tried clean trinity core and it worked without any problem, i seem to getting it only on ashamane core. 
Please help.

**Usefull Wowhead links:**

**Comment by gpn39f** [comment]
you are trying to use a outdated or a alien database on our AshamaneCore 
get the base trinity database "Latest FULL" and from there the core will Auto-Update the database.
Its possible that you receive error on this update procedure.. then you must fix the failure. 
Many update errors are from type: double key not allowed..  the update fix has a insert statement, but the developer was not insert the delete part.. so you have to add them self..

**Comment by Devyl** [comment]
That's exactly what I'm doing. I'm using latest DB (TDB_full_735.00_2018_02_19). It's more like one of the updates is causing problem, but i don't know which one.

**Comment by Dreda59** [comment]
This is not the correct database.

**Comment by Traesh** [comment]
You have to use the Ashamane Database (ABD) available from here : https://github.com/AshamaneProject/AshamaneCore/releases

**Comment by Devyl** [comment]
Which one is it then?
