### ISSUE TITLE
The Power of Light. Obsolete quest.

### ISSUE THREAD

**Issue by Ysil69** [AshamaneProject/AshamaneCore#868]
**Description:**
Quest is out of the game like other class quests.

**Usefull Wowhead links:**

http://www.wowhead.com/quest=26918/the-power-of-the-light

**Comment by HannibalRoG** [comment]
Race and class?

**Comment by TheXWolf** [comment]
DELETE FROM `quest_template` WHERE (`Id`=26918);
DELETE FROM `creature_queststarter` WHERE (`quest`=26918);
DELETE FROM `gameobject_queststarter` WHERE (`quest`=26918);
DELETE FROM `creature_questender` WHERE (`quest`=26918);
DELETE FROM `gameobject_questender` WHERE (`quest`=26918);
DELETE FROM `areatrigger_involvedrelation` WHERE (`quest`=26918);
