### ISSUE TITLE
Steady Shot Quest is Obsolete

### ISSUE THREAD

**Issue by Ysil69** [AshamaneProject/AshamaneCore#869]
**Description:**
Quest is no longer in the game.

**Usefull Wowhead links:**
http://www.wowhead.com/quest=10070/steady-shot

**Comment by HannibalRoG** [comment]
Race and class

**Comment by Ysil69** [comment]
Blood elf Hunter as per the wow head link.
________________________________

**Comment by TheXWolf** [comment]
`DELETE FROM `quest_template` WHERE (`Id`=10070);
DELETE FROM `creature_queststarter` WHERE (`quest`=10070);
DELETE FROM `gameobject_queststarter` WHERE (`quest`=10070);
DELETE FROM `creature_questender` WHERE (`quest`=10070);
DELETE FROM `gameobject_questender` WHERE (`quest`=10070);
DELETE FROM `areatrigger_involvedrelation` WHERE (`quest`=10070);`

**Comment by cooler-SAI** [comment]
fixed
