### ISSUE TITLE
Andorhal Defender unattackable 

### ISSUE THREAD

**Issue by Ysil69** [AshamaneProject/AshamaneCore#879]
**Description:**
One of the spawns of the Andorhal Defenders aren't attackable. Creature ID 44448 is attackable. 44332 is NOT attackable. 

**Usefull Wowhead links:**
http://www.wowhead.com/npc=44448/andorhal-defender
http://www.wowhead.com/npc=44332/andorhal-defender

**Comment by cooler-SAI** [comment]
fixed
