### ISSUE TITLE
Andorhal bosses hit extremely hard. 

### ISSUE THREAD

**Issue by Ysil69** [AshamaneProject/AshamaneCore#880]
**Description:**
This is probably a bigger issue than just these few npcs, since I know shadowfang keep bosses his ridiculously hard too. But they're doing like 5k damage a hit. Araj also doesn't summon any skeletons. 

**Usefull Wowhead links:**
http://www.wowhead.com/npc=44317/the-ravenian
http://www.wowhead.com/npc=44323/darkmaster-gandling
http://www.wowhead.com/quest=26925/araj-the-summoner#comments

**Comment by cooler-SAI** [comment]
fixed
