### ISSUE TITLE
unusable skill tank demon hunter, missing ones and broken 

### ISSUE THREAD

**Issue by jasonh57** [AshamaneProject/AshamaneCore#889]
**Description:**
On my demon hunter I have two spells that don't even appear on my character (demon spike and sigil of flame for the tank and vengeful retreat and blade dance for the dps), my dh being lvl 106 should have all its attack, and furthermore when I'm in my vengeance specialisation I can't use any skills nor my wings everything refuses to work.
my last weapon problem is with my tank weapon, when trying to see if I could use spells with my other spec, my class weapon disapeared and I got it back via mail. now when I equip it I only have one and not 2 as it should be, I cant re equip it so my tank spec is completely unusable.

**Comment by HannibalRoG** [comment]
There is some missing important information, is that issue from live server or master repo?
Is a fresh created DH or old one?
We do some fixes to that class that refer to missing spells.

**Comment by jasonh57** [comment]
I don't know what you meann by live server or master repo but I can tell you that I just created this character last week

**Comment by HannibalRoG** [comment]
You compiled your own server from ashamane repo or you play on private Ashamane server?

**Comment by jasonh57** [comment]
I play on ashamane server

**Comment by HannibalRoG** [comment]
Ok, that is an issue for live server, i cant test in that server.

**Comment by jasonh57** [comment]
Thank you very much for your time

**Comment by Traesh** [comment]
Hello @jasonh57, could you try to change your level 106 talent (sigil of...) and try again if all your vengeance spell still bug ?

**Comment by jasonh57** [comment]
I'll try it now

**Comment by jasonh57** [comment]
Indeed that was this talent that broke my character thank for it ^^
For my two other problems I think that a GM may be able to solve them, I hope at least
The most problematic is formy classe's weapon that should split into two but only gives me the right one
