### ISSUE TITLE
Quest-Desperate Acts 27054

### ISSUE THREAD

**Issue by Ysil69** [AshamaneProject/AshamaneCore#892]
**Description:**
Can't turn in the quest. Complete button does nothing.

**Usefull Wowhead links:**
http://www.wowhead.com/quest=27054/desperate-acts

**Comment by cooler-SAI** [comment]
can't confirm,all works

**Comment by Ysil69** [comment]
Still not working for me. I can turn it in by hand, but the "quest complete" popup isn't working.

**Comment by Ysil69** [comment]
I've "updated" by running the updater included with the SPP repack. It hasn't helped. I've also got other weird things like the scholomance instance portal is missing. I'm never really sure if it's the repack or the core.

If you have the time, would you be able to explain to me how to manually update my DB without having to us the SPP repack?
