### ISSUE TITLE
"Finding a foothold" not working

### ISSUE THREAD

**Issue by sujoy84** [AshamaneProject/AshamaneCore#893]
![wowscrnshot_041918_093936](https://user-images.githubusercontent.com/12880541/38970963-1d617d70-43b6-11e8-80d5-9f4fa1f38441.jpg)
**Description:**
Alliance quest "Finding a foothold" does not work. when I try to complete the quest manually using ".quest reward 34582" it shows "Quest 34582 not found".

**Usefull Wowhead links:**

http://www.wowhead.com/quest=34582/finding-a-foothold

**Comment by Neredun** [comment]
Fixed on https://github.com/AshamaneProject/AshamaneCore/commit/ebbf4b0f4fefe153aa61632056f50daf8ad27331
