### ISSUE TITLE
Ever So Lonely

### ISSUE THREAD

**Issue by conan513** [AshamaneProject/AshamaneCore#895]
**Description:**
Everything is working, except the leash on the wounded murloc.
The leash can only activated on a wounded murloc like the quest says but no effect if I do that.

**Usefull Wowhead links:**
http://www.wowhead.com/quest=24974/ever-so-lonely

**Comment by GeneralissimeDarklinks** [comment]
the last time i did this quest i did not have any problem regarding that resolution. try to use it on several murloc then returned to see the pnj that gave you the quest to see if it is validated

**Comment by cooler-SAI** [comment]
Quest works good for me
