### ISSUE TITLE
Fixes DBErrors Log - creature_template

### ISSUE THREAD

**Issue by Sefrenia-Caecias** [AshamaneProject/AshamaneCore#897]
El archivo adjunto contiene 637 reparaciones del DBErrors Log, relacionados con `creature_template`:

* 602 reparaciones del parámetro `flags_extra`.
* 15 reparaciones del parámetro `unit_class`.
* 16 reparaciones del parámetro `family`.
* 1 reparaciones del parámetro `spell1`.
* 3 reparaciones del parámetro `faction`.

------------------------------------------------

The attached file contains 637 DBErrors Log repairs, related to `creature_template`:

* 602 repairs of the parameter `flags_extra`.
* 15 repairs of the parameter `unit_class`.
* 16 repairs of the parameter `family`.
* 1 repairs of the parameter `spell1`.
* 3 repairs of the `faction` parameter.

[Fixes DBErrors Log - creature_template.log](https://github.com/AshamaneProject/AshamaneCore/files/1928702/Fixes.DBErrors.Log.-.creature_template.log)

**Comment by HannibalRoG** [comment]
Close #897
