### ISSUE TITLE
Fixes DBErrors Log - npc_text

### ISSUE THREAD

**Issue by Sefrenia-Caecias** [AshamaneProject/AshamaneCore#900]
El archivo adjunto contiene 29 reparaciones del DBErrors Log, correspondientes al parámetro `npc_text`.

----------------------------------------------------

The attached file contains 29 repairs to the DBErrors Log, corresponding to the `npc_text` parameter.

[DBErrors Log - npc_text.log](https://github.com/AshamaneProject/AshamaneCore/files/1929232/DBErrors.Log.-.npc_text.log)

**Comment by HannibalRoG** [comment]
Close #900
