### ISSUE TITLE
Terrain swaps

### ISSUE THREAD

**Issue by sergemanuel** [AshamaneProject/AshamaneCore#902]
**Description:**
Someone know if its posible swap terrains on ashamane core .For example gilneas. gilneas has al least 3 maps, or 4 i dont know for sure, the question is, when you complete certain quest the map must be changed destroing gilneas step by step. I want to know if there some spell to do this, or code in core that allow me to do that... after complete a quest, make swap terrains. 
in this video this guy is doing what I want, and he say is under trinity core, but i dont know if it is a modified copy by himself to do this, or the core we are using(ashamane) allow to do this too. 

the video here: https://www.youtube.com/watch?v=Z5NN3NS2ACs

Please help, I am working on gilneas quest line for worgren and i must complete the chain soon but without this, is not the same result.

/Salute.

**Comment by TheXWolf** [comment]
You have to make sure you're in the right phase_mask for spawns etc. When you complete a quest you need to have a spell trigger on complete that sets the players correct phase mask. All that can be done from the DB.

**Comment by sergemanuel** [comment]
I have already see those npc in the area and its work fine, that when I complete certain quest change my phase and see another npc instead of the ones in the passed phase. but i changed my phase to all phases in gilneas and the terrain not change ever. My problemn is not see or not an npc in a certain phase, my problem is the terrain is not swaping with the phase change. 
what i mean is the phase are changing after complete or accept a quest, but not the terrain when it must to change too. example where you complete The Kings Observatory you see a shake on camera and when you look the next cinematic the town must be complete underwater and yet is not, nothing in the map is change when the phases are changing.

**Comment by mayorCuba** [comment]
in C++ should be like this method 
` void SwitchPhaseMapAfterDamExplosion(Player* player)
    {
        PhaseShift phaseShift;
        phaseShift.AddUiWorldMapAreaIdSwap((uint32)TanaanZones::TerrainSwapID);
        PhasingHandler::SendToPlayer(player, phaseShift);
    }
TerrainSwapID = 1307`
I never test it yet

other way was on DB Old table phase_definitions , now loot of thing change on DB so I relay do not Know is there is a Way on DB yet I see there is a new table phase_area but realy do not know how use it yet

**Comment by sergemanuel** [comment]
Thanks man, give me a time to test and apply on gilneas map, then i tell you the result. 

Por tu nombre supongo que eres cubano, de ser asi...gg me too. saludos.

**Comment by sergemanuel** [comment]
mayorCuba, is part of the solution but no complete, the code only chance de WorlMap interfaces, i mean when you press M you see el new map, but when you move see the old one. the code AddUiWorldMapAreaIdSwap refer to Ui(user interface).

**Comment by sergemanuel** [comment]
Hello. at last, i do this:
PhaseShift phaseShift;
phaseShift.AddUiWorldMapAreaIdSwap((uint32)679);
phaseShift.AddVisibleMapId((uint32)656, nullptr);
 PhasingHandler::SendToPlayer(player, phaseShift);
and its working, i mean the terrain swap, but after complete any quest that alter my phaseid the map swap back awain. no need to pick up a quest or something, simple after the code run, you type, .mod phase N and swap back inmediatle. I guess the new terrain swaped must be a phase where it can work, i dont see how to say it what phaseMask i want it stay. 
to try this, you cant type on a swaping map, .debug send setphaseshift 655 0 678 for example, on gilneas of curse, the .mod phase 183 or whatever you want and map swap back again.
/salute.

**Comment by mayorCuba** [comment]
nice , yes I am Cuban , 
que bien , si soy Cubano
