### ISSUE TITLE
[FIX]DB/SAI: added Scholomance Dungeon trash mobs skills fully....

### ISSUE THREAD

**Issue by cooler-SAI** [AshamaneProject/AshamaneCore#906]
**Description:**
patch add Scholomance Dungeon trash mobs skills fully,enjoy..))))

**Usefull Wowhead links:**
http://www.wowhead.com/scholomance#npcs

https://pastebin.com/KfKXYyh7

**Comment by HannibalRoG** [comment]
Thanks again for your contribution.
