### ISSUE TITLE
[FIX]DB/SAI: added Isle of Thunder zone fully scripts!! enjoy....

### ISSUE THREAD

**Issue by cooler-SAI** [AshamaneProject/AshamaneCore#912]
**Description:**
patch add Isle of Thunder zone fully scripts!! enjoy.... :grinning: 

**Usefull Wowhead links:**
http://www.wowhead.com/isle-of-thunder#npcs:0+1

https://pastebin.com/4ZCpp2gW

**Comment by Traesh** [comment]
Do you use any software to generate all this SAI ?

**Comment by cooler-SAI** [comment]
@Traesh , yes! 
https://mega.nz/#!jIckCCCT!LkCKVskFMiDU3_jn67dT2Mbx7FqCGh8fmc9RCZop8MI

**Comment by HannibalRoG** [comment]
You are full of surprises @cooler-SAI ;)
