### ISSUE TITLE
Pillars all over the blood elf area blocking npc's.

### ISSUE THREAD

**Issue by Painwithin** [AshamaneProject/AshamaneCore#913]
**Description:**
There is pillars all over the blood elf area "so far its the only areas i noticed" that has pillars that are not suppose to be there and is blocking NPC's and the pillars are not solid objects so you can walk through them.

I cant seem to target them to remove them myself but these pillars do make it frustrating as some quest givers are inside of them.

not even sure why these pillars are even there and i got no idea where i would start to try to remove them.

**Usefull Wowhead links:**

**Comment by cooler-SAI** [comment]
I don't see anything.... please make a screenshot where it is

**Comment by Painwithin** [comment]
Its in the blood elf starting area and the next city over that i have seen them i got a screenshot in the lost on ac-web

--
Sent from myMail for Android

Saturday, 21 April 2018, 04:33PM -04:00 from Ander notifications@github.com<mailto:notifications@github.com>:


I don't see anything.... please make a screenshot where it is

**Comment by cooler-SAI** [comment]
hm...now looking on it - can't see any pillars

**Comment by Painwithin** [comment]
https://ibb.co/cSW17S

here is the screenshot i took, see the pillars? there all over the place.

**Comment by cooler-SAI** [comment]
Can anyone else confirm it?coz I don't have this issue on my server

**Comment by Painwithin** [comment]
What is weird about this is im using the repack on ac-web and got this and also tried loading a fresh DB to be sure it wasnt something i did.

**Comment by HannibalRoG** [comment]
That error does not belong to AshamaneCore or DB and is not considered valid. Maybe a repack issue.
