### ISSUE TITLE
Warsong Gulch flag issue

### ISSUE THREAD

**Issue by silviu2008** [AshamaneProject/AshamaneCore#917]
Revision: TrinityCore rev. 500540be6fd0 2018-04-18 16:20:06 -0400 (master branch) (Win64, RelWithDebInfo, Static)

Description: capture opposite team flag -> try to drop it to your base -> nothing happens ...

**Comment by Traesh** [comment]
Update to latest ADB or import sql\ashamane\old\hotfixes\2018_04_11_00_hotfixes.sql

**Comment by silviu2008** [comment]
It was imported by the automatic updater, but it doesn't work.
