### ISSUE TITLE
Migration Dhem

### ISSUE THREAD

**Issue by Pretirkal** [AshamaneProject/AshamaneCore#920]
**Description:**
Hello,
migration of the character Dhem.
I do not have the right object.

**Usefull Wowhead links:**

https://firestorm-servers.com/fr/community/armory/6/12/2587593

http://fr.wowhead.com/item=137061/regard-acere-de-raddon

http://fr.wowhead.com/item=121284/pendentif-cauchemardesque&bonus=1826:1507

http://fr.wowhead.com/item=121298/mantelet-de-peau-deffroi&bonus=1826:1507

http://fr.wowhead.com/item=134365/grande-cape-rongee-par-le-neant&bonus=1826:1507

http://fr.wowhead.com/item=139109/robe-crin-de-rive&bonus=1826:1507

http://fr.wowhead.com/item=121292/brassards-de-peau-deffroi&bonus=1826:1507

http://fr.wowhead.com/item=121295/gants-de-peau-deffroi&bonus=1826:1507

http://fr.wowhead.com/item=121299/ceinturon-de-peau-deffroi&bonus=1826:1507

http://fr.wowhead.com/item=121294/jambieres-de-peau-deffroi&bonus=1826:1507

http://fr.wowhead.com/item=134193/mocassins-en-peau-de-biorn&bonus=1826:1507

http://fr.wowhead.com/item=134367/bague-de-legionnaire&bonus=1826:1507

http://fr.wowhead.com/item=121288/jonc-cauchemardesque&bonus=1826:1507

http://fr.wowhead.com/item=139075/fourberie-du-rampant-forestier&bonus=1826:1507

http://fr.wowhead.com/item=134379/eclat-de-pierre-de-sang-infernale&bonus=1826:1507

**Comment by Traesh** [comment]
Hello, as stated on the website, migration's item are limited to ilvl 820, that's why all items superior to this limit are replaced by an available 820 equivalent
