### ISSUE TITLE
[FIX]DB/SAI: added Mogu'shan Vaults trash mobs

### ISSUE THREAD

**Issue by cooler-SAI** [AshamaneProject/AshamaneCore#921]
**Description:**
patch add Mogu'shan Vaults trash mobs

**Usefull Wowhead links:**
http://www.wowhead.com/mogushan-vaults#npcs

https://pastebin.com/XBXm0Vus

**Comment by Traesh** [comment]
Would it be easier for you to have push access ?

**Comment by cooler-SAI** [comment]
give me repo access )))

**Comment by Traesh** [comment]
Done, welcome in the team :) You can join Ashamane discord if you want (https://discord.gg/kaP2ZVS), i'll grant you Contributor/Dev role

**Comment by cooler-SAI** [comment]
thanks))will help as more as I can

**Comment by HannibalRoG** [comment]
Welcome

**Comment by cooler-SAI** [comment]
@HannibalRoG ,thanks
