### ISSUE TITLE
Arme mage bugez (morte)

### ISSUE THREAD

**Issue by Melo51240** [AshamaneProject/AshamaneCore#922]
**Description:**
Bonjour , depuis la mise a jour du serveur j'ai perdu mon arme gauche de Coeur du phénix mais j'ai Felo'melorn l'arme droite et aussi elle c'est remise a 0 alors qu'elle était lvl 68/69 
Merci ! 
Melo

**Usefull Wowhead links:**
http://fr.wowhead.com/item=128820/felomelorn
http://fr.wowhead.com/item=133959/coeur-du-phenix

**Comment by Traesh** [comment]
Réglé en jeu
