### ISSUE TITLE
Update 26365 without a public patch, developer need that.

### ISSUE THREAD

**Issue by sergemanuel** [AshamaneProject/AshamaneCore#926]
**Description:**
Update de client build without a public patch for that build from the old one, some have not access to blizard or anything like that. Please can someone public if there a patch to update client from 26124 to 26365. if posible in dl.ashamane or a link i dont know, im tired looking on google but i cant fine any.

thanks,

**Comment by Traesh** [comment]
You just have to download https://dl.ashamane.com/7.3.5/26365.zip and put it in your old wow

Enjoy :)

**Comment by sergemanuel** [comment]
Traesh, i have copied before, but i cant parch them, unable to find pattern error. can you share a executable already patched o if there is a solution to patch better then. thanks.

**Comment by sergemanuel** [comment]
something is not right man. look, I copied you files, but only open mi client in online mode, if my pc have not conection to internet, then no open de client, with the old one that not happens, the old ones open event without any conection, of curse, the not conect with anyserver but open. the principal problem of curse is that i havent continuos access to internet, and repeat, my old client open without the open internet connection, why those you give me not ?

**Comment by sergemanuel** [comment]
you mean, I open the client conected to internet because it have to download context, but my question one it download you request files, always i will need a conection? 
the client before i have 7.3.5 26124 not need internet conection to open. 
look, sorry bather so much, i never update a client, we here work olmost time offline, or on a local network, never update before. i have been see example a patch about 1.5 Gb that update a client from a version to another, but i cant find nothign like this to this case, because de etire client is not a posibility for me.

**Comment by HannibalRoG** [comment]
@sergemanuel Dónde tu vives? quizas puedas venir a buscarlo a la casa, tengo entendido que eres cubano ¿no?

**Comment by sergemanuel** [comment]
habana, la lisa, la uci espesificamente. falta haria man poder copiar eso man, pq llevo dias trabajando sobre la 26365 usando el cliente de la 26124, metiendole las manos ahi al server para que me dejara entrar. de hecho no tengo para poder hacer el clone del respositorio, lo cual me limita de subir cosas y bajar commits solamentes, cuando actualizo es bajando todo y es la ostia. se pudiera ver a travez tuyo para que subas las cosas si las crees convenientes. saludos.

**Comment by HannibalRoG** [comment]
Entra al discord de Ashamane https://discord.gg/s78mUBJ y envíame mp para enviarte mi correo y ponernos de acuerdo, soy de Santa Fe Playa.
