### ISSUE TITLE
Worgen Starter area not working.

### ISSUE THREAD

**Issue by Ysil69** [AshamaneProject/AshamaneCore#934]
**Description:**
Something amiss won't turn in and doesn't "advance" the area. Can't even force all hell breaks lose.

**Usefull Wowhead links:**
http://www.wowhead.com/quest=14091/somethings-amiss

**Comment by cooler-SAI** [comment]
Work in progress......

**Comment by Traesh** [comment]
in progress != completed :)

**Comment by cooler-SAI** [comment]
@Traesh / I am too lazy for this )))  https://github.com/AshamaneProject/AshamaneCore/commit/c78b9d234451a6204a6feb5b5d9289f4e6013174
