### ISSUE TITLE
BG issues

### ISSUE THREAD

**Issue by silviu2008** [AshamaneProject/AshamaneCore#936]
TrinityCore rev. 500540be6fd0 2018-04-18 16:20:06 -0400 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

Issues:
- most of the times you get the message that BG will prematurely end because of not enough players, but there are enough. I put in battleground_template a minimum players of 1 for WSG, and with 4 players on each side, I  get this message.
- capture flag in WSG is still broken

**Comment by Traesh** [comment]
Can't reproduce

For the second point, as i already said, please make sure you have all last hotfixes updates.

**Comment by silviu2008** [comment]
I do have all the hotfixes added! It jus doesn't work. Test i if you have the time please. Thanks.
