### ISSUE TITLE
Fixes DBErrors Log - More DBErros Fixes

### ISSUE THREAD

**Issue by Sefrenia-Caecias** [AshamaneProject/AshamaneCore#949]
The attached file contains 2.666 repairs to the DBErrors Log, corresponding to:

* 3 repairs of `creature_template_addon`.
* 185 repairs of `gameobject_addon`.
* 54 repairs of `quest_details`.
* 1,302 repairs of `quest_template`.
* 476 repairs of `quest_objectives`.
* 646 repairs of `quest_template_addon`.

------------------------------------------------------------------

El archivo adjunto contiene 2.666 reparaciones del DBErrors Log, correspondientes a:

* 3 reparaciones de `creature_template_addon`.
* 185 reparaciones de `gameobject_addon`.
* 54 reparaciones de `quest_details`.
* 1.302 reparaciones de `quest_template`.
* 476 reparaciones de `quest_objectives`.
* 646 reparaciones de `quest_template_addon`.

[Fixes DBErrors Log - More DBErros Fixes.log](https://github.com/AshamaneProject/AshamaneCore/files/1940494/Fixes.DBErrors.Log.-.More.DBErros.Fixes.log)

**Comment by cooler-SAI** [comment]
very good fixes!! scripnames leave to me - also completed fix all of them)))
