### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by darkmord1991** [AshamaneProject/AshamaneCore#951]
**Description:**
![image](https://user-images.githubusercontent.com/811881/39205975-76ee1052-47fc-11e8-8620-4d479a83f376.png)

CHANGEME Description of the problem or issue here. Wowhead link will be appreciated.

**Current behaviour:**

Client crash when running this way up.
Problems with 3 Players now.
Deleted Cache and tested again.
Same problem.

**Expected behaviour:**
No crash

**Project(s): <-- Mandatory**

 [ ] Issue found playing in Live Ashamane Private Server.
 [x] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

Latest
https://github.com/AshamaneProject/AshamaneCore/commit/6a8592d5ee3d7be14d0bf964f2cf45dd6af0a960

**Database version**

Latest
https://github.com/AshamaneProject/AshamaneCore/commit/6a8592d5ee3d7be14d0bf964f2cf45dd6af0a960

**Operating system:** CHANGEME OS
Windows Server 2016
Client: Windows 10 1709

**Comment by Razfury** [comment]
Just your client the server doesn't crash>?

**Comment by darkmord1991** [comment]
Yes, only the Client

**Comment by HannibalRoG** [comment]
Same crash in Jade forest.

**Comment by darkmord1991** [comment]
DH also crashes the client now, after second quest

**Comment by michaelabrahantes** [comment]
in my case also crashes other characters ... until server is restarted

**Comment by darkmord1991** [comment]
I have multiple Client crashes all around the world now. Some in Orgrimmar, some in Dala, some in Legion, some in the DH Start area. But I have no idea where it comes from

**Comment by AdynatonNess** [comment]
Yes I have crashed in Legion, then unlock my carct--> tp to orgri and i still crashing at Orgri.. What should I do?

**Comment by Traesh** [comment]
@darkmord1991 Could you please apply SQL patches one by one and check which one make the client crash ? Is it only the big script_names fixes ?

**Comment by darkmord1991** [comment]
Now I applied the Scriptnames fix and it seems to work. but i need more time to confirm this. No crashes in the first 20 minutes and several regions. So I think we have a problem with those db error fixxes
