### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Bulbucan** [AshamaneProject/AshamaneCore#953]
https://github.com/AshamaneProject/AshamaneCore/blob/6a8592d5ee3d7be14d0bf964f2cf45dd6af0a960/src/server/game/Server/Packets/PetBattlePackets.h#L112
This line need to be replace with:
PetBattleEnviroUpdate PetBattleEnviroUpdates[3];

**Comment by HannibalRoG** [comment]
@traesh
