### ISSUE TITLE
Fixes DBErrors Log - queststarters + extras

### ISSUE THREAD

**Issue by Sefrenia-Caecias** [AshamaneProject/AshamaneCore#954]
The attached file contains 1,296 repairs to the DBErrors Log, corresponding to:

* 269 repairs of `gameobject_template`.
* 1,019 repairs of `creature_template`.
* 2 repairs of Ulduar (definitive fix of the problem "unsupported difficulty modes for map Id: 603").
* 2 repairs of `creature_addon`.
* 1 repair of `quest_template_addon`.
* 1 repair of `quest_poi`.
* 2 repairs of `pool_template`.

------------------------------------------

El archivo adjunto contiene 1.296 reparaciones del DBErrors Log, correspondientes a:

* 269 reparaciones de `gameobject_template`.
* 1.019 reparaciones de `creature_template`.
* 2 reparaciones de Ulduar (fix definitivo del problema "unsupported difficulty modes for map Id: 603").
* 2 reparaciones de `creature_addon`.
* 1 reparación de `quest_template_addon`.
* 1 reparación de `quest_poi`.
* 2 reparaciones de `pool_template`.

[Fixes DBErrors Log - queststarters + extras.log](https://github.com/AshamaneProject/AshamaneCore/files/1944255/Fixes.DBErrors.Log.-.queststarters.extras.log)

**Comment by HannibalRoG** [comment]
@cooler-SAI

**Comment by cooler-SAI** [comment]
good!)) @HannibalRoG ,you can continue add fixes fromthis guy,coz he is good)
