### ISSUE TITLE
Fixes DBErrors Log - spell_proc + extras

### ISSUE THREAD

**Issue by Sefrenia-Caecias** [AshamaneProject/AshamaneCore#957]
The attachment contains 1.737 repairs to the DBErrors Log, corresponding to:

* 1.001 repairs of `spell_proc`.
* 736 repairs to `item_enchantment_template`.

--------------------------------------

El archivo adjunto contiene 1.737 reparaciones del DBErrors Log, correspondientes a:

* 1.001 reparaciones de `spell_proc`.
* 736 reparaciones de `item_enchantment_template`.

[Fixes DBErrors Log - spell_proc + extras.log](https://github.com/AshamaneProject/AshamaneCore/files/1944973/Fixes.DBErrors.Log.-.spell_proc.extras.log)

**Comment by HannibalRoG** [comment]
Agregué la parte de spell_proc pero los delete de template los eliminé, saludos y gracias por tu trabajo.

Add all spell_proc part only, thanks for your work.

**Comment by Sefrenia-Caecias** [comment]
@HannibalRoG, creo que eso va a ser difícil, ya que las referencias borradas existen en la database World, pero no existen en las tablas "ItemRandomProperties.db2" e "ItemRandomSuffix.db2", que extraemos de nuestro WoW con las herramientas de compilación del Core en la carpeta DBC. En otras palabras, la Database dice que existen o existieron alguna vez, pero en las tablas extraidas ya no figuran, como si Blizzard las hubiera borrado del mismo modo que borró muchas cosas más con las actualizaciones del juego. Te paso ejemplos del DBError Log:

-**Property 8 used in `item_enchantment_template` by entry 61 doesn't have exist in ItemRandomProperties.db2**
-**Suffix 334 used in `item_enchantment_template` by entry 464 doesn't have exist in ItemRandomSuffix.db2**

Necesito que me orientes a este respecto, ya que el DBErrors Logs contiene cosas que faltan agregar, y otras que dejaron de existir, como podemos comprobar utilizando Wowhead. O si hay manera de añadir estos faltantes a tablas comunes, me enacntaría aprender cómo y ayudar :D

---------------------------------------------------

@HannibalRoG, I think that's going to be difficult, since the deleted references exist in the World database, but they do not exist in the "ItemRandomProperties.db2" and "ItemRandomSuffix.db2" tables, which we extract from our WoW with the compilation tools of the Core in the DBC folder. In other words, the Database says that they exist or ever existed, but in the extracted tables they no longer appear, as if Blizzard had erased them in the same way that it erased many other things with the game updates. I give you examples of the DBError Log:

-**Property 8 used in `item_enchantment_template` by entry 61 does not have exist in ItemRandomProperties.db2**
-**Suffix 334 used in `item_enchantment_template` by entry 464 does not exist in ItemRandomSuffix.db2**

I need you to guide me in this regard, since the DBErrors Logs contain things that need to be added, and others that ceased to exist, as we can verify using Wowhead. Or if there is a way to add these missing to common tables, I would love to learn how and help :D

**Comment by HannibalRoG** [comment]
Cierto, si es así entonces sobran.

**Comment by Sefrenia-Caecias** [comment]
Me quedo más tranquilo, entonces. Si me lo autorizas, en próximas reparaciones puedo detallarte los borrados que refieran a casos como este, o a parámetros inexistentes o sobrantes, para que puedas estar más seguro sobre el trabajo realizado.

-----------------------------------------

I'm more calm, then. If you authorize me, in future repairs I can detail the erasures that refer to cases like this, or nonexistent parameters or surplus, so you can be more confident about the work done.
