### ISSUE TITLE
Fixes DBErrors Log - Multiple fixes

### ISSUE THREAD

**Issue by Sefrenia-Caecias** [AshamaneProject/AshamaneCore#959]
The attached file contains 486 repairs of the DBErrors Log, corresponding to:

* 293 repairs of `creature_template`.
* 1 repair of `creature`.
* 77 repairs of `creature_equip_template`.
* 3 repairs of `game_event`.
* 23 repairs of `game_event_creature`.
* 5 repairs of `creature_addon`.
* 18 repairs of `gameobject`.
* 18 repairs of `gameobject_addon`.
* 24 repairs of `npc_spellclick_spells`.
* 5 repairs of `vehicle_template_accessory`.
* 19 repairs of `areatrigger_teleport`.

**Types of lines involved:**

-Creature (Entry: 352220) lists non-existing Modelid1 id (29680), this can crash the client: replaced Modelid1.

-No model data exist for `Modelid1` = 0 listed by creature (Entry: 352220): replaced Modelid1.

-Creature (Entry: 352220) does not have any existing display id in Modelid1 / Modelid2 / Modelid3 / Modelid4: replaced corresponding Modelid.

-Unknown item appearance for (ID = 128093, AppearanceModID = 0) pair in creature_equip_template.ItemID1 creature_equip_template.AppearanceModID1 for CreatureID = 93105 and ID = 1, forced to default: valid ItemID aggregates.

-Unknown item (ID = 53835) in creature_equip_template.ItemID1 for CreatureID = 10540 and ID = 1, forced to 0: valid ItemID aggregates, in the corresponding cases.

-Creature template (Entry: 130275) does not exist but you have a record in `creature_template_scaling`: added corresponding templates.

-Table `creature` has creature (Entry: 532980) with equipment_id 1 not found in table` creature_equip_template`, set to no equipment: modified corresponding value.

-Table `creature` have creature (GUID: 0 Entry: 532980) with` phaseid` 1 does not exist, set to 0: modified phaseid.

-Creature (GUID: 169917) does not exist but has a record in `creature_addon`: deleted addons from creatures positions that were removed at some point.

-Table `gameobject` has gameobject (GUID: 20372161 Entry: 242529) with invalid coordinates, skip: deleted GUIDES of gameobjects in ivory map.

-GameObject (GUID: 20372161) does not exist but has a record in gameobject_addon: eliminated gameobjects addons previously removed.

-`game_event_creature`: game event id (73) / (75) / (76) / (77) is out of range compared to max event id in `game_event`: recalibrated corresponding parameters.

-`game_event_gameobject`: game event id (73) / (76) / (77) is out of range compared to max event id in `game_event`: repaired automatically with the previous repair.

-Table npc_spellclick_spells creature: 31897 references unknown spellid 60123. Skipping entry: Deleted entries of spells and creatures that do not exist.

-npc_spellclick_spells: Creature template 78903 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing flag: modified wrong parameter.

-Table `vehicle_template_accessory`: creature template entry 6588 does not exist: deleted reference of nonexistent creature.

-Table `vehicle_template_accessory`: creature template entry 59464 has not data in npc_spellclick_spells: deleted invalid references.

-Area Trigger (ID: 4917) does not exist in AreaTrigger.dbc .: deleted references that ceased to exist in the corresponding DBC.

---------------------------------------------------------

El archivo adjunto contiene 486 reparaciones del DBErrors Log, correspondientes a:

* 293 reparaciones de `creature_template`.
* 1 reparación de `creature`.
* 77 reparaciones de `creature_equip_template`.
* 3 reparaciones de `game_event`.
* 23 reparaciones de `game_event_creature`.
* 5 reparaciones de `creature_addon`.
* 18 reparaciones de `gameobject`.
* 18 reparaciones de `gameobject_addon`.
* 24 reparaciones de `npc_spellclick_spells`.
* 5 reparaciones de `vehicle_template_accessory`.
* 19 reparaciones de `areatrigger_teleport`.

**Tipos de líneas involucradas:**

-Creature (Entry: 352220) lists non-existing Modelid1 id (29680), this can crash the client: reemplazado Modelid1.

-No model data exist for `Modelid1` = 0 listed by creature (Entry: 352220): reemplazado Modelid1.

-Creature (Entry: 352220) does not have any existing display id in Modelid1/Modelid2/Modelid3/Modelid4: reemplazado Modelid correspondiente.

-Unknown item appearance for (ID=128093, AppearanceModID=0) pair in creature_equip_template.ItemID1 creature_equip_template.AppearanceModID1 for CreatureID = 93105 and ID=1, forced to default: agregados ItemID válidos.

-Unknown item (ID=53835) in creature_equip_template.ItemID1 for CreatureID = 10540 and ID=1, forced to 0: agregados ItemID válidos, en los casos correspondientes.

-Creature template (Entry: 130275) does not exist but has a record in `creature_template_scaling`: agregados templates correspondientes.

-Table `creature` has creature (Entry: 532980) with equipment_id 1 not found in table `creature_equip_template`, set to no equipment: modificado valor correspondiente.

-Table `creature` have creature (GUID: 0 Entry: 532980) with `phaseid` 1 does not exist, set to 0: modificada phaseid.

-Creature (GUID: 169917) does not exist but has a record in `creature_addon`: eliminados addons de posiciones de creatures que fueron removidas en algún momento.

-Table `gameobject` has gameobject (GUID: 20372161 Entry: 242529) with invalid coordinates, skip: eliminadas GUIDS de gameobjects en mapa iválido.

-GameObject (GUID: 20372161) does not exist but has a record in gameobject_addon: eliminados addons de gameobjects removidos previamente.

-`game_event_creature`: game event id (73)/(75)/(76)/(77) is out of range compared to max event id in `game_event`: recalibrados parámetros correspondientes.

-`game_event_gameobject`: game event id (73)/(76)/(77) is out of range compared to max event id in `game_event`: reparadas automáticamente con la reparación anterior.

-Table npc_spellclick_spells creature: 31897 references unknown spellid 60123. Skipping entry: borradas entradas de spells y creatures inexistentes.

-npc_spellclick_spells: Creature template 78903 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing flag: modificado parámetro erróneo.

-Table `vehicle_template_accessory`: creature template entry 6588 does not exist: eliminada referencia de creature inexistente.

-Table `vehicle_template_accessory`: creature template entry 59464 has no data in npc_spellclick_spells: eliminadas referencias inválidas.

-Area Trigger (ID: 4917) does not exist in AreaTrigger.dbc.: eliminadas referencias que dejaron de existir en la DBC correspondiente.

[Fixes DBErrors Log - Multiple fixes.log](https://github.com/AshamaneProject/AshamaneCore/files/1948157/Fixes.DBErrors.Log.-.Multiple.fixes.log)

**Comment by Sefrenia-Caecias** [comment]
@HannibalRoG te dejé una explicación más detallada. Abrazos ;)

**Comment by Neredun** [comment]
https://github.com/AshamaneProject/AshamaneCore/commit/9b1ab1e92a925a35955154b1db31792fe3c30a5e Now that this was commited, i procceed to close it. Good work!
