### ISSUE TITLE
[CRITICAL] Restoration Affinity and Frenzed Regeneration

### ISSUE THREAD

**Issue by GeneralissimeDarklinks** [AshamaneProject/AshamaneCore#960]
**Description:** Restoration Affinity does not give the spells bound with the talent as well as the passive spell Ysera gift

Frenzed Regeneration to a regen of 1 health per hit received by the Druid

Wowhead link: 
http://www.wowhead.com/spell=22842
http://fr.wowhead.com/spell=197492

**Comment by Traesh** [comment]
Fixed in https://github.com/AshamaneProject/AshamaneCore/commit/47b592d055e410eeafa864cf660eb9f9237b8d4c
