### ISSUE TITLE
Penance bug

### ISSUE THREAD

**Issue by Questiero** [AshamaneProject/AshamaneCore#965]
**Description:**

Took damage while casting a spell.

**Current behaviour:**

When I use the spell Penance ( http://www.wowhead.com/spell=186723/penance ) on an ennemy, the damages he receive are dealt to me too.

**Expected behaviour:**

The spell shouldn't dealt me these damage.

**Project(s): <-- Mandatory**

 [X] Issue found playing in Live Ashamane Private Server.
 [ ] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

CHANGEME Mandatory if Project == compiled master repo from Git, found it in first line of Server.log

**Database version**

CHANGEME What DB do you use, TDB, ADB, other.

**Operating system:** Windows 10

**Comment by Neredun** [comment]
if i remember correctly. It also heals you when you cast the spell on a ally.

**Comment by Questiero** [comment]
I never used it on an ally, so it appears that the effect of this spell, heal or damage, is applied on the caster too.

**Comment by HannibalRoG** [comment]
#673
