### ISSUE TITLE
Lonely wolf

### ISSUE THREAD

**Issue by Oldarorn** [AshamaneProject/AshamaneCore#966]
**Description:** 

Lonely wolf doesn't work properly. When you choose this talent, your pets spells are disabled (that's the point of the spell) but here, we can still invoke them.

http://fr.wowhead.com/spell=155228/loup-solitaire

**Current behaviour:**

I don't know if the spells gives his buff but I'm sure you can still use your pets

**Expected behaviour:**

Give a damage buff and disable Call pet
http://www.wowhead.com/search?q=call+pet

**Project(s): <-- Mandatory**

 [X] Issue found playing in Live Ashamane Private Server.
 [ ] Issue found in a compiled master repo from Git.

**Database version**

The actual one

**Operating system:** WINDOWS

**Comment by HannibalRoG** [comment]
#502
