### ISSUE TITLE
2018_04_27_01_world_start_area_fix.sql failed to apply 

### ISSUE THREAD

**Issue by vader75** [AshamaneProject/AshamaneCore#979]
**Description:**

Sql database update failed 

**Current behaviour:**

ashamane/world/2018_04_27_01_world_start_area_fix.sql failed to apply to database due to error. World server does not start.

>> Applying update "2018_04_27_01_world_start_area_fix.sql" '4D2A80E'...
ERROR 1062 (23000) at line 3: Duplicate entry '210112069' for key 'PRIMARY'

**Expected behaviour:**

Application of sql should be error free, server world server should start

**Project(s): <-- Mandatory**

 [] Issue found playing in Live Ashamane Private Server.
 [x] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

Mandatory if Project  Git, https://github.com/AshamaneProject/AshamaneCore, not sure I guess latest commit

**Database version**

latest

**Operating system: Windows 7 Pro

**Comment by cooler-SAI** [comment]
fixed
