### ISSUE TITLE
Wizard ! weapon bug skill 

### ISSUE THREAD

**Issue by Melo51240** [AshamaneProject/AshamaneCore#987]
**Description:**
Hey , if you have fire specialization with the weapon logically you have the spell of weapon but if you switch your specialization to the arcane you stay with the spell of weapon fire and the spell of the weapon arcanes 

CHANGEME Description of the problem or issue here. Wowhead link will be appreciated.

**Current behaviour:**
Logically if you switch your specialization you lost the spell of weapon 
CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/). Do not post entire log here.

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Project(s): <-- Mandatory**

 [ ] Issue found playing in Live Ashamane Private Server.
 [ ] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

CHANGEME Mandatory if Project == compiled master repo from Git, found it in first line of Server.log

**Database version**

CHANGEME What DB do you use, TDB, ADB, other.

**Operating system:** CHANGEME OS

**Comment by HannibalRoG** [comment]
You forgot the most important info, project and database version.
