### ISSUE TITLE
vmap4assembler: file name too long

### ISSUE THREAD

**Issue by cljnnn** [AshamaneProject/AshamaneCore#988]
**Description:**

the build is from the latest code. To dump the maps, I used the below commands batch, but I can't get success with vmap4assembler
mapextractor -i /root/wowgame
vmap4extractor -d /root/wowgame
mkdir vmaps
vmap4assembler Buildings vmaps

**Current behaviour:**

Outputs: vmap4assembler Buildings vmaps
using Buildings as source directory and writing output to vmaps
Read coordinate mapping...
Error reading ModelSpawn, file name too long!

Converting Model Files
Ok, all done

**Project(s): <-- Mandatory**

 [ ] Issue found playing in Live Ashamane Private Server.
 [*] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:** 

TrinityCore rev. 11c3c456b7e1+ 2018-04-18 20:27:45 +0300 (master branch) (Unix, Release, Dynamic) (VMAP assembler)

**Comment by cooler-SAI** [comment]
can't confirm, all good!update core to last rev

**Comment by HannibalRoG** [comment]
Possibly very old core

**Comment by cljnnn** [comment]
Thank you, yep, I didn't copy the updated libcommon.so. It works now.
