### ISSUE TITLE
DBErrors Log - Quest 9403 (The Purest Water)

### ISSUE THREAD

**Issue by Sefrenia-Caecias** [AshamaneProject/AshamaneCore#989]
In the DBErrors Log a quest appeared that was not there before, with this caption: _"Quest 9403 objective 260310 has non existing item entry 0, quest can not be done"_. I assume that it is of some repair entered in these days. I leave two ways to solve it, for whoever was the author of the original modification:

1) If what is missing is the item: UPDATE `quest_objectives` SET` ObjectID` = '23552' , `Amount`='1' WHERE `ID` = 260310;

2) If what is left over is the item: DELETE FROM `quest_objectives` WHERE` ID` = 260310;

Whatever you choose, eliminate this error ;)

----------------------------------------------

En el DBErrors Log apareció una quest que antes no estaba, con esta leyenda: _"Quest 9403 objective 260310 has non existing item entry 0, quest can't be done"_. Asumo que es de alguna reparación ingresada en estos días. Dejo dos formas de resolverla, para quien haya sido el autor de la modifcación original:

1) Si lo que falta es el item: UPDATE `quest_objectives` SET `ObjectID`='23552', `Amount`='1'  WHERE  `ID`=260310;

2) Si lo que sobra es el item: DELETE FROM `quest_objectives` WHERE  `ID`=260310;

Como sea que elijan, eliminen este error ;)

**Comment by Sefrenia-Caecias** [comment]
It could be, but I must warn you that my command of English is limited to Google Translate XD

Anyway, I think the important thing now is to continue cleaning the DBErrors Log, to improve the performance of the game and provide a better image as a project ;)

------------------------------------

Podría ser, pero debo advertirte que mi dominio del inglés se limita al Google Traductor XD

De todos modos, creo que lo importante ahora es seguir limpiando el DBErrors Log, para mejorar la performance del juego y brindar una mejor imagen como proyecto ;)

**Comment by cooler-SAI** [comment]
@Traesh , can you add this guy?

**Comment by Traesh** [comment]
@Sefrenia-Caecias You should join the Ashamane discord so we can communicate easily in case of commit problem :)

I'm adding your to the SQL team, please follow the naming convention for SQL files (just check the other ones)

**Comment by cooler-SAI** [comment]
@Sefrenia-Caecias ,check your github e-mail for join

**Comment by Sefrenia-Caecias** [comment]
Thank you very much. It is done. Now I will see to connect to the Discord to receive the work instructions ;)

-----------------------------

Muchas gracias. Ya está hecho. Ahora veré de conectarme al Discord para recibir las instrucciones de trabajo ;)
