### ISSUE TITLE
Fixes DBErrors Log - disenchant_loot_template + extras

### ISSUE THREAD

**Issue by Sefrenia-Caecias** [AshamaneProject/AshamaneCore#993]
The attached file contains 174 repairs to the DBErrors Log, corresponding to:

* 75 repairs of 'disenchant_loot_template'.
* 2 repairs of `creature_addon`.
* 97 repairs of `gameobject_addon`.

**Types of lines involved:**

-Table 'disenchant_loot_template' Entry 5 Item 10978: item entry not listed in `item_template` - skipped: replaced references of items that no longer exist.

-Table 'disenchant_loot_template' Entry 9 does not exist: fixed automatically with the previous processing.

-Table 'disenchant_loot_template' entry 136 group 1 has total chance> 100% (200.000000): recalibrated percentage.

-Creature (GUID: 20343418) does not exist but has a record in `creature_addon`: deleted references of creatures deleted in previous update.

-GameObject (GUID: 20361660) does not exist but has a record in `gameobject_addon`: deleted references of objects deleted in previous update.

--------------------------------------

El archivo adjunto contiene 174 reparaciones del DBErrors Log, correspondientes a:

* 75 reparaciones de 'disenchant_loot_template'.
* 2 reparaciones de `creature_addon`.
* 97 reparaciones de `gameobject_addon`.

**Tipos de líneas involucradas:**

-Table 'disenchant_loot_template' Entry 5 Item 10978: item entry not listed in `item_template` - skipped: reemplazadas referencias de items que ya no existen.

-Table 'disenchant_loot_template' Entry 9 does not exist: solucionado automáticamente con la trparación anterior.

-Table 'disenchant_loot_template' entry 136 group 1 has total chance > 100% (200.000000): recalibrado porcentaje.

-Creature (GUID: 20343418) does not exist but has a record in `creature_addon`: eliminadas referencias de creatures borradas en anterior update.

-GameObject (GUID: 20361660) does not exist but has a record in `gameobject_addon`: eliminadas referencias de objects borrados en anterior update.

[Fixes DBErrors Log - disenchant_loot_template + extras.log](https://github.com/AshamaneProject/AshamaneCore/files/1959504/Fixes.DBErrors.Log.-.disenchant_loot_template.extras.log)

**Comment by cooler-SAI** [comment]
heyy,man! u can add fixes by yourself to repo

**Comment by Sefrenia-Caecias** [comment]
I do not know how to do it XD

**Comment by cooler-SAI** [comment]
@Sefrenia-Caecias , see https://www.youtube.com/watch?v=ruieT3Nkg2M
first add sql file to repo folder
on source folder right click mouse - git bash
git pull origin master
this for pull new commits and update repo
than:
git add . 
place point after add
this will add changes
than add commit:
git commit -m "here write commit"
and pull make:
git pull origin master

**Comment by Sefrenia-Caecias** [comment]
Very complicated. And I'm stupid. I do the repairs, you upload them XD

**Comment by Neredun** [comment]
@Sefrenia-Caecias es tan simple como ir hasta la sql > ashamane > world y le das a create new file o upload. Y cambias el nombre según fecha_mes_dia_número de archivo sql del día (en general, no que sea el segundo o el tercero que pones, si no el que se pone) y la database que cambias (casi siempre será world así que...) por ejemplo: 2018_04_30_00_world.sql (nunca olvides la extensión... ya me ha pasado xD)

**Comment by Sefrenia-Caecias** [comment]
No me sale : (

**Comment by Neredun** [comment]
https://github.com/AshamaneProject/AshamaneCore/tree/master/sql/ashamane/world fijate arriba a la derecha. Ahí están las opciones que yo decía. Es realmente simple ya lo veras xD

**Comment by Sefrenia-Caecias** [comment]
Sos un genio. Ya los pude subir. Mil gracias :D
